export const BADGE_LABELS = {
  obrigatorio: "Obrigatorio",
  recomendado: "Recomendado",
  condicional: "Condicional",
};

export function flattenOnboardingItems(secoes = SECOES_ONBOARDING) {
  return secoes.flatMap((secao) =>
    secao.itens.map((item) => ({
      ...item,
      secaoId: secao.id,
      secaoTitulo: secao.titulo,
    })),
  );
}

export function buildGuiaHref(path, guiaId) {
  const sep = path.includes("?") ? "&" : "?";
  return `${path}${sep}guia=${encodeURIComponent(guiaId)}`;
}

export const SECOES_ONBOARDING = [
  {
    id: "empresa-acesso",
    titulo: "1) Empresa, acesso e permissoes",
    resumo: "Identifique a empresa, revise acesso e confirme quais modulos estao liberados.",
    itens: [
      {
        id: "empresa-dados",
        titulo: "Conferir dados cadastrais da empresa",
        tipo: "obrigatorio",
        onde: "/configuracoes",
        resultado: "Recibos, documentos e comunicacoes usam os dados certos.",
        autoCheckKey: "empresaDados",
      },
      {
        id: "empresa-fiscal",
        titulo: "Conferir configuracao fiscal basica",
        tipo: "obrigatorio",
        onde: "/configuracoes/fiscal",
        resultado: "Impostos, margem e documentos fiscais partem de uma base coerente.",
        autoCheckKey: "empresaFiscal",
      },
      {
        id: "usuarios-permissoes",
        titulo: "Criar usuarios e revisar permissoes",
        tipo: "recomendado",
        onde: "/admin/usuarios",
        resultado: "Cada pessoa opera com acesso adequado, sem depender do admin.",
        autoCheckKey: "usuarios",
      },
      {
        id: "plano-modulos",
        titulo: "Conferir plano e modulos ativos",
        tipo: "recomendado",
        onde: "/meu-plano",
        resultado: "O guia mostra apenas o que faz sentido para a operacao contratada.",
      },
    ],
  },
  {
    id: "financeiro-obrigatorio",
    titulo: "2) Financeiro obrigatorio",
    resumo: "Prepare caixa, recebimentos, DRE e conciliacao antes da primeira venda real.",
    itens: [
      {
        id: "contas-bancarias",
        titulo: "Conferir bancos, caixas e carteiras",
        tipo: "obrigatorio",
        onde: "/cadastros/financeiro/bancos",
        resultado: "O sistema sabe onde o dinheiro entra e sai.",
        autoCheckKey: "contasBancarias",
      },
      {
        id: "formas-pagamento",
        titulo: "Conferir formas de pagamento",
        tipo: "obrigatorio",
        onde: "/cadastros/financeiro/formas-pagamento",
        resultado: "O PDV consegue finalizar vendas e gerar recebiveis quando necessario.",
        autoCheckKey: "formasPagamento",
      },
      {
        id: "operadoras-cartao",
        titulo: "Cadastrar operadoras de cartao",
        tipo: "condicional",
        condicao: "Obrigatorio se vender em cartao",
        onde: "/cadastros/financeiro/operadoras",
        resultado: "Taxas, prazos e conciliacao de cartao ficam mais confiaveis.",
        autoCheckKey: "operadoras",
      },
      {
        id: "categorias-financeiras",
        titulo: "Revisar categorias financeiras",
        tipo: "obrigatorio",
        onde: "/cadastros/categorias-financeiras",
        resultado: "Fluxo de caixa e contas usam classificacao consistente.",
        autoCheckKey: "categoriasFinanceiras",
      },
      {
        id: "dre-tipos-despesa",
        titulo: "Revisar DRE e tipos de despesa",
        tipo: "obrigatorio",
        onde: "/financeiro/dre",
        resultado: "Lucro, custos e despesas aparecem com leitura gerencial correta.",
        autoCheckKey: "dreBase",
      },
    ],
  },
  {
    id: "cadastros-base",
    titulo: "3) Cadastros base da operacao",
    resumo: "Organize produtos, pessoas e pets antes de rodar o atendimento real.",
    itens: [
      {
        id: "departamentos-categorias-marcas",
        titulo: "Conferir departamentos, categorias e marcas",
        tipo: "obrigatorio",
        onde: "/cadastros/categorias",
        resultado: "Produtos ficam organizados para venda, relatorios e comissao.",
        autoCheckKey: "categoriasProduto",
      },
      {
        id: "produtos",
        titulo: "Cadastrar ou importar produtos vendaveis",
        tipo: "obrigatorio",
        onde: "/produtos",
        resultado: "PDV, estoque, ecommerce e app passam a ter catalogo operacional.",
        autoCheckKey: "produtos",
      },
      {
        id: "estoque-minimo",
        titulo: "Revisar estoque inicial e estoque minimo",
        tipo: "recomendado",
        onde: "/produtos",
        resultado: "Alertas de ruptura e reposicao ficam mais uteis.",
        autoCheckKey: "estoqueMinimo",
      },
      {
        id: "pessoas",
        titulo: "Cadastrar clientes, fornecedores e equipe",
        tipo: "obrigatorio",
        onde: "/clientes",
        resultado: "Vendas, compras, financeiro e atendimento ficam vinculados a pessoas reais.",
        autoCheckKey: "pessoas",
      },
      {
        id: "pets",
        titulo: "Cadastrar pets dos clientes",
        tipo: "recomendado",
        onde: "/pets",
        resultado: "Historico, recorrencia, veterinario e banho/tosa ganham contexto.",
        autoCheckKey: "pets",
      },
      {
        id: "especies-racas-opcoes-racao",
        titulo: "Revisar especies, racas e opcoes de racao",
        tipo: "recomendado",
        onde: "/cadastros/especies-racas",
        resultado: "Cadastro de pets e analises de racao ficam padronizados.",
        autoCheckKey: "opcoesRacao",
      },
    ],
  },
  {
    id: "operacao-venda",
    titulo: "4) PDV, caixa e primeira venda",
    resumo: "Teste o ciclo minimo antes de operar com cliente real.",
    itens: [
      {
        id: "abrir-caixa",
        titulo: "Abrir caixa com saldo inicial",
        tipo: "obrigatorio",
        onde: "/pdv",
        resultado: "O dia de venda comeca com conferencia de caixa.",
        autoCheckKey: "caixaAberto",
      },
      {
        id: "venda-teste",
        titulo: "Fazer venda teste",
        tipo: "obrigatorio",
        onde: "/pdv",
        resultado: "Venda, pagamento, estoque e financeiro sao validados juntos.",
        autoCheckKey: "temVendas",
      },
      {
        id: "contas-receber-venda",
        titulo: "Conferir contas a receber da venda",
        tipo: "obrigatorio",
        onde: "/financeiro/contas-receber",
        resultado: "Recebiveis aparecem quando a forma de pagamento exige prazo.",
      },
      {
        id: "fechar-caixa",
        titulo: "Fechar caixa e conferir diferenca",
        tipo: "obrigatorio",
        onde: "/meus-caixas",
        resultado: "A rotina diaria fica validada ate a conferencia final.",
      },
    ],
  },
  {
    id: "compras-estoque",
    titulo: "5) Compras, estoque e entrada XML",
    resumo: "Valide reposicao, custo, impostos de entrada e integracoes.",
    itens: [
      {
        id: "fornecedores",
        titulo: "Cadastrar fornecedores principais",
        tipo: "recomendado",
        onde: "/clientes",
        resultado: "Compras e produtos ficam vinculados ao fornecedor certo.",
        autoCheckKey: "fornecedores",
      },
      {
        id: "compras-pedidos",
        titulo: "Registrar pedido de compra",
        tipo: "condicional",
        condicao: "Obrigatorio se usar modulo Compras",
        onde: "/compras/pedidos",
        resultado: "Reposicao passa a ter pedido, recebimento e historico.",
        modulo: "compras",
        autoCheckKey: "pedidoCompra",
      },
      {
        id: "compras-entrada-xml",
        titulo: "Processar entrada XML ou nota de compra",
        tipo: "condicional",
        condicao: "Obrigatorio se usar entrada fiscal de mercadoria",
        onde: "/compras/entrada-xml",
        resultado: "Custos, impostos, divergencias e estoque sao conferidos pela NF.",
        modulo: "compras",
        autoCheckKey: "entradaXml",
      },
      {
        id: "bling-integracao",
        titulo: "Validar integracao Bling",
        tipo: "condicional",
        condicao: "Obrigatorio se usar Bling",
        onde: "/produtos/sinc-bling",
        resultado: "Produtos, pedidos e monitoramento ficam alinhados com o Bling.",
        modulo: "bling",
        autoCheckKey: "blingConfig",
      },
    ],
  },
  {
    id: "modulos-operacao",
    titulo: "6) Modulos por tipo de operacao",
    resumo: "Ative apenas os fluxos que fazem sentido para o cliente.",
    itens: [
      {
        id: "modulo-entregas",
        titulo: "Configurar entregas",
        tipo: "condicional",
        condicao: "Se a loja faz delivery",
        onde: "/configuracoes/entregas",
        resultado: "Rotas, taxas, origem e entregadores ficam prontos.",
        modulo: "entregas",
        autoCheckKey: "configEntrega",
      },
      {
        id: "modulo-comissoes",
        titulo: "Configurar comissoes",
        tipo: "condicional",
        condicao: "Se a equipe recebe comissao",
        onde: "/comissoes",
        resultado: "Vendas geram calculo de comissao conforme regra definida.",
        modulo: "comissoes",
        autoCheckKey: "comissoesConfig",
      },
      {
        id: "modulo-banho-tosa",
        titulo: "Configurar Banho & Tosa",
        tipo: "condicional",
        condicao: "Se a loja agenda banho/tosa",
        onde: "/banho-tosa/servicos",
        resultado: "Servicos, agenda, recursos e fila ficam prontos para atendimento.",
        modulo: "banho_tosa",
        autoCheckKey: "banhoTosaServicos",
      },
      {
        id: "modulo-veterinario",
        titulo: "Configurar modulo veterinario",
        tipo: "condicional",
        condicao: "Se a empresa usa clinica veterinaria",
        onde: "/veterinario/configuracoes",
        resultado: "Agenda, consultorios, parceiros e catalogos clinicos ficam preparados.",
        modulo: "veterinario",
        autoCheckKey: "vetConfig",
      },
      {
        id: "modulo-ecommerce",
        titulo: "Configurar ecommerce",
        tipo: "condicional",
        condicao: "Se vender online",
        onde: "/ecommerce/configuracoes",
        resultado: "Loja, retirada/entrega, pagamento e catalogo online ficam prontos.",
        modulo: "ecommerce",
        autoCheckKey: "ecommerceConfig",
      },
      {
        id: "modulo-campanhas",
        titulo: "Criar primeira campanha",
        tipo: "condicional",
        condicao: "Se usar campanhas",
        onde: "/campanhas",
        resultado: "Cliente ja sai com uma acao comercial configurada.",
        modulo: "campanhas",
        autoCheckKey: "campanhas",
      },
      {
        id: "modulo-whatsapp",
        titulo: "Configurar WhatsApp",
        tipo: "condicional",
        condicao: "Se usar atendimento ou automacao via WhatsApp",
        onde: "/ia/whatsapp",
        resultado: "Atendimento, handoff e automacoes ficam rastreaveis.",
        modulo: "whatsapp",
        autoCheckKey: "whatsappConfig",
      },
    ],
  },
  {
    id: "validacao-final",
    titulo: "7) Validacao final",
    resumo: "Confira o sistema como usuario real antes de encerrar a implantacao.",
    itens: [
      {
        id: "validacao-fluxo-caixa",
        titulo: "Conferir fluxo de caixa",
        tipo: "obrigatorio",
        onde: "/financeiro/fluxo-caixa",
        resultado: "Entradas e saidas aparecem com datas e contas corretas.",
      },
      {
        id: "validacao-dre",
        titulo: "Conferir DRE",
        tipo: "obrigatorio",
        onde: "/financeiro/dre",
        resultado: "Receitas, custos e despesas aparecem em leitura gerencial.",
      },
      {
        id: "validacao-relatorios",
        titulo: "Conferir relatorios de venda e estoque",
        tipo: "obrigatorio",
        onde: "/financeiro/relatorio-vendas",
        resultado: "Gestor consegue tomar decisao com dados confiaveis.",
      },
      {
        id: "validacao-usuario-operacional",
        titulo: "Testar com usuario operacional",
        tipo: "obrigatorio",
        onde: "/admin/usuarios",
        resultado: "A rotina funciona sem usar acesso de administrador.",
      },
    ],
  },
];
