"""Catalogo ficticio usado pela vitrine comercial da conta Demo."""

from decimal import Decimal


DEMO_RATION_SHOWCASE_PRODUCTS = (
    {
        "code": "DEMO-RACAO-COMP-001",
        "name": "Racao VivaPata Performance Caes Adultos Frango 15 kg",
        "brand": "VivaPata Demo",
        "classification": "premium",
        "line": "Premium",
        "species": "dog",
        "category": "adulto",
        "phase": "Adulto",
        "size": "Todos",
        "flavor": "Frango",
        "weight": Decimal("15"),
        "cost": Decimal("118.90"),
        "price": Decimal("199.90"),
        "stock": Decimal("24"),
        "minimum_stock": Decimal("8"),
        "interval_days": 30,
        "recurring": True,
        "consumption": {"2kg": 48, "5kg": 92, "10kg": 150, "20kg": 280, "30kg": 365},
    },
    {
        "code": "DEMO-RACAO-COMP-002",
        "name": "Racao NutriCauda Prime Caes Adultos Carne 15 kg",
        "brand": "NutriCauda Demo",
        "classification": "super_premium",
        "line": "Super Premium",
        "species": "dog",
        "category": "adulto",
        "phase": "Adulto",
        "size": "Todos",
        "flavor": "Carne",
        "weight": Decimal("15"),
        "cost": Decimal("132.00"),
        "price": Decimal("229.90"),
        "stock": Decimal("18"),
        "minimum_stock": Decimal("7"),
        "interval_days": 35,
        "recurring": True,
        "consumption": {"2kg": 40, "5kg": 78, "10kg": 125, "20kg": 230, "30kg": 305},
    },
    {
        "code": "DEMO-RACAO-COMP-003",
        "name": "Racao BemPet Essencial Caes Adultos Frango 15 kg",
        "brand": "BemPet Demo",
        "classification": "standard",
        "line": "Standard",
        "species": "dog",
        "category": "adulto",
        "phase": "Adulto",
        "size": "Todos",
        "flavor": "Frango",
        "weight": Decimal("15"),
        "cost": Decimal("89.90"),
        "price": Decimal("159.90"),
        "stock": Decimal("30"),
        "minimum_stock": Decimal("10"),
        "interval_days": 28,
        "recurring": True,
        "consumption": {"2kg": 58, "5kg": 112, "10kg": 190, "20kg": 360, "30kg": 470},
    },
    {
        "code": "DEMO-RACAO-COMP-004",
        "name": "Racao VivaPata Crescer Filhotes Frango e Arroz 10 kg",
        "brand": "VivaPata Demo",
        "classification": "premium",
        "line": "Premium",
        "species": "dog",
        "category": "filhote",
        "phase": "Filhote",
        "size": "Todos",
        "flavor": "Frango e Arroz",
        "weight": Decimal("10"),
        "cost": Decimal("82.50"),
        "price": Decimal("149.90"),
        "stock": Decimal("20"),
        "minimum_stock": Decimal("6"),
        "interval_days": 30,
        "recurring": False,
        "consumption": {"2kg": 70, "5kg": 135, "10kg": 220, "20kg": 390, "30kg": 510},
    },
    {
        "code": "DEMO-RACAO-COMP-005",
        "name": "Racao NutriCauda Gatos Castrados Salmao 7 kg",
        "brand": "NutriCauda Demo",
        "classification": "super_premium",
        "line": "Super Premium",
        "species": "cat",
        "category": "adulto",
        "phase": "Adulto",
        "size": "Todos",
        "flavor": "Salmao",
        "weight": Decimal("7"),
        "cost": Decimal("76.40"),
        "price": Decimal("139.90"),
        "stock": Decimal("16"),
        "minimum_stock": Decimal("5"),
        "interval_days": 42,
        "recurring": False,
        "consumption": {"2kg": 32, "4kg": 55, "6kg": 76, "8kg": 92},
    },
    {
        "code": "DEMO-RACAO-COMP-006",
        "name": "Racao BemPet Gatos Adultos Frango 3 kg",
        "brand": "BemPet Demo",
        "classification": "especial",
        "line": "Especial",
        "species": "cat",
        "category": "adulto",
        "phase": "Adulto",
        "size": "Todos",
        "flavor": "Frango",
        "weight": Decimal("3"),
        "cost": Decimal("31.80"),
        "price": Decimal("64.90"),
        "stock": Decimal("22"),
        "minimum_stock": Decimal("7"),
        "interval_days": 35,
        "recurring": False,
        "consumption": {"2kg": 38, "4kg": 64, "6kg": 86, "8kg": 105},
    },
)

DEMO_REMINDER_SCENARIOS = (
    {"product": "DEMO-RACAO-COMP-001", "pet": "thor", "days": -2},
    {"product": "DEMO-RACAO-COMP-002", "pet": "luna", "days": 3},
    {"product": "DEMO-RACAO-COMP-003", "pet": "thor", "days": 7},
    {"product": "DEMO-RACAO-COMP-001", "pet": "luna", "days": 18},
)

DEMO_VALIDITY_SCENARIOS = (
    {
        "product": "DEMO-RACAO-COMP-004",
        "lot": "DEMO-VAL-001",
        "days": -1,
        "quantity": 3,
    },
    {"product": "DEMO-RACAO-COMP-005", "lot": "DEMO-VAL-002", "days": 5, "quantity": 4},
    {
        "product": "DEMO-RACAO-COMP-006",
        "lot": "DEMO-VAL-003",
        "days": 12,
        "quantity": 6,
    },
)
