"""fix configuracoes entrega id

Revision ID: fix_conf_entrega_001
Revises: 87694134aabd
Create Date: 2026-02-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fix_conf_entrega_001'
down_revision = '87694134aabd'
branch_labels = None
depends_on = None


def upgrade():
    # Corrige o campo id para usar IDENTITY
    # Primeiro tenta dropar identity se já existir (para casos de rerun)
    op.execute("""
        DO $$
        BEGIN
            -- Remove identity se existir
            ALTER TABLE configuracoes_entrega ALTER COLUMN id DROP IDENTITY IF EXISTS;
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END $$;
    """)
    
    # Agora adiciona IDENTITY - usando DO block para verificar se já existe
    op.execute("""
        DO $$
        BEGIN
            -- Cria sequence apenas se não existir
            IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'configuracoes_entrega_id_seq') THEN
                CREATE SEQUENCE configuracoes_entrega_id_seq;
                
                -- Pega o próximo valor da sequence baseado no max id atual
                PERFORM setval('configuracoes_entrega_id_seq', COALESCE((SELECT MAX(id) FROM configuracoes_entrega), 0) + 1, false);
                
                -- Define o default
                ALTER TABLE configuracoes_entrega 
                ALTER COLUMN id SET DEFAULT nextval('configuracoes_entrega_id_seq');
                
                -- Define como identity
                ALTER TABLE configuracoes_entrega 
                ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME configuracoes_entrega_id_seq);
            END IF;
        END $$;
    """)


def downgrade():
    op.execute("""
        ALTER TABLE configuracoes_entrega 
        ALTER COLUMN id DROP IDENTITY IF EXISTS;
    """)
