const ecommerceMvpStyles = {
  page: {
    minHeight: "100vh",
    background: "#faf7f4",
    fontFamily: "'Plus Jakarta Sans', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  topbar: {
    background: "linear-gradient(90deg,#f97316 0%,#fb923c 100%)",
    color: "#fff",
    padding: "6px 20px",
    fontSize: 11,
    fontWeight: 500,
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  topbarInner: {
    maxWidth: 1280,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  header: {
    background: "#fff",
    borderBottom: "1px solid #e7e5e4",
    padding: "12px 20px",
    position: "sticky",
    top: 32,
    zIndex: 40,
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
  },
  headerInner: {
    maxWidth: 1280,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  logo: {
    fontSize: 20,
    fontWeight: 800,
    color: "#1c1917",
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    userSelect: "none",
  },
  cityChip: {
    fontSize: 11,
    color: "#a8a29e",
    borderLeft: "1px solid #e7e5e4",
    paddingLeft: 12,
    fontWeight: 400,
  },
  headerActions: { display: "flex", gap: 10, alignItems: "center" },
  avatarBtn: {
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    borderRadius: 24,
    padding: "7px 14px",
    fontSize: 13,
    fontWeight: 600,
    color: "#ea580c",
    display: "flex",
    alignItems: "center",
    gap: 6,
    cursor: "pointer",
  },
  loginBtn: {
    background: "#fff",
    border: "1.5px solid #d1d5db",
    color: "#374151",
    borderRadius: 24,
    padding: "7px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  cartBtn: {
    background: "#f97316",
    color: "#fff",
    border: "none",
    borderRadius: 12,
    height: 42,
    padding: "0 18px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    position: "relative",
    flexShrink: 0,
    fontWeight: 700,
    fontSize: 14,
  },
  headerWishBtn: {
    background: "transparent",
    border: "none",
    color: "#78716c",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 38,
    height: 38,
    borderRadius: "50%",
    transition: "color 0.15s",
  },
  cartBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    background: "#10b981",
    color: "#fff",
    borderRadius: 20,
    minWidth: 18,
    height: 18,
    fontSize: 10,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "2px solid #fff",
    padding: "0 3px",
  },
  floatBar: {
    position: "sticky",
    top: 0,
    zIndex: 45,
    background: "#ea580c",
    color: "#fff",
    padding: "10px 24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    cursor: "pointer",
  },
  navWrap: { background: "transparent", borderBottom: "1px solid #e7e5e4" },
  navInner: { maxWidth: 1280, margin: "0 auto", display: "flex", padding: "0 20px" },
  navTab: (active) => ({
    flex: "0 0 auto",
    background: "transparent",
    border: "none",
    borderBottom: active ? "2px solid #f97316" : "2px solid transparent",
    color: active ? "#f97316" : "#78716c",
    padding: "13px 18px",
    fontWeight: active ? 700 : 500,
    fontSize: 14,
    cursor: "pointer",
    transition: "all 0.15s",
    marginBottom: -1,
  }),
  bannerWrap: { position: "relative", overflow: "hidden", height: 260, background: "#1c1917" },
  appBar: { padding: "8px 20px 0" },
  appBarInner: {
    maxWidth: 1280,
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    color: "#166534",
    background: "#dcfce7",
    border: "1px solid #bbf7d0",
    borderRadius: 10,
    padding: "10px 16px",
  },
  bannerDots: {
    position: "absolute",
    bottom: 14,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: 6,
  },
  bannerDot: (active) => ({
    width: active ? 26 : 9,
    height: 9,
    background: active ? "#fff" : "rgba(255,255,255,0.4)",
    borderRadius: 5,
    border: "none",
    cursor: "pointer",
    padding: 0,
    transition: "all 0.3s",
  }),
  alertError: {
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
    margin: "10px 0",
  },
  alertSuccess: {
    background: "#f0fdf4",
    color: "#166534",
    border: "1px solid #bbf7d0",
    borderRadius: 10,
    padding: "10px 14px",
    fontSize: 13,
    margin: "10px 0",
  },
  main: { maxWidth: 1280, margin: "0 auto", padding: "24px 20px" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 16 },
  card: (hovered) => ({
    border: "1px solid #e7e5e4",
    borderRadius: 14,
    background: "#fff",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    transition: "all 0.2s",
    boxShadow: hovered ? "0 10px 32px rgba(249,115,22,0.15)" : "0 1px 4px rgba(0,0,0,0.05)",
    transform: hovered ? "translateY(-5px)" : "none",
  }),
  cardImgWrap: {
    aspectRatio: "1/1",
    background: "#f5f5f4",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  cardBody: {
    padding: "12px 14px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    flex: 1,
  },
  cardName: {
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.4,
    color: "#1c1917",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  cardCat: { fontSize: 11, color: "#a8a29e", fontWeight: 500 },
  cardSku: { fontSize: 10, color: "#d6d3d1", letterSpacing: 0.3 },
  cardStock: (out) => ({ fontSize: 11, fontWeight: 600, color: out ? "#d97706" : "#059669" }),
  cardPrice: {
    fontSize: 19,
    fontWeight: 800,
    color: "#1c1917",
    letterSpacing: -0.5,
    marginTop: "auto",
    paddingTop: 6,
  },
  addBtn: (out) => ({
    background: out ? "#f5f5f4" : "linear-gradient(135deg,#f97316,#fb923c)",
    border: "none",
    color: out ? "#a8a29e" : "#fff",
    borderRadius: 9,
    padding: "10px 0",
    fontWeight: 700,
    fontSize: 13,
    cursor: out ? "not-allowed" : "pointer",
    width: "100%",
    marginTop: 6,
    transition: "opacity 0.15s",
    boxShadow: out ? "none" : "0 2px 8px rgba(249,115,22,0.3)",
  }),
  notifyBtn: {
    background: "#fff",
    border: "1.5px solid #f59e0b",
    color: "#b45309",
    borderRadius: 9,
    padding: "8px 0",
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
    width: "100%",
    marginTop: 6,
  },
  wishBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    background: "#fff",
    border: "none",
    borderRadius: "50%",
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 1px 4px rgba(0,0,0,0.12)",
    fontSize: 14,
  },
  unavailBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    background: "#fee2e2",
    color: "#991b1b",
    borderRadius: 6,
    padding: "3px 8px",
    fontSize: 10,
    fontWeight: 700,
  },
  sidebar: {
    background: "#fff",
    borderRadius: 16,
    border: "1px solid #e7e5e4",
    padding: 20,
    alignSelf: "start",
    position: "sticky",
    top: 80,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
    boxSizing: "border-box",
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
  },
  sidebarTitle: {
    margin: "0 0 14px",
    fontSize: 15,
    fontWeight: 700,
    color: "#1c1917",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sidebarBadge: {
    background: "#f97316",
    color: "#fff",
    borderRadius: 20,
    padding: "2px 9px",
    fontSize: 11,
    fontWeight: 700,
  },
  miniItem: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    borderBottom: "1px solid #f5f5f4",
    paddingBottom: 8,
    marginBottom: 4,
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    overflow: "hidden",
  },
  miniImg: {
    width: 42,
    height: 42,
    borderRadius: 8,
    background: "#f5f5f4",
    flexShrink: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #e7e5e4",
  },
  subtotalBox: {
    background: "#fff7ed",
    borderRadius: 10,
    padding: "10px 12px",
    marginTop: 6,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    border: "1px solid #fed7aa",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    gap: 10,
  },
  checkoutBig: {
    background: "linear-gradient(135deg,#f97316,#fb923c)",
    border: "none",
    color: "#fff",
    borderRadius: 10,
    padding: "12px 0",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    marginTop: 8,
    boxShadow: "0 4px 14px rgba(249,115,22,0.35)",
  },
  viewCartBtn: {
    background: "transparent",
    border: "2px solid #f97316",
    color: "#f97316",
    borderRadius: 10,
    padding: "10px 0",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    marginTop: 6,
  },
  cartItem: {
    border: "1px solid #e7e5e4",
    borderRadius: 14,
    padding: "14px",
    display: "flex",
    gap: 14,
    alignItems: "center",
    background: "#fff",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
    minWidth: 0,
    boxSizing: "border-box",
  },
  cartItemImg: {
    width: 80,
    height: 80,
    borderRadius: 10,
    background: "#f5f5f4",
    flexShrink: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #e7e5e4",
  },
  qtyBtn: {
    background: "#f5f5f4",
    border: "1px solid #d1d5db",
    borderRadius: 7,
    width: 32,
    height: 32,
    cursor: "pointer",
    fontSize: 16,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  removeBtn: {
    background: "transparent",
    border: "none",
    color: "#ef4444",
    cursor: "pointer",
    fontSize: 12,
    padding: "4px 8px",
  },
  cartTotalRow: {
    border: "1px solid #e7e5e4",
    borderRadius: 12,
    padding: "14px 16px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "#fff",
  },
  checkoutPage: (isMobile) => ({
    maxWidth: 1100,
    margin: "0 auto",
    padding: isMobile ? "22px 12px 0" : "28px 16px",
  }),
  checkoutGrid: (isMobile) => ({
    display: "grid",
    gridTemplateColumns: isMobile ? "minmax(0, 1fr)" : "minmax(0, 1fr) 360px",
    gap: 20,
    alignItems: "start",
  }),
  cartOrderSummaryBox: (isMobile) => ({
    background: "#fff",
    border: "1px solid #e7e5e4",
    borderRadius: 16,
    padding: 20,
    boxShadow: "0 2px 12px rgba(0,0,0,0.06)",
    position: isMobile ? "static" : "sticky",
    top: 154,
    alignSelf: "start",
  }),
  formCard: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #e7e5e4",
    padding: "20px 24px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  formLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "#78716c",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
    display: "block",
  },
  formInput: {
    width: "100%",
    padding: "10px 12px",
    border: "1.5px solid #e7e5e4",
    borderRadius: 9,
    fontSize: 14,
    background: "#faf7f4",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    fontSize: 14,
    padding: "10px 14px",
    borderRadius: 10,
    border: "1.5px solid #e7e5e4",
    background: "#faf7f4",
    fontWeight: 500,
  },
  radioLabelActive: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    fontSize: 14,
    padding: "10px 14px",
    borderRadius: 10,
    border: "1.5px solid #f97316",
    background: "#fff7ed",
    fontWeight: 600,
    color: "#ea580c",
  },
  payBtn: (active) => ({
    padding: "10px 16px",
    borderRadius: 10,
    border: active ? "2px solid #f97316" : "2px solid #e7e5e4",
    background: active ? "#fff7ed" : "#fff",
    color: active ? "#ea580c" : "#374151",
    fontWeight: active ? 700 : 500,
    cursor: "pointer",
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    gap: 6,
  }),
  resumoBox: {
    background: "#fff",
    border: "1px solid #e7e5e4",
    borderRadius: 12,
    padding: "14px 16px",
    display: "grid",
    gap: 6,
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  checkoutSummaryBox: (isMobile) => ({
    background: "#fff",
    border: "1px solid #e7e5e4",
    borderRadius: 12,
    padding: "14px 16px",
    display: "grid",
    gap: 6,
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
    position: isMobile ? "static" : "sticky",
    top: 154,
    alignSelf: "start",
    zIndex: 5,
  }),
  finalizarBtn: (disabled) => ({
    background: disabled ? "#e5e7eb" : "linear-gradient(135deg,#f97316,#fb923c)",
    border: "none",
    color: disabled ? "#9ca3af" : "#fff",
    borderRadius: 12,
    padding: "14px 0",
    fontWeight: 700,
    fontSize: 16,
    cursor: disabled ? "not-allowed" : "pointer",
    width: "100%",
    boxShadow: disabled ? "none" : "0 4px 14px rgba(249,115,22,0.35)",
  }),
  mobileCheckoutBar: {
    position: "fixed",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 60,
    background: "#fff",
    borderTop: "1px solid #e7e5e4",
    boxShadow: "0 -8px 24px rgba(28,25,23,0.12)",
    padding: "10px 12px 12px",
    display: "grid",
    gap: 8,
  },
  mobileCheckoutBarTotal: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#1c1917",
    fontSize: 13,
  },
  mobileCheckoutBarHint: {
    fontSize: 11,
    color: "#92400e",
    textAlign: "center",
  },
  mobileCheckoutSpacer: {
    height: 116,
  },
  orderCard: {
    border: "1px solid #e7e5e4",
    borderRadius: 14,
    padding: "16px 20px",
    background: "#fff",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
    display: "grid",
    gap: 10,
  },
  statusBadge: (status) => {
    const map = {
      confirmado: { bg: "#dcfce7", color: "#166534" },
      pendente: { bg: "#fef9c3", color: "#854d0e" },
      cancelado: { bg: "#fee2e2", color: "#991b1b" },
    };
    const s = map[String(status).toLowerCase()] || { bg: "#f5f5f4", color: "#555" };
    return {
      background: s.bg,
      color: s.color,
      borderRadius: 20,
      padding: "3px 10px",
      fontSize: 11,
      fontWeight: 700,
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
    };
  },
  rewardBox: {
    background: "#fff7ed",
    border: "2px solid #f97316",
    borderRadius: 10,
    padding: 12,
    textAlign: "center",
  },
  accountCard: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #e7e5e4",
    padding: "20px 24px",
    boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
  },
  saveBtn: {
    background: "linear-gradient(135deg,#f97316,#fb923c)",
    border: "none",
    color: "#fff",
    borderRadius: 10,
    fontWeight: 700,
    padding: "11px 24px",
    cursor: "pointer",
    fontSize: 14,
  },
  footer: { background: "#1c1917", color: "#a8a29e", padding: "32px 20px", marginTop: 40 },
};

export default ecommerceMvpStyles;
