"""Fachada de compatibilidade da listagem de NF-e/NFC-e."""

from app.nfe.listagem_base import (
    _FINALIDADE_MAP,
    _INDICADOR_PRESENCA_MAP,
    _LOJA_ID_CANAL_MAP,
    _NFE_SYNC_CACHE_TTL_SECONDS,
    _NFE_SYNC_DEFAULT_LOOKBACK_DAYS,
    _NFE_SYNC_SAFETY_LOOKBACK_DAYS,
    _REGIME_TRIBUTARIO_MAP,
    _STATUS_EMITIDA_DANFE,
    _STATUS_MAP,
    _XML_NS,
    _calcular_total_componentes_nota,
    _canal_label,
    _canal_slug,
    _coerce_float,
    _coerce_int,
    _detalhe_nota_valido,
    _dict,
    _digitos,
    _extrair_campo_texto,
    _extrair_valor_nota,
    _formatar_data_iso,
    _formatar_data_param_bling,
    _formatar_endereco,
    _inferir_canal_por_loja_id,
    _inferir_canal_por_numero,
    _label_codigo,
    _list,
    _nota_autorizada_bling,
    _nota_cancelada_bling,
    _parse_data_referencia,
    _planejar_sincronizacao_bling_nfes,
    _primeiro_float,
    _primeiro_preenchido,
    _separar_data_hora,
    _situacao_num,
    _somar_parcelas_nota,
    _sort_key_nota_por_numero_desc,
    _status_local_ultima_nf,
    _status_nota_bling,
    _status_nota_por_codigo,
    _status_nota_por_texto,
    _texto,
    _texto_generico_baixo_valor,
    _texto_relacionado,
    _texto_situacao,
    _tipo_nota_label,
    _tipo_pessoa_label,
    _venda_usa_nfce,
)
from app.nfe.listagem_cache import (
    _NFE_DETAIL_CACHE_SECONDS,
    _NFE_LIST_CACHE_SECONDS,
    _cache_key_detalhe_nfe,
    _cache_key_listar_nfes,
    _nfe_detail_cache,
    _nfe_list_cache,
    _obter_detalhe_nfe_cache,
    _salvar_detalhe_nfe_cache,
)
from app.nfe.listagem_detalhes import (
    _buscar_venda_por_nfe_bling_id,
    _consultar_detalhe_cache_persistente,
    _consultar_detalhe_nota_bling,
    _consultar_detalhe_remoto_bling,
    _modelos_tentativa_detalhe,
    _montar_detalhe_venda_local,
    _persistir_detalhe_remoto_bling,
    obter_detalhe_nota_cache,
)
from app.nfe.listagem_normalizacao import (
    _normalizar_detalhe_nota_bling,
    _normalizar_item_nota,
    _normalizar_nota_bling,
    _normalizar_nota_venda_local,
    _normalizar_parcela,
    _normalizar_resumo_canal,
)
from app.nfe.listagem_pedidos import (
    _adicionar_notas_de_pedidos_integrados,
    _enriquecer_notas_com_pedidos_integrados,
    _extrair_total_pedido_integrado,
    _identificadores_pedido_integrado,
    _normalizar_nota_pedido_integrado,
    _resumo_pedido_integrado,
)
from app.nfe.listagem_sync import (
    _aplicar_cliente_detalhe_em_nota,
    _aplicar_cliente_venda_em_nota,
    _aplicar_detalhe_bling_em_nota,
    _aplicar_resumo_canal_em_nota,
    _aplicar_venda_em_nota,
    _buscar_detalhe_para_enriquecimento,
    _deduplicar_notas_bling,
    _enriquecer_notas_com_detalhes_bling,
    _enriquecer_notas_com_vendas,
    _erro_rate_limit_bling,
    _ids_bling_das_notas,
    _listar_notas_bling_por_modelo,
    _necessidades_detalhe_nota,
    _persistir_enriquecimento_detalhe,
    _sincronizar_cache_nfes_com_bling,
    _sincronizar_fontes_locais_nfe_em_cache,
    _sincronizar_pedidos_integrados_em_cache,
    _sincronizar_vendas_em_cache,
    _vendas_por_bling_id,
    upsert_nota_cache,
)
from app.nfe.listagem_xml import (
    _consultar_campos_fiscais_no_xml,
    _enriquecer_detalhe_com_xml_link,
    _extrair_campos_fiscais_do_xml,
)

__all__ = [name for name in globals() if not name.startswith("__")]
