import PedidoCompraFormulario from "./PedidoCompraFormulario";
import PedidosCompraFiltros from "./PedidosCompraFiltros";
import PedidosCompraModalsLayer from "./PedidosCompraModalsLayer";
import PedidosCompraTabela from "./PedidosCompraTabela";
import PedidosCompraTabs from "./PedidosCompraTabs";

export default function PedidosCompraView({ controller }) {
  const {
    ITEM_FORM_INICIAL,
    abaAtiva,
    adicionarItem,
    adicionarSugestoesAoPedido,
    alterarPaginaPedidos,
    alterarPedidosPorPagina,
    alternarFornecedorNoGrupoForm,
    alternarMarcaSelecionada,
    apenasCriticos,
    aplicarFiltrosPedidos,
    abrirConfronto,
    abrirEdicao,
    abrirFluxoSugestaoInteligente,
    abrirNovoGrupoFornecedor,
    abrirRecebimento,
    atualizarColunasDocumento,
    atualizarFiltroPedidos,
    atualizarItemPedido,
    atualizarQuantidadeSugerida,
    atualizarQuantidadePorEmbalagemSugestao,
    atualizarUnidadeCompraSugestao,
    buscarSugestoes,
    cabecalhoTabelaSugestaoRef,
    calcularTotal,
    calcularValorTotalSugestao,
    cancelarPedido,
    carregarDados,
    classeCabecalhoTabelaSugestao,
    classeTabelaSugestao,
    colunasDocumentoPedido,
    confirmarEnvioPedido,
    confirmarExportacaoPedido,
    confirmarPedido,
    consumoFoiAjustado,
    contextoRascunhoSugestao,
    copiarSkuSugestao,
    corpoTabelaSugestaoRef,
    dadosEnvio,
    decidirAcaoRascunhoSugestao,
    desmarcarVisiveis,
    diasCobertura,
    editarGrupoFornecedor,
    editarPedido,
    emailEnvioDisponivel,
    enviarPedido,
    estrategiaMesclaItens,
    excluirGrupoFornecedor,
    exportandoArquivo,
    exportarExcel,
    exportarPDF,
    fecharFormularioEListar,
    fecharModalExportacao,
    fecharModalGruposFornecedores,
    fecharModalRascunho,
    fecharModalSugestao,
    filtroMarcasRef,
    filtroSugestao,
    filtrosPedidos,
    filtrosPedidosAtivos,
    formData,
    fornecedorTexto,
    fornecedores,
    fornecedoresOrdenados,
    formatarQuantidadeCompraSugestao,
    formatarQuantidadeCurta,
    grupoFornecedorAtual,
    grupoFornecedorForm,
    gruposFornecedores,
    handleSubmit,
    incluirAlerta,
    incluirGrupoFornecedor,
    iniciarNovoGrupoFornecedor,
    itemForm,
    limparEstadosSugestao,
    limparFiltrosPedidos,
    loading,
    loadingListaPedidos,
    loadingPrepararSugestao,
    loadingSugestao,
    marcasFornecedor,
    marcasSelecionadas,
    marcarComoEnviadoManualmente,
    marcarQuantidadePorEmbalagemDesconhecida,
    modoAplicacaoSugestao,
    modoEdicao,
    montarTooltipGiroSugestao,
    montarTooltipQuantidadeCompraSugestao,
    mostrarConfronto,
    mostrarFiltroMarcas,
    mostrarForm,
    mostrarModalEnvio,
    mostrarModalExportacao,
    mostrarModalGruposFornecedores,
    mostrarModalRascunhoSugestao,
    mostrarRecebimento,
    mostrarSoPreenchidos,
    mostrarSugestao,
    mostrarSugestoesProduto,
    numeroSeguro,
    obterEmbalagemSugestao,
    obterFornecedorPorId,
    obterGrupoDoFornecedor,
    obterQuantidadeInteira,
    obterQuantidadeTotalUnidadesSugestao,
    obterSkuItemPedido,
    obterVendaJanelaSugestao,
    pedidoConfronto,
    pedidoParaEnviar,
    pedidoParaExportar,
    pedidoSelecionado,
    paginaPedidos,
    paginacaoPedidos,
    pedidos,
    pedidosPorPagina,
    periodoSugestao,
    produtoTexto,
    produtos,
    produtosFiltrados,
    porProdutos,
    produtosSelecionados,
    receberPedido,
    registrarFornecedorCriado,
    removerItem,
    renderColGroupSugestao,
    resumoMarcasSelecionadas,
    reverterStatus,
    salvarGrupoFornecedor,
    salvandoGrupoFornecedor,
    selecionarVisaoPedidos,
    selecionarAbaCompra,
    selecionarFornecedor,
    selecionarGrupoFornecedor,
    selecionarPreenchidosVisiveis,
    selecionarProduto,
    selecionarTodosCriticos,
    selecionadosComQuantidade,
    setApenasCriticos,
    setDadosEnvio,
    setDiasCobertura,
    setEstrategiaMesclaItens,
    setFiltroSugestao,
    setFormData,
    setFornecedorTexto,
    setGrupoFornecedorForm,
    setIncluirAlerta,
    setIncluirGrupoFornecedor,
    setItemForm,
    setMarcasSelecionadas,
    setMostrarConfronto,
    setMostrarFiltroMarcas,
    setMostrarModalEnvio,
    setMostrarRecebimento,
    setMostrarSoPreenchidos,
    setMostrarSugestoesProduto,
    setPeriodoSugestao,
    setPedidoConfronto,
    setPedidoSelecionado,
    setProdutoEditandoQuantidade,
    setProdutoTexto,
    setProdutos,
    setProdutosSelecionados,
    sugestoes,
    sugestoesFiltradas,
    toggleSelecionarProduto,
    verDetalhes,
  } = controller;

  return (
    <div className="p-6">
      <div className="mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Pedidos de Compra</h1>
          <p className="text-gray-600">
            Monte novos pedidos e acompanhe os pedidos realizados em áreas separadas
          </p>
        </div>
      </div>

      <PedidosCompraTabs
        abaAtiva={abaAtiva}
        itensNoPedido={formData.itens.length}
        onChange={selecionarAbaCompra}
        totalPedidos={paginacaoPedidos.total}
      />

      {abaAtiva !== "pedidos" ? (
        <PedidoCompraFormulario
          mostrarForm={mostrarForm}
          modoEdicao={modoEdicao}
          fecharFormularioPedido={fecharFormularioEListar}
          editarPedido={editarPedido}
          handleSubmit={handleSubmit}
          fornecedorTexto={fornecedorTexto}
          setFornecedorTexto={setFornecedorTexto}
          fornecedores={fornecedores}
          gruposFornecedores={gruposFornecedores}
          registrarFornecedorCriado={registrarFornecedorCriado}
          selecionarFornecedor={selecionarFornecedor}
          selecionarGrupoFornecedor={selecionarGrupoFornecedor}
          setFormData={setFormData}
          setProdutos={setProdutos}
          setIncluirGrupoFornecedor={setIncluirGrupoFornecedor}
          setProdutoTexto={setProdutoTexto}
          setMostrarSugestoesProduto={setMostrarSugestoesProduto}
          setItemForm={setItemForm}
          itemFormInicial={ITEM_FORM_INICIAL}
          limparEstadosSugestao={limparEstadosSugestao}
          obterGrupoDoFornecedor={obterGrupoDoFornecedor}
          abrirNovoGrupoFornecedor={abrirNovoGrupoFornecedor}
          formData={formData}
          grupoFornecedorAtual={grupoFornecedorAtual}
          incluirGrupoFornecedor={incluirGrupoFornecedor}
          abrirFluxoSugestaoInteligente={abrirFluxoSugestaoInteligente}
          loadingPrepararSugestao={loadingPrepararSugestao}
          produtoTexto={produtoTexto}
          produtos={produtos}
          selecionarProduto={selecionarProduto}
          produtosFiltrados={produtosFiltrados}
          mostrarSugestoesProduto={mostrarSugestoesProduto}
          itemForm={itemForm}
          adicionarItem={adicionarItem}
          obterSkuItemPedido={obterSkuItemPedido}
          atualizarItemPedido={atualizarItemPedido}
          numeroSeguro={numeroSeguro}
          removerItem={removerItem}
          calcularTotal={calcularTotal}
          loading={loading}
          porProdutos={porProdutos}
        />
      ) : null}

      {abaAtiva === "pedidos" ? (
        <>
          <PedidosCompraFiltros
            filtrosPedidos={filtrosPedidos}
            filtrosPedidosAtivos={filtrosPedidosAtivos}
            fornecedoresOrdenados={fornecedoresOrdenados}
            loadingListaPedidos={loadingListaPedidos}
            onAplicar={aplicarFiltrosPedidos}
            onAtualizarFiltro={atualizarFiltroPedidos}
            onLimpar={limparFiltrosPedidos}
            onSelecionarVisao={selecionarVisaoPedidos}
            pedidosCount={paginacaoPedidos.total}
          />

          <PedidosCompraTabela
            abrirConfronto={abrirConfronto}
            abrirEdicao={abrirEdicao}
            abrirRecebimento={abrirRecebimento}
            cancelarPedido={cancelarPedido}
            confirmarPedido={confirmarPedido}
            enviarPedido={enviarPedido}
            exportarExcel={exportarExcel}
            exportarPDF={exportarPDF}
            loading={loadingListaPedidos}
            obterFornecedorPorId={obterFornecedorPorId}
            onItemsPerPageChange={alterarPedidosPorPagina}
            onPageChange={alterarPaginaPedidos}
            paginaAtual={paginaPedidos}
            paginasTotal={paginacaoPedidos.pages}
            pedidos={pedidos}
            pedidosPorPagina={pedidosPorPagina}
            reverterStatus={reverterStatus}
            totalPedidos={paginacaoPedidos.total}
            verDetalhes={verDetalhes}
          />
        </>
      ) : null}
      <PedidosCompraModalsLayer
        mostrarRecebimento={mostrarRecebimento}
        pedidoSelecionado={pedidoSelecionado}
        setMostrarRecebimento={setMostrarRecebimento}
        setPedidoSelecionado={setPedidoSelecionado}
        receberPedido={receberPedido}
        mostrarConfronto={mostrarConfronto}
        pedidoConfronto={pedidoConfronto}
        setMostrarConfronto={setMostrarConfronto}
        setPedidoConfronto={setPedidoConfronto}
        carregarDados={carregarDados}
        mostrarModalEnvio={mostrarModalEnvio}
        pedidoParaEnviar={pedidoParaEnviar}
        pedidoSemFornecedor={Boolean(
          pedidoParaEnviar &&
          !pedidos.find((pedido) => Number(pedido.id) === Number(pedidoParaEnviar))?.fornecedor_id,
        )}
        setMostrarModalEnvio={setMostrarModalEnvio}
        confirmarEnvioPedido={confirmarEnvioPedido}
        marcarComoEnviadoManualmente={marcarComoEnviadoManualmente}
        emailEnvioDisponivel={emailEnvioDisponivel}
        dadosEnvio={dadosEnvio}
        setDadosEnvio={setDadosEnvio}
        colunasDocumentoPedido={colunasDocumentoPedido}
        atualizarColunasDocumento={atualizarColunasDocumento}
        mostrarModalExportacao={mostrarModalExportacao}
        pedidoParaExportar={pedidoParaExportar}
        fecharModalExportacao={fecharModalExportacao}
        confirmarExportacaoPedido={confirmarExportacaoPedido}
        exportandoArquivo={exportandoArquivo}
        mostrarModalRascunhoSugestao={mostrarModalRascunhoSugestao}
        contextoRascunhoSugestao={contextoRascunhoSugestao}
        estrategiaMesclaItens={estrategiaMesclaItens}
        setEstrategiaMesclaItens={setEstrategiaMesclaItens}
        fecharModalRascunho={fecharModalRascunho}
        decidirAcaoRascunhoSugestao={decidirAcaoRascunhoSugestao}
        mostrarModalGruposFornecedores={mostrarModalGruposFornecedores}
        gruposFornecedores={gruposFornecedores}
        fornecedores={fornecedores}
        grupoFornecedorForm={grupoFornecedorForm}
        setGrupoFornecedorForm={setGrupoFornecedorForm}
        salvandoGrupoFornecedor={salvandoGrupoFornecedor}
        fecharModalGruposFornecedores={fecharModalGruposFornecedores}
        salvarGrupoFornecedor={salvarGrupoFornecedor}
        iniciarNovoGrupoFornecedor={iniciarNovoGrupoFornecedor}
        editarGrupoFornecedor={editarGrupoFornecedor}
        excluirGrupoFornecedor={excluirGrupoFornecedor}
        registrarFornecedorCriado={registrarFornecedorCriado}
        alternarFornecedorNoGrupoForm={alternarFornecedorNoGrupoForm}
        mostrarSugestao={mostrarSugestao}
        fecharModalSugestao={fecharModalSugestao}
        filtroSugestao={filtroSugestao}
        setFiltroSugestao={setFiltroSugestao}
        filtroMarcasRef={filtroMarcasRef}
        setMostrarFiltroMarcas={setMostrarFiltroMarcas}
        resumoMarcasSelecionadas={resumoMarcasSelecionadas}
        mostrarFiltroMarcas={mostrarFiltroMarcas}
        setMarcasSelecionadas={setMarcasSelecionadas}
        marcasSelecionadas={marcasSelecionadas}
        marcasFornecedor={marcasFornecedor}
        alternarMarcaSelecionada={alternarMarcaSelecionada}
        periodoSugestao={periodoSugestao}
        setPeriodoSugestao={setPeriodoSugestao}
        diasCobertura={diasCobertura}
        setDiasCobertura={setDiasCobertura}
        buscarSugestoes={buscarSugestoes}
        loadingSugestao={loadingSugestao}
        apenasCriticos={apenasCriticos}
        setApenasCriticos={setApenasCriticos}
        incluirAlerta={incluirAlerta}
        setIncluirAlerta={setIncluirAlerta}
        grupoFornecedorAtual={grupoFornecedorAtual}
        incluirGrupoFornecedor={incluirGrupoFornecedor}
        setIncluirGrupoFornecedor={setIncluirGrupoFornecedor}
        limparEstadosSugestao={limparEstadosSugestao}
        sugestoes={sugestoes}
        produtosSelecionados={produtosSelecionados}
        obterQuantidadeInteira={obterQuantidadeInteira}
        obterEmbalagemSugestao={obterEmbalagemSugestao}
        atualizarUnidadeCompraSugestao={atualizarUnidadeCompraSugestao}
        atualizarQuantidadePorEmbalagemSugestao={atualizarQuantidadePorEmbalagemSugestao}
        marcarQuantidadePorEmbalagemDesconhecida={marcarQuantidadePorEmbalagemDesconhecida}
        formatarQuantidadeCompraSugestao={formatarQuantidadeCompraSugestao}
        montarTooltipQuantidadeCompraSugestao={montarTooltipQuantidadeCompraSugestao}
        obterQuantidadeTotalUnidadesSugestao={obterQuantidadeTotalUnidadesSugestao}
        calcularValorTotalSugestao={calcularValorTotalSugestao}
        modoAplicacaoSugestao={modoAplicacaoSugestao}
        mostrarSoPreenchidos={mostrarSoPreenchidos}
        setMostrarSoPreenchidos={setMostrarSoPreenchidos}
        selecionarTodosCriticos={selecionarTodosCriticos}
        selecionarPreenchidosVisiveis={selecionarPreenchidosVisiveis}
        desmarcarVisiveis={desmarcarVisiveis}
        selecionadosComQuantidade={selecionadosComQuantidade}
        sugestoesFiltradas={sugestoesFiltradas}
        setProdutosSelecionados={setProdutosSelecionados}
        classeTabelaSugestao={classeTabelaSugestao}
        renderColGroupSugestao={renderColGroupSugestao}
        classeCabecalhoTabelaSugestao={classeCabecalhoTabelaSugestao}
        cabecalhoTabelaSugestaoRef={cabecalhoTabelaSugestaoRef}
        corpoTabelaSugestaoRef={corpoTabelaSugestaoRef}
        toggleSelecionarProduto={toggleSelecionarProduto}
        copiarSkuSugestao={copiarSkuSugestao}
        montarTooltipGiroSugestao={montarTooltipGiroSugestao}
        formatarQuantidadeCurta={formatarQuantidadeCurta}
        obterVendaJanelaSugestao={obterVendaJanelaSugestao}
        consumoFoiAjustado={consumoFoiAjustado}
        atualizarQuantidadeSugerida={atualizarQuantidadeSugerida}
        setProdutoEditandoQuantidade={setProdutoEditandoQuantidade}
        adicionarSugestoesAoPedido={adicionarSugestoesAoPedido}
      />
    </div>
  );
}
