import PedidoCompraFormulario from "./PedidoCompraFormulario";
import PedidosCompraFiltros from "./PedidosCompraFiltros";
import PedidosCompraModalsLayer from "./PedidosCompraModalsLayer";
import PedidosCompraTabela from "./PedidosCompraTabela";
import { Plus, X } from "lucide-react";

export default function PedidosCompraView({ controller }) {
  const {
    ITEM_FORM_INICIAL,
    adicionarItem,
    adicionarSugestoesAoPedido,
    alternarFornecedorNoGrupoForm,
    alternarMarcaSelecionada,
    apenasCriticos,
    aplicarFiltrosPedidos,
    abrirConfronto,
    abrirEdicao,
    abrirFluxoSugestaoInteligente,
    abrirNovoFormulario,
    abrirNovoGrupoFornecedor,
    abrirRecebimento,
    atualizarColunasDocumento,
    atualizarFiltroPedidos,
    atualizarItemPedido,
    atualizarQuantidadeSugerida,
    atualizarQuantidadePorEmbalagemSugestao,
    atualizarUnidadeCompraSugestao,
    buscarSugestoes,
    cabecalhoTabelaSugestaoRef,
    calcularTotal,
    calcularValorTotalSugestao,
    cancelarPedido,
    carregarDados,
    classeCabecalhoTabelaSugestao,
    classeTabelaSugestao,
    colunasDocumentoPedido,
    confirmarEnvioPedido,
    confirmarExportacaoPedido,
    confirmarPedido,
    consumoFoiAjustado,
    contextoRascunhoSugestao,
    copiarSkuSugestao,
    corpoTabelaSugestaoRef,
    dadosEnvio,
    decidirAcaoRascunhoSugestao,
    desmarcarVisiveis,
    diasCobertura,
    editarGrupoFornecedor,
    editarPedido,
    emailEnvioDisponivel,
    enviarPedido,
    estrategiaMesclaItens,
    excluirGrupoFornecedor,
    exportandoArquivo,
    exportarExcel,
    exportarPDF,
    fecharFormularioPedido,
    fecharModalExportacao,
    fecharModalGruposFornecedores,
    fecharModalRascunho,
    fecharModalSugestao,
    filtroMarcasRef,
    filtroSugestao,
    filtrosPedidos,
    filtrosPedidosAtivos,
    formData,
    fornecedorTexto,
    fornecedores,
    fornecedoresOrdenados,
    formatarQuantidadeCompraSugestao,
    formatarQuantidadeCurta,
    grupoFornecedorAtual,
    grupoFornecedorForm,
    gruposFornecedores,
    handleSubmit,
    incluirAlerta,
    incluirGrupoFornecedor,
    iniciarNovoGrupoFornecedor,
    itemForm,
    limparEstadosSugestao,
    limparFiltrosPedidos,
    loading,
    loadingListaPedidos,
    loadingPrepararSugestao,
    loadingSugestao,
    marcasFornecedor,
    marcasSelecionadas,
    marcarComoEnviadoManualmente,
    marcarQuantidadePorEmbalagemDesconhecida,
    modoAplicacaoSugestao,
    modoEdicao,
    montarTooltipGiroSugestao,
    montarTooltipQuantidadeCompraSugestao,
    mostrarConfronto,
    mostrarFiltroMarcas,
    mostrarForm,
    mostrarModalEnvio,
    mostrarModalExportacao,
    mostrarModalGruposFornecedores,
    mostrarModalRascunhoSugestao,
    mostrarRecebimento,
    mostrarSoPreenchidos,
    mostrarSugestao,
    mostrarSugestoesProduto,
    numeroSeguro,
    obterEmbalagemSugestao,
    obterFornecedorPorId,
    obterGrupoDoFornecedor,
    obterQuantidadeInteira,
    obterQuantidadeTotalUnidadesSugestao,
    obterSkuItemPedido,
    obterVendaJanelaSugestao,
    pedidoConfronto,
    pedidoParaEnviar,
    pedidoParaExportar,
    pedidoSelecionado,
    pedidos,
    periodoSugestao,
    produtoTexto,
    produtos,
    produtosFiltrados,
    produtosSelecionados,
    receberPedido,
    registrarFornecedorCriado,
    removerItem,
    renderColGroupSugestao,
    resumoMarcasSelecionadas,
    reverterStatus,
    salvarGrupoFornecedor,
    salvandoGrupoFornecedor,
    selecionarFiltroStatus,
    selecionarFornecedor,
    selecionarGrupoFornecedor,
    selecionarPreenchidosVisiveis,
    selecionarProduto,
    selecionarTodosCriticos,
    selecionadosComQuantidade,
    setApenasCriticos,
    setDadosEnvio,
    setDiasCobertura,
    setEstrategiaMesclaItens,
    setFiltroSugestao,
    setFormData,
    setFornecedorTexto,
    setGrupoFornecedorForm,
    setIncluirAlerta,
    setIncluirGrupoFornecedor,
    setItemForm,
    setMarcasSelecionadas,
    setMostrarConfronto,
    setMostrarFiltroMarcas,
    setMostrarModalEnvio,
    setMostrarRecebimento,
    setMostrarSoPreenchidos,
    setMostrarSugestoesProduto,
    setPeriodoSugestao,
    setPedidoConfronto,
    setPedidoSelecionado,
    setProdutoEditandoQuantidade,
    setProdutoTexto,
    setProdutos,
    setProdutosSelecionados,
    sugestoes,
    sugestoesFiltradas,
    toggleSelecionarProduto,
    verDetalhes,
  } = controller;

  return (
    <div className="p-6">
      <div className="mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Pedidos de Compra</h1>
          <p className="text-gray-600">Gerencie seus pedidos aos fornecedores</p>
        </div>
        <button
          onClick={() => {
            if (mostrarForm) {
              fecharFormularioPedido();
              return;
            }

            abrirNovoFormulario();
          }}
          className="inline-flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-5 py-2.5 font-semibold text-blue-700 transition-colors hover:bg-blue-100"
        >
          {mostrarForm ? (
            <>
              <X className="h-4 w-4" />
              Cancelar
            </>
          ) : (
            <>
              <Plus className="h-4 w-4" />
              Novo Pedido
            </>
          )}
        </button>
      </div>

      <PedidoCompraFormulario
        mostrarForm={mostrarForm}
        modoEdicao={modoEdicao}
        fecharFormularioPedido={fecharFormularioPedido}
        editarPedido={editarPedido}
        handleSubmit={handleSubmit}
        fornecedorTexto={fornecedorTexto}
        setFornecedorTexto={setFornecedorTexto}
        fornecedores={fornecedores}
        gruposFornecedores={gruposFornecedores}
        selecionarFornecedor={selecionarFornecedor}
        selecionarGrupoFornecedor={selecionarGrupoFornecedor}
        setFormData={setFormData}
        setProdutos={setProdutos}
        setIncluirGrupoFornecedor={setIncluirGrupoFornecedor}
        setProdutoTexto={setProdutoTexto}
        setMostrarSugestoesProduto={setMostrarSugestoesProduto}
        setItemForm={setItemForm}
        itemFormInicial={ITEM_FORM_INICIAL}
        limparEstadosSugestao={limparEstadosSugestao}
        obterGrupoDoFornecedor={obterGrupoDoFornecedor}
        abrirNovoGrupoFornecedor={abrirNovoGrupoFornecedor}
        formData={formData}
        grupoFornecedorAtual={grupoFornecedorAtual}
        incluirGrupoFornecedor={incluirGrupoFornecedor}
        abrirFluxoSugestaoInteligente={abrirFluxoSugestaoInteligente}
        loadingPrepararSugestao={loadingPrepararSugestao}
        produtoTexto={produtoTexto}
        produtos={produtos}
        selecionarProduto={selecionarProduto}
        produtosFiltrados={produtosFiltrados}
        mostrarSugestoesProduto={mostrarSugestoesProduto}
        itemForm={itemForm}
        adicionarItem={adicionarItem}
        obterSkuItemPedido={obterSkuItemPedido}
        atualizarItemPedido={atualizarItemPedido}
        numeroSeguro={numeroSeguro}
        removerItem={removerItem}
        calcularTotal={calcularTotal}
        loading={loading}
      />

      <PedidosCompraFiltros
        filtrosPedidos={filtrosPedidos}
        filtrosPedidosAtivos={filtrosPedidosAtivos}
        fornecedoresOrdenados={fornecedoresOrdenados}
        loadingListaPedidos={loadingListaPedidos}
        onAplicar={aplicarFiltrosPedidos}
        onAtualizarFiltro={atualizarFiltroPedidos}
        onLimpar={limparFiltrosPedidos}
        onSelecionarStatus={selecionarFiltroStatus}
        pedidosCount={pedidos.length}
      />

      {/* Lista de Pedidos */}
      <PedidosCompraTabela
        abrirConfronto={abrirConfronto}
        abrirEdicao={abrirEdicao}
        abrirRecebimento={abrirRecebimento}
        cancelarPedido={cancelarPedido}
        confirmarPedido={confirmarPedido}
        enviarPedido={enviarPedido}
        exportarExcel={exportarExcel}
        exportarPDF={exportarPDF}
        obterFornecedorPorId={obterFornecedorPorId}
        pedidos={pedidos}
        reverterStatus={reverterStatus}
        verDetalhes={verDetalhes}
      />
      <PedidosCompraModalsLayer
        mostrarRecebimento={mostrarRecebimento}
        pedidoSelecionado={pedidoSelecionado}
        setMostrarRecebimento={setMostrarRecebimento}
        setPedidoSelecionado={setPedidoSelecionado}
        receberPedido={receberPedido}
        mostrarConfronto={mostrarConfronto}
        pedidoConfronto={pedidoConfronto}
        setMostrarConfronto={setMostrarConfronto}
        setPedidoConfronto={setPedidoConfronto}
        carregarDados={carregarDados}
        mostrarModalEnvio={mostrarModalEnvio}
        pedidoParaEnviar={pedidoParaEnviar}
        setMostrarModalEnvio={setMostrarModalEnvio}
        confirmarEnvioPedido={confirmarEnvioPedido}
        marcarComoEnviadoManualmente={marcarComoEnviadoManualmente}
        emailEnvioDisponivel={emailEnvioDisponivel}
        dadosEnvio={dadosEnvio}
        setDadosEnvio={setDadosEnvio}
        colunasDocumentoPedido={colunasDocumentoPedido}
        atualizarColunasDocumento={atualizarColunasDocumento}
        mostrarModalExportacao={mostrarModalExportacao}
        pedidoParaExportar={pedidoParaExportar}
        fecharModalExportacao={fecharModalExportacao}
        confirmarExportacaoPedido={confirmarExportacaoPedido}
        exportandoArquivo={exportandoArquivo}
        mostrarModalRascunhoSugestao={mostrarModalRascunhoSugestao}
        contextoRascunhoSugestao={contextoRascunhoSugestao}
        estrategiaMesclaItens={estrategiaMesclaItens}
        setEstrategiaMesclaItens={setEstrategiaMesclaItens}
        fecharModalRascunho={fecharModalRascunho}
        decidirAcaoRascunhoSugestao={decidirAcaoRascunhoSugestao}
        mostrarModalGruposFornecedores={mostrarModalGruposFornecedores}
        gruposFornecedores={gruposFornecedores}
        fornecedores={fornecedores}
        grupoFornecedorForm={grupoFornecedorForm}
        setGrupoFornecedorForm={setGrupoFornecedorForm}
        salvandoGrupoFornecedor={salvandoGrupoFornecedor}
        fecharModalGruposFornecedores={fecharModalGruposFornecedores}
        salvarGrupoFornecedor={salvarGrupoFornecedor}
        iniciarNovoGrupoFornecedor={iniciarNovoGrupoFornecedor}
        editarGrupoFornecedor={editarGrupoFornecedor}
        excluirGrupoFornecedor={excluirGrupoFornecedor}
        registrarFornecedorCriado={registrarFornecedorCriado}
        alternarFornecedorNoGrupoForm={alternarFornecedorNoGrupoForm}
        mostrarSugestao={mostrarSugestao}
        fecharModalSugestao={fecharModalSugestao}
        filtroSugestao={filtroSugestao}
        setFiltroSugestao={setFiltroSugestao}
        filtroMarcasRef={filtroMarcasRef}
        setMostrarFiltroMarcas={setMostrarFiltroMarcas}
        resumoMarcasSelecionadas={resumoMarcasSelecionadas}
        mostrarFiltroMarcas={mostrarFiltroMarcas}
        setMarcasSelecionadas={setMarcasSelecionadas}
        marcasSelecionadas={marcasSelecionadas}
        marcasFornecedor={marcasFornecedor}
        alternarMarcaSelecionada={alternarMarcaSelecionada}
        periodoSugestao={periodoSugestao}
        setPeriodoSugestao={setPeriodoSugestao}
        diasCobertura={diasCobertura}
        setDiasCobertura={setDiasCobertura}
        buscarSugestoes={buscarSugestoes}
        loadingSugestao={loadingSugestao}
        apenasCriticos={apenasCriticos}
        setApenasCriticos={setApenasCriticos}
        incluirAlerta={incluirAlerta}
        setIncluirAlerta={setIncluirAlerta}
        grupoFornecedorAtual={grupoFornecedorAtual}
        incluirGrupoFornecedor={incluirGrupoFornecedor}
        setIncluirGrupoFornecedor={setIncluirGrupoFornecedor}
        limparEstadosSugestao={limparEstadosSugestao}
        sugestoes={sugestoes}
        produtosSelecionados={produtosSelecionados}
        obterQuantidadeInteira={obterQuantidadeInteira}
        obterEmbalagemSugestao={obterEmbalagemSugestao}
        atualizarUnidadeCompraSugestao={atualizarUnidadeCompraSugestao}
        atualizarQuantidadePorEmbalagemSugestao={atualizarQuantidadePorEmbalagemSugestao}
        marcarQuantidadePorEmbalagemDesconhecida={marcarQuantidadePorEmbalagemDesconhecida}
        formatarQuantidadeCompraSugestao={formatarQuantidadeCompraSugestao}
        montarTooltipQuantidadeCompraSugestao={montarTooltipQuantidadeCompraSugestao}
        obterQuantidadeTotalUnidadesSugestao={obterQuantidadeTotalUnidadesSugestao}
        calcularValorTotalSugestao={calcularValorTotalSugestao}
        modoAplicacaoSugestao={modoAplicacaoSugestao}
        mostrarSoPreenchidos={mostrarSoPreenchidos}
        setMostrarSoPreenchidos={setMostrarSoPreenchidos}
        selecionarTodosCriticos={selecionarTodosCriticos}
        selecionarPreenchidosVisiveis={selecionarPreenchidosVisiveis}
        desmarcarVisiveis={desmarcarVisiveis}
        selecionadosComQuantidade={selecionadosComQuantidade}
        sugestoesFiltradas={sugestoesFiltradas}
        setProdutosSelecionados={setProdutosSelecionados}
        classeTabelaSugestao={classeTabelaSugestao}
        renderColGroupSugestao={renderColGroupSugestao}
        classeCabecalhoTabelaSugestao={classeCabecalhoTabelaSugestao}
        cabecalhoTabelaSugestaoRef={cabecalhoTabelaSugestaoRef}
        corpoTabelaSugestaoRef={corpoTabelaSugestaoRef}
        toggleSelecionarProduto={toggleSelecionarProduto}
        copiarSkuSugestao={copiarSkuSugestao}
        montarTooltipGiroSugestao={montarTooltipGiroSugestao}
        formatarQuantidadeCurta={formatarQuantidadeCurta}
        obterVendaJanelaSugestao={obterVendaJanelaSugestao}
        consumoFoiAjustado={consumoFoiAjustado}
        atualizarQuantidadeSugerida={atualizarQuantidadeSugerida}
        setProdutoEditandoQuantidade={setProdutoEditandoQuantidade}
        adicionarSugestoesAoPedido={adicionarSugestoesAoPedido}
      />
    </div>
  );
}
