import { StyleSheet } from "react-native";
import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../theme";

export const gestorStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F3F6F6" },
  content: { padding: ESPACO.md, paddingBottom: ESPACO.xxl, gap: ESPACO.md },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F6F6",
    padding: ESPACO.lg,
  },
  loadingText: { marginTop: ESPACO.sm, color: CORES.textoSecundario },
  hero: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
    overflow: "hidden",
  },
  heroEyebrow: {
    color: "#A7F3D0",
    fontSize: FONTE.pequena,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: "#fff",
    fontSize: FONTE.titulo,
    fontWeight: "900",
    marginTop: ESPACO.xs,
  },
  heroSubtitle: {
    color: "#D5EFEC",
    fontSize: FONTE.normal,
    marginTop: ESPACO.xs,
  },
  heroMeta: {
    color: "#A9D7D4",
    fontSize: FONTE.pequena,
    marginTop: ESPACO.md,
  },
  filterSection: { gap: ESPACO.sm },
  filterHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  filterTitle: { color: CORES.texto, fontSize: FONTE.media, fontWeight: "800" },
  periodText: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  chipsContent: { paddingRight: ESPACO.md, gap: ESPACO.sm },
  chip: {
    paddingHorizontal: ESPACO.md,
    paddingVertical: 10,
    borderRadius: RAIO.circulo,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.superficie,
  },
  chipActive: { backgroundColor: CORES.primario, borderColor: CORES.primario },
  chipText: {
    color: CORES.textoSecundario,
    fontSize: FONTE.normal,
    fontWeight: "700",
  },
  chipTextActive: { color: "#fff" },
  customChip: { flexDirection: "row", alignItems: "center", gap: 6 },
  errorCard: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  errorTitle: { color: "#991B1B", fontSize: FONTE.normal, fontWeight: "800" },
  errorText: { color: "#B91C1C", fontSize: FONTE.pequena, marginTop: 3 },
  retryButton: { marginTop: ESPACO.sm, alignSelf: "flex-start" },
  retryText: { color: CORES.primario, fontWeight: "800" },
  warningCard: {
    flexDirection: "row",
    gap: ESPACO.sm,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  warningText: { flex: 1, color: "#92400E", fontSize: FONTE.pequena },
  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: "#E7ECEC",
    ...SOMBRA,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: ESPACO.md,
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    flex: 1,
  },
  cardIcon: {
    width: 38,
    height: 38,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primarioClaro,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: { color: CORES.texto, fontSize: FONTE.media, fontWeight: "900" },
  cardSubtitle: {
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    marginTop: 2,
  },
  mainMetricLabel: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  mainMetricValue: {
    color: CORES.primarioEscuro,
    fontSize: 31,
    fontWeight: "900",
    marginTop: 2,
  },
  moneyGrid: { flexDirection: "row", gap: ESPACO.sm, marginTop: ESPACO.md },
  moneyCell: {
    flex: 1,
    backgroundColor: "#F8FAFA",
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
    minHeight: 72,
  },
  moneyCellLabel: {
    color: CORES.textoSecundario,
    fontSize: 11,
    fontWeight: "700",
  },
  moneyCellValue: {
    color: CORES.texto,
    fontSize: 14,
    fontWeight: "900",
    marginTop: 5,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  metricBox: {
    width: "48%",
    flexGrow: 1,
    backgroundColor: "#F8FAFA",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  metricBoxTop: { flexDirection: "row", alignItems: "center", gap: 6 },
  metricBoxLabel: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  metricBoxValue: {
    color: CORES.texto,
    fontSize: FONTE.grande,
    fontWeight: "900",
    marginTop: 5,
  },
  balanceGrid: { flexDirection: "row", gap: ESPACO.sm },
  balanceBox: { flex: 1, borderRadius: RAIO.md, padding: ESPACO.md },
  realizedBox: { backgroundColor: "#EFF6FF" },
  projectedBox: { backgroundColor: "#ECFDF5" },
  balanceLabel: {
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    fontWeight: "700",
  },
  balanceValue: {
    fontSize: FONTE.grande,
    fontWeight: "900",
    marginTop: ESPACO.xs,
  },
  positive: { color: "#047857" },
  negative: { color: "#B91C1C" },
  detailRows: {
    marginTop: ESPACO.md,
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: ESPACO.md,
    paddingVertical: ESPACO.sm,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F4",
  },
  detailLabel: {
    flex: 1,
    color: CORES.textoSecundario,
    fontSize: FONTE.normal,
  },
  detailValue: {
    color: CORES.texto,
    fontSize: FONTE.normal,
    fontWeight: "800",
    textAlign: "right",
  },
  accountsGrid: { gap: ESPACO.sm },
  accountPanel: { borderRadius: RAIO.md, borderWidth: 1, padding: ESPACO.md },
  receivablePanel: { borderColor: "#A7F3D0", backgroundColor: "#F0FDF4" },
  payablePanel: { borderColor: "#FECACA", backgroundColor: "#FFF7F7" },
  accountTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
  },
  accountTitle: {
    color: CORES.texto,
    fontSize: FONTE.normal,
    fontWeight: "900",
  },
  accountTotal: {
    color: CORES.texto,
    fontSize: FONTE.titulo,
    fontWeight: "900",
    marginTop: ESPACO.sm,
  },
  accountCaption: {
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    marginTop: 2,
  },
  accountStats: { flexDirection: "row", gap: ESPACO.sm, marginTop: ESPACO.md },
  accountStat: { flex: 1 },
  accountStatLabel: { color: CORES.textoSecundario, fontSize: 11 },
  accountStatValue: {
    color: CORES.texto,
    fontSize: FONTE.normal,
    fontWeight: "800",
    marginTop: 3,
  },
  overdue: { color: CORES.erro },
  dreResult: {
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    backgroundColor: "#F5F3FF",
  },
  dreResultLabel: {
    color: "#6D28D9",
    fontSize: FONTE.pequena,
    fontWeight: "800",
  },
  dreResultValue: { fontSize: FONTE.destaque, fontWeight: "900", marginTop: 3 },
  dreMargin: {
    color: "#6D28D9",
    fontSize: FONTE.pequena,
    marginTop: ESPACO.xs,
  },
  unavailable: {
    color: CORES.textoSecundario,
    fontSize: FONTE.normal,
    paddingVertical: ESPACO.md,
  },
  footnote: {
    color: CORES.textoClaro,
    fontSize: 11,
    marginTop: ESPACO.sm,
    lineHeight: 16,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: CORES.superficie,
    borderTopLeftRadius: RAIO.lg,
    borderTopRightRadius: RAIO.lg,
    padding: ESPACO.lg,
    paddingBottom: ESPACO.xl,
  },
  modalTitle: { color: CORES.texto, fontSize: FONTE.titulo, fontWeight: "900" },
  modalSubtitle: {
    color: CORES.textoSecundario,
    fontSize: FONTE.normal,
    marginTop: ESPACO.xs,
  },
  inputLabel: {
    color: CORES.texto,
    fontSize: FONTE.normal,
    fontWeight: "700",
    marginTop: ESPACO.md,
  },
  input: {
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: 12,
    color: CORES.texto,
    fontSize: FONTE.media,
    marginTop: ESPACO.xs,
  },
  modalActions: { flexDirection: "row", gap: ESPACO.sm, marginTop: ESPACO.lg },
  modalButton: {
    flex: 1,
    alignItems: "center",
    borderRadius: RAIO.md,
    paddingVertical: 13,
  },
  modalCancel: { backgroundColor: "#F1F5F4" },
  modalApply: { backgroundColor: CORES.primario },
  modalCancelText: { color: CORES.texto, fontWeight: "800" },
  modalApplyText: { color: "#fff", fontWeight: "800" },
});
