import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const foodCalculatorStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  content: { padding: ESPACO.lg, paddingBottom: 140 },
  header: { alignItems: 'center', marginBottom: ESPACO.lg },
  emoji: { fontSize: 48, marginBottom: ESPACO.sm },
  titulo: { fontSize: FONTE.titulo, fontWeight: 'bold', color: CORES.texto },
  subtitulo: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    textAlign: 'center',
    marginTop: ESPACO.xs,
  },
  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
    marginBottom: ESPACO.lg,
    ...SOMBRA,
  },
  campo: { marginBottom: ESPACO.md },
  label: { fontSize: FONTE.normal, fontWeight: '600', color: CORES.texto, marginBottom: ESPACO.xs },
  input: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm + 2,
    fontSize: FONTE.media,
    color: CORES.texto,
    backgroundColor: CORES.fundo,
  },
  seletorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm + 2,
    backgroundColor: CORES.fundo,
    gap: ESPACO.sm,
  },
  seletorNome: { fontSize: FONTE.normal, fontWeight: '600', color: CORES.texto },
  seletorSub: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  seletorPlaceholder: { flex: 1, fontSize: FONTE.normal, color: CORES.textoClaro },
  nivelCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: ESPACO.sm,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    marginBottom: ESPACO.xs,
    gap: ESPACO.sm,
  },
  nivelAtivo: { borderColor: CORES.primario, backgroundColor: CORES.primarioClaro },
  nivelEmoji: { fontSize: 22 },
  nivelLabel: { fontSize: FONTE.normal, fontWeight: '600', color: CORES.texto },
  nivelLabelAtivo: { color: CORES.primario },
  nivelDesc: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  botao: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.md,
    alignItems: 'center',
    marginTop: ESPACO.sm,
  },
  botaoDesativado: { opacity: 0.7 },
  botaoTexto: { color: '#fff', fontSize: FONTE.media, fontWeight: 'bold' },

  // Resultado
  resultadoCard: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
    marginBottom: ESPACO.lg,
    ...SOMBRA,
  },
  resultadoCardCompact: { flex: 1, marginHorizontal: ESPACO.xs, padding: ESPACO.sm },
  resultadoTituloCompact: { fontSize: FONTE.normal, marginBottom: ESPACO.xs },
  itemResultadoCompact: { padding: ESPACO.xs, gap: ESPACO.xs },
  itemEmojiCompact: { fontSize: 14 },
  itemTituloCompact: { fontSize: 10 },
  itemValorCompact: { fontSize: FONTE.normal },
  resultadoNome: {
    fontSize: FONTE.pequena,
    fontWeight: '600',
    color: CORES.primario,
    marginBottom: ESPACO.xs,
  },
  resultadoTitulo: {
    fontSize: FONTE.grande,
    fontWeight: 'bold',
    color: CORES.texto,
    marginBottom: ESPACO.md,
  },
  itemResultado: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: ESPACO.sm,
    borderRadius: RAIO.md,
    marginBottom: ESPACO.xs,
    gap: ESPACO.sm,
  },
  itemDestaque: { backgroundColor: CORES.primarioClaro },
  itemEmoji: { fontSize: 20 },
  itemTitulo: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  itemValor: { fontSize: FONTE.grande, fontWeight: 'bold', color: CORES.texto },
  itemValorDestaque: { color: CORES.primario },
  alerta: {
    backgroundColor: '#FFFBEB',
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
    borderWidth: 1,
    borderColor: '#FDE68A',
    marginTop: ESPACO.sm,
  },
  alertaTexto: { fontSize: FONTE.normal, color: '#92400E' },

  // Categoria filter botões
  categoriaBotao: {
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.xs + 2,
    borderRadius: RAIO.lg,
    borderWidth: 1.5,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
  },
  categoriaBotaoAtivo: {
    borderColor: CORES.primario,
    backgroundColor: CORES.primarioClaro,
  },
  categoriaBotaoTexto: { fontSize: FONTE.normal, color: CORES.textoSecundario, fontWeight: '500' },
  categoriaBotaoTextoAtivo: { color: CORES.primario, fontWeight: '700' },
  botaoSecundario: {
    borderWidth: 1.5,
    borderColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.sm,
    alignItems: 'center',
    marginTop: ESPACO.xs,
  },
  botaoSecundarioTexto: { color: CORES.primario, fontSize: FONTE.normal, fontWeight: '700' },

  botaoAdicionar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: ESPACO.xs,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.sm,
    marginTop: ESPACO.sm,
  },
  botaoAdicionarTexto: { color: '#fff', fontSize: FONTE.normal, fontWeight: '700' },

  // Comparativo
  comparativoContainer: { marginBottom: ESPACO.lg },
  comparativoTitulo: {
    fontSize: FONTE.grande,
    fontWeight: 'bold',
    color: CORES.texto,
    marginBottom: ESPACO.sm,
  },
  comparativoRow: { flexDirection: 'row', gap: ESPACO.sm },
  veredito: {
    backgroundColor: '#DCFCE7',
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginTop: ESPACO.sm,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  vereditoTexto: { fontSize: FONTE.normal, color: '#166534', fontWeight: '600' },

  // Modal seletor
  modal: { flex: 1, backgroundColor: CORES.fundo },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: ESPACO.lg,
    borderBottomWidth: 1,
    borderBottomColor: CORES.borda,
    backgroundColor: CORES.superficie,
  },
  modalTitulo: { fontSize: FONTE.grande, fontWeight: 'bold', color: CORES.texto },
  buscaRacaoBox: {
    margin: ESPACO.md,
    marginBottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    backgroundColor: CORES.superficie,
    paddingHorizontal: ESPACO.md,
  },
  buscaRacaoInput: {
    flex: 1,
    paddingVertical: ESPACO.sm + 2,
    fontSize: FONTE.normal,
    color: CORES.texto,
  },
  modalVazio: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: ESPACO.xl, gap: ESPACO.md },
  modalVazioTexto: { fontSize: FONTE.grande, fontWeight: '600', color: CORES.texto, textAlign: 'center' },
  modalVazioSub: { fontSize: FONTE.normal, color: CORES.textoSecundario, textAlign: 'center' },
  racaoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginBottom: ESPACO.sm,
    gap: ESPACO.md,
    ...SOMBRA,
  },
  racaoFoto: { width: 60, height: 60, borderRadius: RAIO.sm },
  racaoFotoPlaceholder: {
    backgroundColor: CORES.primarioClaro,
    justifyContent: 'center',
    alignItems: 'center',
  },
  racaoNome: { fontSize: FONTE.normal, fontWeight: '600', color: CORES.texto },
  racaoSub: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },

  // Pet selector
  petSelecionadoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: ESPACO.sm,
  },
  petFotoMini: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  petFotoMiniPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: CORES.primarioClaro,
    justifyContent: 'center',
    alignItems: 'center',
  },
  racaoPreco: { fontSize: FONTE.normal, fontWeight: 'bold', color: CORES.primario, marginTop: 2 },
});
