import { StyleSheet } from "react-native";

export const detalheEntregaStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f9fafb" },
  content: { padding: 16, paddingBottom: 140 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  errorText: { color: "#ef4444", fontSize: 16 },

  resumo: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    justifyContent: "space-around",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  resumoItem: { alignItems: "center" },
  resumoValor: { fontSize: 22, fontWeight: "700", color: "#111827" },
  resumoLabel: { fontSize: 12, color: "#6b7280", marginTop: 2 },

  btnIniciar: {
    backgroundColor: "#2563eb",
    borderRadius: 10,
    padding: 14,
    alignItems: "center",
    marginBottom: 16,
  },
  btnIniciarText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  btnFinalizar: {
    backgroundColor: "#2563eb",
    borderRadius: 10,
    padding: 14,
    alignItems: "center",
    marginBottom: 16,
  },
  btnFinalizarText: { color: "#fff", fontSize: 16, fontWeight: "700" },

  paradaCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  paradaCardInativa: {
    opacity: 1,
  },
  paradaCardAtiva: {
    opacity: 0.95,
    borderWidth: 1,
    borderColor: "#2563eb",
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    transform: [{ scale: 1.01 }],
  },
  paradaHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  ordemWrapper: {
    alignItems: "center",
    width: 64,
  },
  ordemCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#2563eb",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
    marginTop: 2,
  },
  ordemText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  ordemEditHint: {
    marginTop: 4,
    fontSize: 10,
    color: "#2563eb",
    fontWeight: "600",
    textAlign: "center",
  },
  paradaInfo: { flex: 1 },
  paradaCliente: { fontSize: 15, fontWeight: "600", color: "#111827" },
  paradaEndereco: { fontSize: 13, color: "#6b7280", marginTop: 2 },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    flexShrink: 0,
  },
  statusBadgeText: { fontSize: 11, fontWeight: "600" },

  observacoes: {
    fontSize: 13,
    color: "#374151",
    marginBottom: 8,
    fontStyle: "italic",
  },

  paradaBotoes: { flexDirection: "row", gap: 6, marginBottom: 10 },
  btnMapa: {
    flex: 1,
    backgroundColor: "#eff6ff",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
  },
  btnMapaText: { color: "#2563eb", fontWeight: "600", fontSize: 12 },
  btnLigar: {
    flex: 1,
    backgroundColor: "#f0fdf4",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
  },
  btnLigarText: { color: "#16a34a", fontWeight: "600", fontSize: 12 },
  btnRecebimento: {
    flex: 1,
    backgroundColor: "#f5f3ff",
    borderColor: "#c4b5fd",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  btnRecebimentoIcon: { fontSize: 14, lineHeight: 16 },
  btnRecebimentoText: { color: "#6d28d9", fontWeight: "600", fontSize: 12 },
  btnDetalhes: {
    flex: 1,
    backgroundColor: "#e0f2fe",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 6,
    alignItems: "center",
  },
  btnDetalhesText: { color: "#0369a1", fontWeight: "600", fontSize: 12 },
  btnDrag: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: "#eff6ff",
    marginRight: 8,
    marginTop: 2,
  },
  btnDragAtivo: {
    backgroundColor: "#dbeafe",
  },
  btnDragText: { fontSize: 14, color: "#1d4ed8", fontWeight: "700" },
  dragHint: {
    fontSize: 12,
    color: "#4b5563",
    marginBottom: 10,
  },

  paradaAcoes: { flexDirection: "row", gap: 8 },
  btnEntregue: {
    flex: 1,
    backgroundColor: "#10b981",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  btnEntregueText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  btnNaoEntregue: {
    flex: 1,
    backgroundColor: "#ef4444",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  btnNaoEntregueText: { color: "#fff", fontWeight: "700", fontSize: 14 },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
  },
  modalTitulo: { fontSize: 18, fontWeight: "700", color: "#111827" },
  modalSubtitulo: {
    fontSize: 13,
    color: "#6b7280",
    marginTop: 4,
    marginBottom: 14,
  },
  modalResumoOrdem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dbeafe",
    backgroundColor: "#eff6ff",
    padding: 12,
    marginBottom: 14,
  },
  modalResumoOrdemLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1d4ed8",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  modalResumoOrdemCliente: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
  },
  modalResumoOrdemEndereco: {
    fontSize: 13,
    color: "#4b5563",
    marginTop: 4,
  },
  modalCampoLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: "#111827",
    marginBottom: 16,
  },
  modalTextarea: {
    minHeight: 92,
  },
  modalHeaderDetalhes: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  fecharDetalhes: { color: "#dc2626", fontWeight: "700" },
  detalheLinha: { fontSize: 14, color: "#374151", marginBottom: 6 },
  detalheLabel: { fontWeight: "700", color: "#111827" },
  itemVenda: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    backgroundColor: "#f9fafb",
  },
  itemVendaNome: { fontSize: 14, fontWeight: "600", color: "#111827" },
  itemVendaValor: { fontSize: 12, color: "#4b5563", marginTop: 4 },
  opcoesLinha: { flexDirection: "row", gap: 8 },
  opcaoBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
  opcaoBtnAtivo: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  opcaoTexto: { color: "#374151", fontWeight: "600" },
  opcaoTextoAtivo: { color: "#1d4ed8" },
  parcelasWrap: { marginTop: 12 },
  parcelasTitulo: { marginBottom: 8, color: "#374151", fontWeight: "600" },
  parcelasGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  parcelaBtn: {
    width: 52,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  parcelaBtnAtivo: {
    borderColor: "#2563eb",
    backgroundColor: "#eff6ff",
  },
  parcelaTexto: { color: "#374151", fontWeight: "600" },
  parcelaTextoAtivo: { color: "#1d4ed8" },
  modalAcoes: {
    marginTop: 16,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
  modalCancelar: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
  },
  modalCancelarText: { color: "#111827", fontWeight: "700" },
  modalConfirmar: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#2563eb",
  },
  modalConfirmarDanger: {
    backgroundColor: "#dc2626",
  },
  modalConfirmarText: { color: "#fff", fontWeight: "700" },
});
