sonar.exclusions=backend/tests/**,backend/alembic/**,**/backend/alembic/**,backend/migrations/**,**/backend/migrations/**
sonar.cpd.exclusions=backend/tests/**,backend/app/scripts/**,backend/alembic/**,**/backend/alembic/**,backend/migrations/**,**/backend/migrations/**,frontend/src/components/layout/menuConfig.js
