sonar.projectKey=lcsgmoraes-droid_Sistema-Pet
sonar.organization=lcsgmoraes-droid
sonar.sources=.
sonar.cpd.exclusions=backend/tests/**,backend/app/scripts/**,backend/alembic/versions/**,frontend/src/components/layout/menuConfig.js
