import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const trackDeliveryStyles = StyleSheet.create({
  container: { padding: ESPACO.md, gap: ESPACO.sm },
  loading: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  loadingText: { fontSize: FONTE.normal, color: CORES.textoSecundario },
  erroEmoji: { fontSize: 40 },
  erroText: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    textAlign: "center",
  },
  flex1: { flex: 1 },
  heroCard: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.lg,
    alignItems: "center",
    gap: 8,
    ...SOMBRA,
  },
  heroEmoji: { fontSize: 52 },
  heroTitulo: { fontSize: 22, fontWeight: "700", color: CORES.texto },
  heroSubtitulo: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    textAlign: "center",
  },
  entregadorCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.sm,
    ...SOMBRA,
  },
  entregadorIcone: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: CORES.primarioClaro,
    justifyContent: "center",
    alignItems: "center",
  },
  entregadorNome: {
    fontSize: FONTE.normal,
    fontWeight: "700",
    color: CORES.texto,
  },
  entregadorLabel: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: RAIO.circulo,
  },
  statusBadgeTexto: { fontSize: FONTE.pequena, fontWeight: "600" },
  progressoCard: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: 8,
    ...SOMBRA,
  },
  progressoTitulo: {
    fontSize: FONTE.normal,
    fontWeight: "600",
    color: CORES.texto,
  },
  progressoBar: {
    height: 8,
    backgroundColor: "#E5E7EB",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressoPreenchido: {
    height: "100%",
    backgroundColor: CORES.primario,
    borderRadius: 4,
  },
  progressoTexto: { fontSize: FONTE.normal, color: CORES.textoSecundario },
  progressoAntes: {
    fontSize: FONTE.normal,
    fontWeight: "600",
    color: "#92400E",
  },
  enderecoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.sm,
    ...SOMBRA,
  },
  enderecoLabel: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  enderecoTexto: {
    fontSize: FONTE.normal,
    color: CORES.texto,
    fontWeight: "500",
  },
  btnMaps: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    padding: 8,
    backgroundColor: CORES.primarioClaro,
    borderRadius: RAIO.sm,
  },
  btnMapsTexto: {
    fontSize: FONTE.pequena,
    color: CORES.primario,
    fontWeight: "600",
  },
  mapaCard: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: 8,
    ...SOMBRA,
  },
  mapaTitulo: {
    fontSize: FONTE.normal,
    fontWeight: "700",
    color: CORES.texto,
  },
  mapaSubtitulo: {
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
  },
  mapaLegenda: {
    fontSize: FONTE.pequena,
    color: CORES.primario,
    fontWeight: "600",
  },
  mapa: {
    width: "100%",
    height: 220,
    borderRadius: RAIO.md,
  },
  markerWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  markerPulse: {
    position: "absolute",
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(37,99,235,0.18)",
  },
  markerIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#0F5F66",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  palavraChaveCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.primarioClaro,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.md,
    ...SOMBRA,
  },
  palavraChaveLabel: { fontSize: FONTE.normal, color: CORES.primario },
  palavraChaveValor: {
    fontSize: 24,
    fontWeight: "800",
    color: CORES.primario,
    letterSpacing: 2,
  },
  infoCard: {
    flexDirection: "row",
    gap: ESPACO.sm,
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    alignItems: "flex-start",
    ...SOMBRA,
  },
  infoCardSpaced: { marginTop: ESPACO.md },
  infoTexto: { fontSize: FONTE.normal, color: CORES.textoSecundario, flex: 1 },
  entregueCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D1FAE5",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.sm,
  },
  entregueLabel: { fontSize: FONTE.pequena, color: "#065F46" },
  entregueData: { fontSize: FONTE.normal, fontWeight: "700", color: "#065F46" },
  atualizadoEm: {
    textAlign: "center",
    fontSize: FONTE.pequena,
    color: CORES.textoClaro,
  },
  autoAtualizaAviso: {
    textAlign: "center",
    fontSize: 11,
    color: CORES.textoClaro,
    marginTop: -4,
  },
});
