from app.dre_ia_routes_parts.anomalias_export_routes import (
    exportar_dre_excel,
    exportar_dre_pdf,
    obter_anomalias_dre,
    recalcular_anomalias,
)
from app.dre_ia_routes_parts.base_routes import (
    calcular_dre,
    calcular_mes_atual,
    calcular_mes_passado,
    comparar_periodos,
    listar_canais,
    listar_dres,
    listar_setores,
    obter_categorias_rentabilidade,
    obter_dre,
    obter_indices_mercado,
    obter_insights,
    obter_produtos_rentabilidade,
)
from app.dre_ia_routes_parts.canal_routes import (
    calcular_dre_consolidado_canais,
    calcular_dre_por_canal,
    listar_canais_disponiveis,
    listar_dres_por_canal,
)
from app.dre_ia_routes_parts.dependencies import _usuario_dre
from app.dre_ia_routes_parts.detalhada_routes import (
    alocar_despesa,
    calcular_dre_consolidado,
    calcular_dre_detalhado,
)
from app.dre_ia_routes_parts.schemas import (
    AlocarDespesaRequest,
    CalcularDRECanalRequest,
    CalcularDREConsolidadoRequest,
    CalcularDREDetalhadadRequest,
    CalcularDRERequest,
    CategoriaRentabilidade,
    DRECompleto,
    DREDetalheResponse,
    DREResumo,
    InsightDRE,
    ProdutoRentabilidade,
)

__all__ = [
    "_usuario_dre",
    "DREResumo",
    "DRECompleto",
    "ProdutoRentabilidade",
    "CategoriaRentabilidade",
    "InsightDRE",
    "CalcularDRERequest",
    "CalcularDRECanalRequest",
    "CalcularDREConsolidadoRequest",
    "CalcularDREDetalhadadRequest",
    "DREDetalheResponse",
    "AlocarDespesaRequest",
    "calcular_dre",
    "listar_canais",
    "listar_dres",
    "obter_dre",
    "obter_produtos_rentabilidade",
    "obter_categorias_rentabilidade",
    "obter_insights",
    "comparar_periodos",
    "obter_indices_mercado",
    "listar_setores",
    "calcular_mes_atual",
    "calcular_mes_passado",
    "obter_anomalias_dre",
    "recalcular_anomalias",
    "exportar_dre_pdf",
    "exportar_dre_excel",
    "listar_canais_disponiveis",
    "calcular_dre_por_canal",
    "calcular_dre_consolidado_canais",
    "listar_dres_por_canal",
    "calcular_dre_detalhado",
    "calcular_dre_consolidado",
    "alocar_despesa",
]
