import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const vetAgendaStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  content: { padding: ESPACO.md, gap: ESPACO.md },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: CORES.fundo,
  },
  title: { fontSize: FONTE.titulo, color: CORES.texto, fontWeight: "800" },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ESPACO.sm,
  },
  newButton: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
  },
  newButtonText: { color: "#fff", fontWeight: "800" },
  segment: {
    flexDirection: "row",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: 4,
    ...SOMBRA,
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: ESPACO.sm,
    borderRadius: RAIO.sm,
  },
  segmentButtonActive: { backgroundColor: CORES.primario },
  segmentText: { color: CORES.textoSecundario, fontWeight: "800" },
  segmentTextActive: { color: "#FFFFFF" },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ESPACO.sm,
  },
  navButton: {
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.sm,
  },
  navText: {
    color: CORES.primario,
    fontWeight: "800",
    fontSize: FONTE.pequena,
  },
  periodTitle: {
    flex: 1,
    textAlign: "center",
    color: CORES.texto,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  dayGroup: { gap: ESPACO.sm },
  dayTitle: {
    color: CORES.textoSecundario,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderLeftWidth: 4,
    borderLeftColor: CORES.primario,
    ...SOMBRA,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: ESPACO.sm,
  },
  time: { fontSize: FONTE.grande, color: CORES.primario, fontWeight: "800" },
  badge: {
    backgroundColor: CORES.primarioClaro,
    color: CORES.primario,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.xs,
    borderRadius: RAIO.circulo,
    overflow: "hidden",
    fontWeight: "800",
    textTransform: "capitalize",
  },
  badgeReturn: { backgroundColor: "#ecfdf5", color: CORES.sucesso },
  pet: {
    fontSize: FONTE.grande,
    color: CORES.texto,
    fontWeight: "800",
    marginBottom: ESPACO.xs,
  },
  text: { color: CORES.textoSecundario, fontSize: FONTE.normal, marginTop: 2 },
  status: {
    color: CORES.texto,
    fontSize: FONTE.pequena,
    fontWeight: "800",
    marginTop: ESPACO.sm,
  },
  empty: {
    color: CORES.textoSecundario,
    textAlign: "center",
    marginTop: ESPACO.xl,
  },
  emptyInline: { color: CORES.textoSecundario, paddingVertical: ESPACO.sm },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.45)",
  },
  modalCard: {
    maxHeight: "92%",
    backgroundColor: CORES.fundo,
    borderTopLeftRadius: RAIO.lg,
    borderTopRightRadius: RAIO.lg,
  },
  modalContent: {
    padding: ESPACO.md,
    gap: ESPACO.sm,
    paddingBottom: ESPACO.xl,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { color: CORES.texto, fontSize: FONTE.titulo, fontWeight: "900" },
  closeText: { color: CORES.primario, fontWeight: "800" },
  label: {
    color: CORES.textoSecundario,
    fontWeight: "800",
    fontSize: FONTE.pequena,
    marginTop: ESPACO.xs,
  },
  input: {
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    color: CORES.texto,
  },
  dateInputWrap: {
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    paddingRight: ESPACO.md,
    flexDirection: "row",
    alignItems: "center",
  },
  dateInputText: {
    flex: 1,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    color: CORES.texto,
    fontWeight: "800",
  },
  calendarCard: {
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
    gap: ESPACO.sm,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  calendarNavButton: {
    width: 36,
    height: 36,
    borderRadius: RAIO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarTitle: {
    color: CORES.texto,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  calendarWeekRow: { flexDirection: "row" },
  calendarWeekText: {
    width: `${100 / 7}%`,
    textAlign: "center",
    color: CORES.textoSecundario,
    fontWeight: "900",
    fontSize: FONTE.pequena,
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  calendarDay: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RAIO.sm,
    borderWidth: 1,
    borderColor: "transparent",
  },
  calendarDayOutside: { opacity: 0.45 },
  calendarDayToday: { borderColor: CORES.primario },
  calendarDaySelected: {
    backgroundColor: CORES.primario,
    borderColor: CORES.primario,
  },
  calendarDayText: { color: CORES.texto, fontWeight: "800" },
  calendarDayOutsideText: { color: CORES.textoSecundario },
  calendarDaySelectedText: { color: "#FFFFFF" },
  calendarTodayButton: {
    alignSelf: "flex-start",
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.xs,
  },
  calendarTodayText: { color: CORES.primario, fontWeight: "900" },
  textArea: { minHeight: 76, textAlignVertical: "top" },
  petList: { gap: ESPACO.xs },
  petOption: {
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
  },
  petOptionActive: {
    borderColor: CORES.primario,
    backgroundColor: CORES.primarioClaro,
  },
  petOptionTitle: { color: CORES.texto, fontWeight: "900" },
  petOptionTitleActive: { color: CORES.primario },
  petOptionText: {
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    marginTop: 2,
  },
  chipsRow: { gap: ESPACO.sm, paddingVertical: ESPACO.xs },
  chip: {
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.circulo,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
  },
  chipActive: {
    borderColor: CORES.primario,
    backgroundColor: CORES.primarioClaro,
  },
  chipText: { color: CORES.textoSecundario, fontWeight: "800" },
  chipTextActive: { color: CORES.primario },
  slotsGrid: { flexDirection: "row", flexWrap: "wrap", gap: ESPACO.xs },
  slot: {
    minWidth: 64,
    borderRadius: RAIO.sm,
    paddingVertical: ESPACO.sm,
    paddingHorizontal: ESPACO.sm,
    alignItems: "center",
    borderWidth: 2,
  },
  slotLivre: { backgroundColor: "#DCFCE7", borderColor: "#DCFCE7" },
  slotOcupado: { backgroundColor: "#FEF3C7", borderColor: "#FEF3C7" },
  slotSelecionado: { borderColor: CORES.primario },
  slotText: { color: CORES.texto, fontWeight: "900" },
  legendRow: { flexDirection: "row", gap: ESPACO.sm, marginBottom: ESPACO.xs },
  legendLivre: { color: "#15803D", fontWeight: "800", fontSize: FONTE.pequena },
  legendOcupado: {
    color: "#A16207",
    fontWeight: "800",
    fontSize: FONTE.pequena,
  },
  twoColumns: { flexDirection: "row", gap: ESPACO.sm },
  flexField: { flex: 1 },
  readonlyField: {
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
  },
  readonlyText: { color: CORES.texto, fontWeight: "800" },
  saveButton: {
    backgroundColor: CORES.sucesso,
    borderRadius: RAIO.sm,
    paddingVertical: ESPACO.md,
    alignItems: "center",
    marginTop: ESPACO.md,
  },
  disabledButton: { opacity: 0.65 },
  saveButtonText: { color: "#fff", fontWeight: "900" },
});
