import { formatBRL } from "../utils/formatters";
import {
  RANK_LABELS,
  CUPOM_STATUS,
  TIPO_LABELS,
  USER_CREATABLE_TYPES,
  createDefaultPremio,
} from "../components/campanhas/campanhasConstants";

export default function useCampanhasPageComposition({
  aba,
  setAba,
  consultas,
  gestao,
  gestor,
  configuracoes,
  inativos,
  retencao,
  cupons,
  destaque,
  sorteios,
  unificacao,
}) {
  const {
    campanhas,
    loadingCampanhas,
    dashboard,
    loadingDashboard,
    retencaoRegras,
    loadingRetencao,
    ranking,
    loadingRanking,
    filtroNivel,
    setFiltroNivel,
    cupons: listaCupons,
    loadingCupons,
    filtroCupomStatus,
    setFiltroCupomStatus,
    filtroCupomBusca,
    setFiltroCupomBusca,
    filtroCupomDataInicio,
    setFiltroCupomDataInicio,
    filtroCupomDataFim,
    setFiltroCupomDataFim,
    filtroCupomCampanha,
    setFiltroCupomCampanha,
    cupomDetalhes,
    setCupomDetalhes,
    destaque: destaqueAtual,
    loadingDestaque,
    premiosPorVencedor,
    setPremiosPorVencedor,
    vencedoresSelecionados,
    setVencedoresSelecionados,
    sorteios: listaSorteios,
    loadingSorteios,
    sugestoes,
    loadingSugestoes,
    relatorio,
    loadingRelatorio,
    relDataInicio,
    setRelDataInicio,
    relDataFim,
    setRelDataFim,
    relTipo,
    setRelTipo,
    rankingConfigLoading,
    schedulerConfigLoading,
    loadingCodigosOffline,
    codigosOffline,
    carregarCupons,
    carregarDestaque,
    carregarSugestoes,
  } = consultas;

  const mainContentProps = {
    aba,
    onAbrirAba: setAba,
    consultas: {
      campanhas,
      loadingCampanhas,
      dashboard,
      loadingDashboard,
      retencaoRegras,
      loadingRetencao,
      ranking,
      loadingRanking,
      filtroNivel,
      setFiltroNivel,
      cupons: listaCupons,
      loadingCupons,
      filtroCupomStatus,
      setFiltroCupomStatus,
      filtroCupomBusca,
      setFiltroCupomBusca,
      filtroCupomDataInicio,
      setFiltroCupomDataInicio,
      filtroCupomDataFim,
      setFiltroCupomDataFim,
      filtroCupomCampanha,
      setFiltroCupomCampanha,
      cupomDetalhes,
      setCupomDetalhes,
      destaque: destaqueAtual,
      loadingDestaque,
      premiosPorVencedor,
      setPremiosPorVencedor,
      vencedoresSelecionados,
      setVencedoresSelecionados,
      sorteios: listaSorteios,
      loadingSorteios,
      sugestoes,
      loadingSugestoes,
      relatorio,
      loadingRelatorio,
      relDataInicio,
      setRelDataInicio,
      relDataFim,
      setRelDataFim,
      relTipo,
      setRelTipo,
      rankingConfigLoading,
      schedulerConfigLoading,
      carregarCupons,
      carregarDestaque,
      carregarSugestoes,
    },
    gestao: {
      ...gestao,
      tipoLabels: TIPO_LABELS,
      userCreatableTypes: USER_CREATABLE_TYPES,
    },
    gestor: {
      ...gestor,
      formatBRL,
      RANK_LABELS,
      CUPOM_STATUS,
    },
    configuracoes: {
      ...configuracoes,
      rankLabels: RANK_LABELS,
      cupomStatus: CUPOM_STATUS,
      formatBRL,
      createDefaultPremio,
    },
    inativos,
    retencao: {
      ...retencao,
      novaRegraPadrao: retencao.novaRegraPadrao,
    },
    cupons,
    destaque,
    sorteios: {
      ...sorteios,
      rankLabels: RANK_LABELS,
    },
    unificacao,
  };

  const modalsLayerProps = {
    modalEnvioInativos: inativos.modalEnvioInativos,
    setModalEnvioInativos: inativos.setModalEnvioInativos,
    resultadoEnvioInativos: inativos.resultadoEnvioInativos,
    setResultadoEnvioInativos: inativos.setResultadoEnvioInativos,
    envioInativosForm: inativos.envioInativosForm,
    setEnvioInativosForm: inativos.setEnvioInativosForm,
    enviandoInativos: inativos.enviandoInativos,
    enviarParaInativos: inativos.enviarParaInativos,
    modalSorteio: sorteios.modalSorteio,
    setModalSorteio: sorteios.setModalSorteio,
    novoSorteio: sorteios.novoSorteio,
    setNovoSorteio: sorteios.setNovoSorteio,
    erroCriarSorteio: sorteios.erroCriarSorteio,
    criarSorteio: sorteios.criarSorteio,
    criandoSorteio: sorteios.criandoSorteio,
    modalCodigosOffline: sorteios.modalCodigosOffline,
    setModalCodigosOffline: sorteios.setModalCodigosOffline,
    loadingCodigosOffline,
    codigosOffline,
    rankLabels: RANK_LABELS,
    fidModalManual: gestor.fidModalManual,
    setFidModalManual: gestor.setFidModalManual,
    fidClienteId: gestor.fidClienteId,
    fidManualNota: gestor.fidManualNota,
    setFidManualNota: gestor.setFidManualNota,
    lancarCarimboManual: gestor.lancarCarimboManual,
    fidLancandoManual: gestor.fidLancandoManual,
    modalLote: configuracoes.modalLote,
    setModalLote: configuracoes.setModalLote,
    loteForm: configuracoes.loteForm,
    setLoteForm: configuracoes.setLoteForm,
    resultadoLote: configuracoes.resultadoLote,
    enviarLote: configuracoes.enviarLote,
    enviandoLote: configuracoes.enviandoLote,
    modalCriarCampanha: gestao.modalCriarCampanha,
    setModalCriarCampanha: gestao.setModalCriarCampanha,
    novaCampanha: gestao.novaCampanha,
    setNovaCampanha: gestao.setNovaCampanha,
    erroCriarCampanha: gestao.erroCriarCampanha,
    criarCampanha: gestao.criarCampanha,
    criandoCampanha: gestao.criandoCampanha,
    modalCupomAberto: cupons.modalCupomAberto,
    setModalCupomAberto: cupons.setModalCupomAberto,
    setErroCupom: cupons.setErroCupom,
    novoCupom: cupons.novoCupom,
    setNovoCupom: cupons.setNovoCupom,
    erroCupom: cupons.erroCupom,
    criarCupomManual: cupons.criarCupomManual,
    criandoCupom: cupons.criandoCupom,
  };

  return {
    mainContentProps,
    modalsLayerProps,
  };
}
