export default function useProdutosPageComposition({
  catalogosState,
  columnsState,
  conflictState,
  filtersState,
  headerState,
  importState,
  modalsState,
  reportState,
  tableState,
  utilsState,
}) {
  const {
    categorias,
    departamentos,
    fornecedores,
    marcas,
  } = catalogosState;
  const {
    abrirModalColunas,
    colunasRelatorio,
    colunasTemporarias,
    colunasTabela,
    filtrarColunas,
    modalColunas,
    modalRelatorioPersonalizado,
    onCloseModalColunas,
    onCloseModalRelatorio,
    onGerarRelatorioPersonalizado,
    onOpenModalRelatorio,
    onRestaurarColunasPadrao,
    onSalvarColunas,
    onToggleColuna,
    onToggleColunaRelatorio,
    ordenacaoRelatorio,
    setOrdenacaoRelatorio,
  } = columnsState;
  const {
    autoSelecionarConflito,
    bloqueiosExclusao,
    modalConflitoExclusao,
    onCancelarConflito,
    onCloseModalConflito,
    onSelecionarTodasVariacoesDoPai,
    onSelecionarVariacaoConflito,
    onToggleAutoSelecionarConflito,
    onTogglePularConfirmacaoConflito,
    pularConfirmacaoConflito,
    resolvendoConflitoExclusao,
    variacoesSelecionadasConflito,
  } = conflictState;
  const {
    filtros,
    handleFiltroChange,
    persistirBusca,
    setPersistirBusca,
  } = filtersState;
  const {
    iniciarTour,
    menuRelatoriosAberto,
    menuRelatoriosRef,
    navigate,
    onExcluirSelecionados,
    onGerarRelatorioFiltrado,
    onGerarRelatorioGeral,
    onOpenEdicaoLote,
    onOpenImportacao,
    onToggleMenuRelatorios,
    selecionadosCount,
  } = headerState;
  const {
    modalImportacao,
    onCloseImportacao,
    onImportacaoSucesso,
  } = importState;
  const {
    dadosEdicaoLote,
    modalEdicaoLote,
    onCloseModalEdicaoLote,
    onSalvarEdicaoLote,
    setDadosEdicaoLote,
  } = modalsState;
  const { colunasRelatorioProdutos } = reportState;
  const {
    editandoMargem,
    editandoPreco,
    getCorEstoque,
    getValidadeMaisProxima,
    handleCancelarEdicaoPreco,
    handleEditarPreco,
    handleExcluir,
    handleSalvarMargem,
    handleSalvarPreco,
    handleSelecionar,
    handleSelecionarTodos,
    handleToggleAtivo,
    itensPorPagina,
    kitsExpandidos,
    linhaProdutoRefs,
    loading,
    novoPreco,
    onChangeItensPorPagina,
    onIrParaPagina,
    onIrParaPrimeiraPagina,
    onIrParaUltimaPagina,
    onPaginaAnterior,
    onProximaPagina,
    paginaAtual,
    paisExpandidos,
    produtos,
    selecionados,
    setEditandoMargem,
    setNovoPreco,
    toggleKitExpandido,
    togglePaiExpandido,
    totalItens,
    totalPaginas,
  } = tableState;
  const { copiarTexto, corrigirTextoQuebrado, isProdutoComComposicao } =
    utilsState;

  return {
    mainContentProps: {
      abrirModalColunas,
      categorias,
      copiarTexto,
      editandoMargem,
      editandoPreco,
      filtrarColunas,
      filtros,
      fornecedores,
      getCorEstoque,
      getValidadeMaisProxima,
      handleCancelarEdicaoPreco,
      handleEditarPreco,
      handleExcluir,
      handleFiltroChange,
      handleSalvarMargem,
      handleSalvarPreco,
      handleSelecionar,
      handleSelecionarTodos,
      handleToggleAtivo,
      iniciarTour,
      isProdutoComComposicao,
      itensPorPagina,
      kitsExpandidos,
      linhaProdutoRefs,
      loading,
      marcas,
      menuRelatoriosAberto,
      menuRelatoriosRef,
      navigate,
      novoPreco,
      onChangeItensPorPagina,
      onExcluirSelecionados,
      onGerarRelatorioFiltrado,
      onGerarRelatorioGeral,
      onIrParaPagina,
      onIrParaPrimeiraPagina,
      onIrParaUltimaPagina,
      onOpenEdicaoLote,
      onOpenImportacao,
      onOpenModalRelatorio,
      onPaginaAnterior,
      onProximaPagina,
      onToggleMenuRelatorios,
      paginaAtual,
      paisExpandidos,
      persistirBusca,
      produtos,
      produtosColunas: colunasTabela,
      selecionados,
      selecionadosCount,
      setEditandoMargem,
      setNovoPreco,
      setPersistirBusca,
      toggleKitExpandido,
      togglePaiExpandido,
      totalItens,
      totalPaginas,
    },
    modalsLayerProps: {
      autoSelecionarConflito,
      bloqueiosExclusao,
      categorias,
      colunasRelatorio,
      colunasRelatorioProdutos,
      colunasTabela,
      colunasTemporarias,
      corrigirTextoQuebrado,
      dadosEdicaoLote,
      departamentos,
      fornecedores,
      marcas,
      modalColunas,
      modalConflitoExclusao,
      modalEdicaoLote,
      modalImportacao,
      modalRelatorioPersonalizado,
      onCancelarConflito,
      onCloseImportacao,
      onCloseModalColunas,
      onCloseModalConflito,
      onCloseModalEdicaoLote,
      onCloseModalRelatorio,
      onGerarRelatorioPersonalizado,
      onImportacaoSucesso,
      onRestaurarColunasPadrao,
      onSalvarColunas,
      onSalvarEdicaoLote,
      onSelecionarTodasVariacoesDoPai,
      onSelecionarVariacaoConflito,
      onToggleAutoSelecionarConflito,
      onToggleColuna,
      onToggleColunaRelatorio,
      onTogglePularConfirmacaoConflito,
      ordenacaoRelatorio,
      pularConfirmacaoConflito,
      resolvendoConflitoExclusao,
      selecionadosCount,
      setDadosEdicaoLote,
      setOrdenacaoRelatorio,
      variacoesSelecionadasConflito,
    },
  };
}
