export function usePDVPageComposition({
  navigate,
  destaqueAbrirCaixa,
  destaqueVenda,
  caixaGuiaClasses,
  vendaGuiaClasses,
  iniciarTour,
  searchVendaQuery,
  setSearchVendaQuery,
  handleBuscarVenda,
  vendaAtual,
  pendenciasCount,
  opportunities,
  painelAssistenteAberto,
  mensagensAssistente,
  setMostrarPendenciasEstoque,
  abrirPainelOportunidades,
  alternarPainelAssistente,
  caixaKey,
  setMostrarModalAbrirCaixa,
  modoVisualizacao,
  loading,
  temCaixaAberto,
  cancelarEdicao,
  excluirVenda,
  salvarVenda,
  abrirModalPagamento,
  setModoVisualizacao,
  limparVenda,
  emitirNotaVendaFinalizada,
  mudarStatusParaAberta,
  habilitarEdicao,
  setMostrarModalCliente,
  setMostrarHistoricoCliente,
  setMostrarModalAdicionarCredito,
  setMostrarVendasEmAberto,
  buscarCliente,
  buscarClientePorCodigoExato,
  clientesSugeridos,
  copiadoClienteCampo,
  setBuscarCliente,
  copiarCampoCliente,
  limparClienteSelecionado,
  selecionarCliente,
  selecionarPet,
  saldoCampanhas,
  vendasEmAbertoInfo,
  buscaProduto,
  buscaProdutoContainerRef,
  copiadoCodigoItem,
  inputProdutoRef,
  itensKitExpandidos,
  mostrarSugestoesProduto,
  abrirModalDescontoItem,
  adicionarNaListaEsperaRapido,
  alterarQuantidade,
  atualizarPetDoItem,
  atualizarQuantidadeItem,
  handleBuscarProdutoChange,
  handleBuscarProdutoFocus,
  handleBuscarProdutoKeyDown,
  copiarCodigoProdutoCarrinho,
  removerItem,
  selecionarProdutoSugerido,
  toggleKitExpansion,
  pendenciasProdutoIds,
  produtosSugeridos,
  setVendaAtual,
  entregadorSelecionado,
  entregadores,
  abrirModalEndereco,
  handleEnderecoEntregaChange,
  handleObservacoesEntregaChange,
  handleSelecionarEnderecoEntrega,
  handleSelecionarEntregador,
  handleTaxaEntregaTotalChange,
  handleTaxaEntregadorChange,
  handleTaxaLojaChange,
  handleToggleTemEntrega,
  alertasCarrinho,
  codigoCupom,
  cupomAplicado,
  erroCupom,
  loadingCupom,
  abrirModalDescontoTotal,
  aplicarCupom,
  handleCodigoCupomChange,
  handleCodigoCupomKeyDown,
  removerCupom,
  removerDescontoTotal,
  totalImpostos,
  buscaFuncionario,
  funcionarioComissao,
  funcionariosSugeridos,
  handleBuscaFuncionarioChange,
  handleBuscaFuncionarioFocus,
  handleRemoverFuncionarioComissao,
  handleSelecionarFuncionarioComissao,
  handleToggleVendaComissionada,
  vendaComissionada,
  handleNovaVenda,
  painelClienteAberto,
  setPainelClienteAberto,
  painelVendasAberto,
  setPainelVendasAberto,
  filtroVendas,
  setFiltroVendas,
  filtroStatus,
  setFiltroStatus,
  filtroTemEntrega,
  setFiltroTemEntrega,
  buscaNumeroVenda,
  setBuscaNumeroVenda,
  vendasRecentes,
  reabrirVenda,
  confirmandoRetirada,
  abrirConfirmacaoRetirada,
  confirmarRetirada,
  setConfirmandoRetirada,
  painelOportunidadesAberto,
  setPainelOportunidadesAberto,
  adicionarOportunidadeAoCarrinho,
  buscarAlternativaOportunidade,
  ignorarOportunidade,
  setPainelAssistenteAberto,
  enviandoAssistente,
  chatAssistenteEndRef,
  inputAssistente,
  setInputAssistente,
  enviarMensagemAssistente,
  carregandoAnalise,
  dadosAnalise,
  enderecoAtual,
  itemEditando,
  loadingCep,
  mostrarAnaliseVenda,
  mostrarCalculadoraRacao,
  mostrarHistoricoCliente,
  mostrarModalAbrirCaixa,
  mostrarModalAdicionarCredito,
  mostrarModalCliente,
  mostrarModalDescontoItem,
  setMostrarModalDescontoItem,
  mostrarModalDescontoTotal,
  setMostrarModalDescontoTotal,
  mostrarModalEndereco,
  fecharModalEndereco,
  mostrarModalPagamento,
  setMostrarModalPagamento,
  mostrarPendenciasEstoque,
  mostrarVendasEmAberto,
  podeVerMargem,
  racaoIdFechada,
  setTipoDescontoTotal,
  setValorDescontoTotal,
  tipoDescontoTotal,
  valorDescontoTotal,
  handleAbrirCaixaSucesso,
  analisarVendaComFormasPagamento,
  aplicarDescontoTotal,
  buscarCepModal,
  setEnderecoAtual,
  setItemEditando,
  handleClienteCriado,
  fecharCalculadoraRacao,
  handleConfirmarCreditoCliente,
  handleConfirmarPagamento,
  carregarPendencias,
  removerItemEditando,
  salvarDescontoItem,
  salvarEnderecoNoCliente,
  handleVendaAtualizadaAposPagamento,
  handleVendasEmAbertoSucesso,
  driveAlertVisible,
  driveAguardando,
  fecharDriveAlert,
  confirmarDriveEntregue,
}) {
  const driveAlertProps = {
    driveAlertVisible,
    driveAguardando,
    onClose: fecharDriveAlert,
    onConfirmarEntregue: confirmarDriveEntregue,
  };

  const containerStyle =
    driveAlertVisible && driveAguardando.length > 0
      ? { paddingTop: "52px" }
      : {};

  const mainAreaProps = {
    destaqueAbrirCaixa,
    destaqueVenda,
    caixaGuiaClasses,
    vendaGuiaClasses,
    iniciarTour,
    searchVendaQuery,
    onSearchVendaQueryChange: setSearchVendaQuery,
    onBuscarVenda: handleBuscarVenda,
    vendaAtual,
    pendenciasCount,
    opportunitiesCount: opportunities.length,
    painelAssistenteAberto,
    mensagensAssistenteLength: mensagensAssistente.length,
    onAbrirPendenciasEstoque: () => setMostrarPendenciasEstoque(true),
    onAbrirOportunidades: () => {
      void abrirPainelOportunidades();
    },
    onToggleAssistente: () => {
      void alternarPainelAssistente();
    },
    caixaKey,
    onAbrirCaixa: () => setMostrarModalAbrirCaixa(true),
    onNavigateMeusCaixas: () => navigate("/meus-caixas"),
    modoVisualizacao,
    loading,
    temCaixaAberto,
    onCancelarEdicao: cancelarEdicao,
    onExcluirVenda: excluirVenda,
    onSalvarVenda: salvarVenda,
    onAbrirModalPagamento: abrirModalPagamento,
    onSairModoVisualizacao: () => {
      setModoVisualizacao(false);
      limparVenda();
    },
    emitirNotaVendaFinalizada,
    mudarStatusParaAberta,
    habilitarEdicao,
    onAbrirCadastroCliente: () => setMostrarModalCliente(true),
    onAbrirHistoricoCliente: () => setMostrarHistoricoCliente(true),
    onAbrirModalAdicionarCredito: () => setMostrarModalAdicionarCredito(true),
    onAbrirVendasEmAberto: () => setMostrarVendasEmAberto(true),
    buscarCliente,
    buscarClientePorCodigoExato,
    clientesSugeridos,
    copiadoClienteCampo,
    onBuscarClienteChange: setBuscarCliente,
    onCopiarCampoCliente: copiarCampoCliente,
    onRemoverCliente: limparClienteSelecionado,
    onSelecionarCliente: selecionarCliente,
    onSelecionarPet: selecionarPet,
    saldoCampanhas,
    vendasEmAbertoInfo,
    buscaProduto,
    buscaProdutoContainerRef,
    copiadoCodigoItem,
    inputProdutoRef,
    itensKitExpandidos,
    mostrarSugestoesProduto,
    onAbrirModalDescontoItem: abrirModalDescontoItem,
    onAdicionarNaListaEsperaRapido: adicionarNaListaEsperaRapido,
    onAlterarQuantidade: alterarQuantidade,
    onAtualizarPetItem: atualizarPetDoItem,
    onAtualizarQuantidadeItem: atualizarQuantidadeItem,
    onBuscarProdutoChange: handleBuscarProdutoChange,
    onBuscarProdutoFocus: handleBuscarProdutoFocus,
    onBuscarProdutoKeyDown: handleBuscarProdutoKeyDown,
    onCopiarCodigoProdutoCarrinho: copiarCodigoProdutoCarrinho,
    onRemoverItem: removerItem,
    onSelecionarProdutoSugerido: selecionarProdutoSugerido,
    onToggleKitExpansion: toggleKitExpansion,
    pendenciasProdutoIds,
    produtosSugeridos,
    onObservacoesChange: (observacoes) =>
      setVendaAtual((prev) => ({
        ...prev,
        observacoes,
      })),
    entregadorSelecionado,
    entregadores,
    onAbrirModalEndereco: abrirModalEndereco,
    onEnderecoEntregaChange: handleEnderecoEntregaChange,
    onObservacoesEntregaChange: handleObservacoesEntregaChange,
    onSelecionarEndereco: handleSelecionarEnderecoEntrega,
    onSelecionarEntregador: handleSelecionarEntregador,
    onTaxaEntregaTotalChange: handleTaxaEntregaTotalChange,
    onTaxaEntregadorChange: handleTaxaEntregadorChange,
    onTaxaLojaChange: handleTaxaLojaChange,
    onToggleTemEntrega: handleToggleTemEntrega,
    alertasCarrinho,
    codigoCupom,
    cupomAplicado,
    erroCupom,
    loadingCupom,
    onAbrirModalDescontoTotal: abrirModalDescontoTotal,
    onAplicarCupom: aplicarCupom,
    onCodigoCupomChange: handleCodigoCupomChange,
    onCodigoCupomKeyDown: handleCodigoCupomKeyDown,
    onRemoverCupom: removerCupom,
    onRemoverDescontoTotal: removerDescontoTotal,
    totalImpostos,
    buscaFuncionario,
    funcionarioComissao,
    funcionariosSugeridos,
    onBuscaFuncionarioChange: handleBuscaFuncionarioChange,
    onBuscaFuncionarioFocus: handleBuscaFuncionarioFocus,
    onRemoverFuncionario: handleRemoverFuncionarioComissao,
    onSelecionarFuncionario: handleSelecionarFuncionarioComissao,
    onToggleVendaComissionada: handleToggleVendaComissionada,
    vendaComissionada,
    onNovaVenda: handleNovaVenda,
  };

  const overlayProps = {
    vendaAtual,
    painelClienteAberto,
    setPainelClienteAberto,
    painelVendasAberto,
    setPainelVendasAberto,
    filtroVendas,
    setFiltroVendas,
    filtroStatus,
    setFiltroStatus,
    filtroTemEntrega,
    setFiltroTemEntrega,
    buscaNumeroVenda,
    setBuscaNumeroVenda,
    vendasRecentes,
    reabrirVenda,
    confirmandoRetirada,
    abrirConfirmacaoRetirada,
    confirmarRetirada,
    setConfirmandoRetirada,
    painelOportunidadesAberto,
    setPainelOportunidadesAberto,
    opportunities,
    adicionarOportunidadeAoCarrinho,
    buscarAlternativaOportunidade,
    ignorarOportunidade,
    painelAssistenteAberto,
    setPainelAssistenteAberto,
    mensagensAssistente,
    enviandoAssistente,
    chatAssistenteEndRef,
    inputAssistente,
    setInputAssistente,
    enviarMensagemAssistente,
    carregandoAnalise,
    dadosAnalise,
    enderecoAtual,
    itemEditando,
    loadingCep,
    mostrarAnaliseVenda,
    mostrarCalculadoraRacao,
    mostrarHistoricoCliente,
    mostrarModalAbrirCaixa,
    mostrarModalAdicionarCredito,
    mostrarModalCliente,
    mostrarModalDescontoItem,
    mostrarModalDescontoTotal,
    mostrarModalEndereco,
    mostrarModalPagamento,
    mostrarPendenciasEstoque,
    mostrarVendasEmAberto,
    podeVerMargem,
    racaoIdFechada,
    setTipoDescontoTotal,
    setValorDescontoTotal,
    tipoDescontoTotal,
    valorDescontoTotal,
    onAbrirCaixaSucesso: handleAbrirCaixaSucesso,
    onAnalisarVenda: podeVerMargem ? analisarVendaComFormasPagamento : null,
    onAplicarDescontoTotal: aplicarDescontoTotal,
    onBuscarCep: buscarCepModal,
    onChangeEnderecoAtual: setEnderecoAtual,
    onChangeItemEditando: setItemEditando,
    onClienteCriado: handleClienteCriado,
    onCloseAnalise: () => setMostrarAnaliseVenda(false),
    onCloseCalculadoraRacao: fecharCalculadoraRacao,
    onCloseHistoricoCliente: () => setMostrarHistoricoCliente(false),
    onCloseModalAbrirCaixa: () => setMostrarModalAbrirCaixa(false),
    onCloseModalAdicionarCredito: () => setMostrarModalAdicionarCredito(false),
    onCloseModalCliente: () => setMostrarModalCliente(false),
    onCloseModalDescontoItem: () => setMostrarModalDescontoItem(false),
    onCloseModalDescontoTotal: () => setMostrarModalDescontoTotal(false),
    onCloseModalEndereco: fecharModalEndereco,
    onCloseModalPagamento: () => setMostrarModalPagamento(false),
    onClosePendenciasEstoque: () => setMostrarPendenciasEstoque(false),
    onCloseVendasEmAberto: () => setMostrarVendasEmAberto(false),
    onConfirmarCredito: handleConfirmarCreditoCliente,
    onConfirmarPagamento: handleConfirmarPagamento,
    onPendenciaAdicionada: carregarPendencias,
    onRemoverItemEditando: removerItemEditando,
    onSalvarDescontoItem: salvarDescontoItem,
    onSalvarEndereco: salvarEnderecoNoCliente,
    onVendaAtualizada: handleVendaAtualizadaAposPagamento,
    onVendasEmAbertoSucesso: handleVendasEmAbertoSucesso,
  };

  return {
    driveAlertProps,
    containerStyle,
    mainAreaProps,
    overlayProps,
  };
}
