import React from "react";
import ProdutosFiltrosPanel from "./ProdutosFiltrosPanel";
import ProdutosHeaderActions from "./ProdutosHeaderActions";
import ProdutosTabelaSection from "./ProdutosTabelaSection";

export default function ProdutosMainContent({
  abrirModalColunas,
  categorias,
  copiarTexto,
  editandoPreco,
  filtrarColunas,
  filtros,
  fornecedores,
  getCorEstoque,
  getValidadeMaisProxima,
  handleCancelarEdicaoPreco,
  handleEditarPreco,
  handleExcluir,
  handleFiltroChange,
  handleSalvarPreco,
  handleSelecionar,
  handleSelecionarTodos,
  handleToggleAtivo,
  iniciarTour,
  isProdutoComComposicao,
  itensPorPagina,
  kitsExpandidos,
  linhaProdutoRefs,
  loading,
  marcas,
  menuRelatoriosAberto,
  menuRelatoriosRef,
  navigate,
  novoPreco,
  onChangeItensPorPagina,
  onExcluirSelecionados,
  onGerarRelatorioFiltrado,
  onGerarRelatorioGeral,
  onIrParaPagina,
  onIrParaPrimeiraPagina,
  onIrParaUltimaPagina,
  onOpenEdicaoLote,
  onOpenImportacao,
  onOpenModalRelatorio,
  onPaginaAnterior,
  onProximaPagina,
  onToggleMenuRelatorios,
  paginaAtual,
  paisExpandidos,
  persistirBusca,
  produtos,
  produtosColunas,
  selecionados,
  selecionadosCount,
  setNovoPreco,
  setPersistirBusca,
  toggleKitExpandido,
  togglePaiExpandido,
  totalItens,
  totalPaginas,
}) {
  const colunasVisiveis = produtosColunas.filter(filtrarColunas);

  return (
    <>
      <ProdutosHeaderActions
        abrirModalColunas={abrirModalColunas}
        iniciarTour={iniciarTour}
        menuRelatoriosAberto={menuRelatoriosAberto}
        menuRelatoriosRef={menuRelatoriosRef}
        navigate={navigate}
        onExcluirSelecionados={onExcluirSelecionados}
        onGerarRelatorioFiltrado={onGerarRelatorioFiltrado}
        onGerarRelatorioGeral={onGerarRelatorioGeral}
        onOpenEdicaoLote={onOpenEdicaoLote}
        onOpenImportacao={onOpenImportacao}
        onOpenModalRelatorio={onOpenModalRelatorio}
        onToggleMenuRelatorios={onToggleMenuRelatorios}
        selecionadosCount={selecionadosCount}
      />
      <ProdutosFiltrosPanel
        categorias={categorias}
        filtros={filtros}
        fornecedores={fornecedores}
        handleFiltroChange={handleFiltroChange}
        marcas={marcas}
        persistirBusca={persistirBusca}
        setPersistirBusca={setPersistirBusca}
      />
      <ProdutosTabelaSection
        colunasVisiveis={colunasVisiveis}
        copiarTexto={copiarTexto}
        editandoPreco={editandoPreco}
        getCorEstoque={getCorEstoque}
        getValidadeMaisProxima={getValidadeMaisProxima}
        handleCancelarEdicaoPreco={handleCancelarEdicaoPreco}
        handleEditarPreco={handleEditarPreco}
        handleExcluir={handleExcluir}
        handleSalvarPreco={handleSalvarPreco}
        handleSelecionar={handleSelecionar}
        handleSelecionarTodos={handleSelecionarTodos}
        handleToggleAtivo={handleToggleAtivo}
        isProdutoComComposicao={isProdutoComComposicao}
        itensPorPagina={itensPorPagina}
        kitsExpandidos={kitsExpandidos}
        linhaProdutoRefs={linhaProdutoRefs}
        loading={loading}
        navigate={navigate}
        novoPreco={novoPreco}
        onChangeItensPorPagina={onChangeItensPorPagina}
        onIrParaPagina={onIrParaPagina}
        onIrParaPrimeiraPagina={onIrParaPrimeiraPagina}
        onIrParaUltimaPagina={onIrParaUltimaPagina}
        onPaginaAnterior={onPaginaAnterior}
        onProximaPagina={onProximaPagina}
        paginaAtual={paginaAtual}
        paisExpandidos={paisExpandidos}
        produtos={produtos}
        selecionados={selecionados}
        selecionadosCount={selecionadosCount}
        setNovoPreco={setNovoPreco}
        toggleKitExpandido={toggleKitExpandido}
        togglePaiExpandido={togglePaiExpandido}
        totalItens={totalItens}
        totalPaginas={totalPaginas}
      />
    </>
  );
}
