import { useInternacoesCadastroAcoes } from "./useInternacoesCadastroAcoes";
import { useInternacoesCarregamentoAcoes } from "./useInternacoesCarregamentoAcoes";
import { useInternacoesProcedimentosAcoes } from "./useInternacoesProcedimentosAcoes";

export function useInternacoesAcoes({
  aba,
  agendaForm,
  carregarAgendaProcedimentos,
  consultaIdQuery,
  expandida,
  filtroDataAltaFim,
  filtroDataAltaInicio,
  filtroPessoaHistorico,
  filtroPetHistorico,
  formAlta,
  formEvolucao,
  formFeito,
  formInsumoRapido,
  formNova,
  insumoRapidoSelecionado,
  modalAlta,
  modalEvolucao,
  modalFeito,
  setAba,
  setAgendaForm,
  setAgendaProcedimentos,
  setCarregando,
  setCarregandoHistoricoPet,
  setCentroAba,
  setErro,
  setEvolucoes,
  setExpandida,
  setFiltroPessoaHistorico,
  setFiltroPetHistorico,
  setFormAlta,
  setFormEvolucao,
  setFormFeito,
  setFormInsumoRapido,
  setFormNova,
  setHistoricoPet,
  setInsumoRapidoSelecionado,
  setInternacoes,
  setModalAlta,
  setModalEvolucao,
  setModalFeito,
  setModalHistoricoPet,
  setModalInsumoRapido,
  setModalNova,
  setProcedimentosInternacao,
  setSalvando,
  setTutorNovaSelecionado,
  sugestaoHorario,
}) {
  const carregamentoAcoes = useInternacoesCarregamentoAcoes({
    aba,
    expandida,
    filtroDataAltaFim,
    filtroDataAltaInicio,
    filtroPessoaHistorico,
    filtroPetHistorico,
    setCarregando,
    setCarregandoHistoricoPet,
    setErro,
    setEvolucoes,
    setExpandida,
    setHistoricoPet,
    setInternacoes,
    setModalHistoricoPet,
    setProcedimentosInternacao,
  });

  const cadastroAcoes = useInternacoesCadastroAcoes({
    abrirDetalhe: carregamentoAcoes.abrirDetalhe,
    carregar: carregamentoAcoes.carregar,
    carregarDetalheInternacao: carregamentoAcoes.carregarDetalheInternacao,
    consultaIdQuery,
    formAlta,
    formEvolucao,
    formNova,
    modalAlta,
    modalEvolucao,
    setAba,
    setCentroAba,
    setErro,
    setFiltroPessoaHistorico,
    setFiltroPetHistorico,
    setFormAlta,
    setFormEvolucao,
    setFormNova,
    setModalAlta,
    setModalEvolucao,
    setModalNova,
    setSalvando,
    setTutorNovaSelecionado,
  });

  const procedimentosAcoes = useInternacoesProcedimentosAcoes({
    agendaForm,
    carregarAgendaProcedimentos,
    carregarDetalheInternacao: carregamentoAcoes.carregarDetalheInternacao,
    expandida,
    formFeito,
    formInsumoRapido,
    insumoRapidoSelecionado,
    modalFeito,
    setAgendaForm,
    setAgendaProcedimentos,
    setErro,
    setFormFeito,
    setFormInsumoRapido,
    setInsumoRapidoSelecionado,
    setModalFeito,
    setModalInsumoRapido,
    setSalvando,
    sugestaoHorario,
  });

  return {
    ...carregamentoAcoes,
    ...cadastroAcoes,
    ...procedimentosAcoes,
  };
}
