import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const cartStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  lista: { padding: ESPACO.md, paddingBottom: 0 },
  item: {
    flexDirection: "row",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
    marginBottom: ESPACO.sm,
    alignItems: "center",
    gap: ESPACO.sm,
    ...SOMBRA,
  },
  itemFoto: { width: 55, height: 55, borderRadius: RAIO.sm },
  itemFotoPlaceholder: {
    backgroundColor: CORES.primarioClaro,
    justifyContent: "center",
    alignItems: "center",
  },
  itemInfo: { flex: 1 },
  itemNome: { fontSize: FONTE.normal, fontWeight: "500", color: CORES.texto },
  itemPreco: {
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
    marginTop: 2,
  },
  itemControles: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.xs,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: 6,
  },
  controleBtn: { padding: 6 },
  qtd: {
    fontSize: FONTE.normal,
    fontWeight: "bold",
    color: CORES.texto,
    minWidth: 20,
    textAlign: "center",
  },
  itemSubtotal: {
    fontSize: FONTE.normal,
    fontWeight: "bold",
    color: CORES.primario,
    minWidth: 60,
    textAlign: "right",
  },
  opcaoEntrega: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginTop: ESPACO.sm,
    marginBottom: ESPACO.md,
    ...SOMBRA,
  },
  secaoTitulo: {
    fontSize: FONTE.normal,
    fontWeight: "700",
    color: CORES.texto,
    marginBottom: ESPACO.sm,
  },
  modoRow: { flexDirection: "row", gap: ESPACO.sm, marginBottom: ESPACO.sm },
  modoBotao: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ESPACO.xs,
    paddingVertical: ESPACO.sm + 2,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
  },
  modoBotaoAtivo: {
    backgroundColor: CORES.primario,
    borderColor: CORES.primario,
  },
  modoTexto: { fontSize: FONTE.pequena, fontWeight: "600", color: CORES.texto },
  modoTextoAtivo: { color: "#fff" },
  subSecao: { marginTop: ESPACO.sm },
  subSecaoTitulo: {
    fontSize: FONTE.pequena,
    fontWeight: "600",
    color: CORES.textoSecundario,
    marginBottom: ESPACO.xs,
  },
  opcaoBotao: {
    paddingVertical: ESPACO.sm,
    paddingHorizontal: ESPACO.md,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    marginBottom: ESPACO.xs,
  },
  opcaoBotaoAtivo: {
    borderColor: CORES.primario,
    backgroundColor: CORES.primarioClaro,
  },
  opcaoTexto: { fontSize: FONTE.normal, color: CORES.texto },
  opcaoTextoAtivo: { color: CORES.primario, fontWeight: "600" },
  aviso: {
    backgroundColor: "#FFF7ED",
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
    borderWidth: 1,
    borderColor: "#FED7AA",
    marginTop: ESPACO.xs,
  },
  avisoTexto: { fontSize: FONTE.pequena, color: "#92400E" },
  campo: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.xs + 4,
    fontSize: FONTE.normal,
    color: CORES.texto,
    backgroundColor: CORES.fundo,
    marginBottom: ESPACO.xs,
  },
  campoRow: { flexDirection: "row", gap: ESPACO.xs },
  enderecoSalvoTexto: {
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
    marginTop: 4,
  },
  btnEditar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: ESPACO.xs,
    alignSelf: "flex-end",
  },
  btnEditarTexto: { fontSize: FONTE.pequena, color: CORES.primario },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: ESPACO.lg,
    borderBottomWidth: 1,
    borderBottomColor: CORES.borda,
    backgroundColor: CORES.superficie,
  },
  modalTitulo: {
    fontSize: FONTE.grande,
    fontWeight: "bold",
    color: CORES.texto,
  },
  modalConteudo: { padding: ESPACO.lg },
  modalLabel: {
    fontSize: FONTE.pequena,
    fontWeight: "600",
    color: CORES.textoSecundario,
    marginBottom: 4,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm + 2,
    fontSize: FONTE.normal,
    color: CORES.texto,
    backgroundColor: CORES.fundo,
    marginBottom: ESPACO.md,
  },
  modalRow: { flexDirection: "row", marginBottom: 0 },
  cepRow: { flexDirection: "row", alignItems: "center", marginBottom: 0 },
  modalBotao: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.md,
    alignItems: "center",
    marginTop: ESPACO.lg,
  },
  modalBotaoTexto: { color: "#fff", fontSize: FONTE.media, fontWeight: "bold" },
  rodape: {
    backgroundColor: CORES.superficie,
    padding: ESPACO.lg,
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    ...SOMBRA,
  },
  resumo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: ESPACO.md,
  },
  resumoLabel: { fontSize: FONTE.media, color: CORES.textoSecundario },
  resumoTotal: {
    fontSize: FONTE.titulo,
    fontWeight: "bold",
    color: CORES.texto,
  },
  botaoFinalizar: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.md,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: ESPACO.sm,
  },
  botaoDesativado: { opacity: 0.7 },
  botaoFinalizarTexto: {
    color: "#fff",
    fontSize: FONTE.media,
    fontWeight: "bold",
  },
  btnLimpar: { alignSelf: "flex-end", marginBottom: ESPACO.sm },
  btnLimparTexto: { color: CORES.erro, fontSize: FONTE.pequena },
  vazio: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: ESPACO.xl,
  },
  vazioEmoji: { fontSize: 60, marginBottom: ESPACO.md },
  vazioTitulo: {
    fontSize: FONTE.titulo,
    fontWeight: "bold",
    color: CORES.texto,
    marginBottom: ESPACO.sm,
  },
  vazioTexto: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    textAlign: "center",
    marginBottom: ESPACO.xl,
  },
  botaoScanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.xl,
    paddingVertical: ESPACO.md,
    gap: ESPACO.sm,
    marginBottom: ESPACO.sm,
  },
  botaoScannerTexto: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: FONTE.normal,
  },
  botaoCatalogo: { padding: ESPACO.sm },
  botaoCatalogoTexto: { color: CORES.primario, fontSize: FONTE.normal },
  pagamentoAviso: {
    fontSize: FONTE.pequena,
    color: "#92400E",
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
    borderWidth: 1,
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
    marginBottom: ESPACO.sm,
  },
  pagBotao: {
    flex: 1,
    alignItems: "center",
    paddingVertical: ESPACO.sm + 2,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
  },
  pagBotaoAtivo: {
    backgroundColor: CORES.primario,
    borderColor: CORES.primario,
  },
  pagBotaoIcon: { fontSize: 18, marginBottom: 2 },
  pagBotaoTexto: {
    fontSize: FONTE.pequena,
    fontWeight: "600",
    color: CORES.texto,
  },
  pagBotaoTextoAtivo: { color: "#fff" },
  pagLabel: {
    fontSize: FONTE.pequena,
    fontWeight: "600",
    color: CORES.textoSecundario,
    marginBottom: 4,
  },
  bandeiraBotao: {
    flex: 1,
    alignItems: "center",
    paddingVertical: ESPACO.xs + 4,
    borderRadius: RAIO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
  },
  bandeiraBotaoAtivo: {
    backgroundColor: CORES.primarioClaro,
    borderColor: CORES.primario,
  },
  bandeiraTexto: { fontSize: FONTE.pequena, color: CORES.texto },
  bandeiraTextoAtivo: { color: CORES.primario, fontWeight: "700" },
});
