from __future__ import annotations

SEVERITY_RANK = {
    "info": 0,
    "low": 1,
    "medium": 2,
    "high": 3,
    "critical": 4,
}

FINAL_STATUS = {"confirmado", "cancelado", "expirado"}
OPEN_INCIDENT_STATUSES = {"open", "ignored"}
PEDIDO_MONITORED_INCIDENT_CODES = {
    "PEDIDO_SEM_ITENS",
    "SKU_SEM_PRODUTO_LOCAL",
    "RESERVA_ATIVA_EM_PEDIDO_FINALIZADO",
    "ITEM_NAO_CONFIRMADO_EM_PEDIDO_CONFIRMADO",
    "ITEM_VENDIDO_EM_PEDIDO_ABERTO",
    "NF_AUTORIZADA_PEDIDO_NAO_CONFIRMADO",
    "NF_ENCONTRADA_SEM_VINCULO_NO_PEDIDO",
    "NF_ENCONTRADA_COM_DIVERGENCIA_NO_PEDIDO",
    "NF_MULTIPLA_ENCONTRADA_POR_PEDIDO_LOJA",
    "PEDIDO_CONFIRMADO_SEM_BAIXA_ESTOQUE",
    "SKU_MAPEADO_POR_CODIGO_BARRAS",
}
EXTRA_MONITORED_INCIDENT_CODES = {
    "PEDIDO_DUPLICADO_POR_NUMERO_LOJA",
}
MONITORED_INCIDENT_CODES = (
    PEDIDO_MONITORED_INCIDENT_CODES | EXTRA_MONITORED_INCIDENT_CODES
)

__all__ = [
    "EXTRA_MONITORED_INCIDENT_CODES",
    "FINAL_STATUS",
    "MONITORED_INCIDENT_CODES",
    "OPEN_INCIDENT_STATUSES",
    "PEDIDO_MONITORED_INCIDENT_CODES",
    "SEVERITY_RANK",
]
