"""Read the safe TLS certificate snapshot generated by the host probe."""

from datetime import datetime, timezone
import json
import os
from typing import Any

TLS_STATUS_PATH = os.getenv(
    "OPS_TLS_STATUS_PATH", os.path.join(os.getcwd(), "logs", "tls_status.json")
)


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except ValueError:
        return default


TLS_STATUS_MAX_AGE_HOURS = _env_float("OPS_TLS_STATUS_MAX_AGE_HOURS", 2)


def _parse_datetime(value: Any) -> datetime | None:
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except (TypeError, ValueError):
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def summarize_tls_status(*, now: datetime | None = None) -> dict[str, Any]:
    current_time = now or datetime.now(timezone.utc)
    if current_time.tzinfo is None:
        current_time = current_time.replace(tzinfo=timezone.utc)

    try:
        with open(TLS_STATUS_PATH, encoding="utf-8") as status_file:
            payload = json.load(status_file)
    except (OSError, json.JSONDecodeError):
        return {"status": "unavailable", "certificates": [], "age_hours": None}

    if not isinstance(payload, dict):
        return {"status": "unavailable", "certificates": [], "age_hours": None}

    generated_at = _parse_datetime(payload.get("generated_at"))
    if not generated_at or not isinstance(payload.get("certificates"), list):
        return {"status": "unavailable", "certificates": [], "age_hours": None}

    age_hours = max(0.0, (current_time - generated_at).total_seconds() / 3600)
    status = str(payload.get("status") or "unavailable")
    if age_hours > TLS_STATUS_MAX_AGE_HOURS and status == "healthy":
        status = "stale"

    certificates = []
    for item in payload["certificates"]:
        if not isinstance(item, dict):
            continue
        certificates.append(
            {
                "domain": str(item.get("domain") or ""),
                "status": str(item.get("status") or "unavailable"),
                "expires_at": item.get("expires_at"),
                "days_remaining": item.get("days_remaining"),
                "error_type": item.get("error_type"),
            }
        )

    return {
        "status": status,
        "generated_at": payload.get("generated_at"),
        "age_hours": round(age_hours, 2),
        "warning_days": payload.get("warning_days"),
        "critical_days": payload.get("critical_days"),
        "certificates": certificates,
    }
