"""Campos cadastrais revisaveis na fusao de produtos."""

CAMPOS_CADASTRAIS_FUSAO: list[tuple[str, str]] = [
    ("codigo", "SKU"),
    ("nome", "Nome"),
    ("tipo", "Tipo"),
    ("tipo_produto", "Tipo do produto"),
    ("is_parent", "Produto pai"),
    ("is_sellable", "Vendavel"),
    ("produto_pai_id", "Produto pai vinculado"),
    ("variation_attributes", "Atributos da variacao"),
    ("variation_signature", "Assinatura da variacao"),
    ("tipo_kit", "Tipo de kit"),
    ("descricao_curta", "Descricao curta"),
    ("descricao_completa", "Descricao completa"),
    ("tags", "Tags"),
    ("codigo_barras", "Codigo de barras"),
    ("codigos_barras_alternativos", "Codigos de barras alternativos"),
    ("categoria_id", "Categoria"),
    ("subcategoria", "Subcategoria"),
    ("marca_id", "Marca"),
    ("fornecedor_id", "Fornecedor principal"),
    ("departamento_id", "Departamento"),
    ("preco_custo", "Preco de custo"),
    ("preco_venda", "Preco de venda"),
    ("preco_promocional", "Preco promocional ERP"),
    ("promocao_inicio", "Inicio da promocao ERP"),
    ("promocao_fim", "Fim da promocao ERP"),
    ("promocao_ativa", "Promocao ativa"),
    ("preco_ecommerce", "Preco e-commerce"),
    ("preco_ecommerce_promo", "Preco promocional e-commerce"),
    ("preco_ecommerce_promo_inicio", "Inicio promo e-commerce"),
    ("preco_ecommerce_promo_fim", "Fim promo e-commerce"),
    ("preco_app", "Preco app"),
    ("preco_app_promo", "Preco promocional app"),
    ("preco_app_promo_inicio", "Inicio promo app"),
    ("preco_app_promo_fim", "Fim promo app"),
    ("anunciar_ecommerce", "Anunciar no e-commerce"),
    ("anunciar_app", "Anunciar no app"),
    ("estoque_minimo", "Estoque minimo"),
    ("estoque_maximo", "Estoque maximo"),
    ("localizacao", "Localizacao"),
    ("crossdocking_dias", "Crossdocking"),
    ("controle_lote", "Controle de lote"),
    ("unidade", "Unidade"),
    ("condicao", "Condicao"),
    ("e_granel", "Produto granel"),
    ("participa_sugestao_compra", "Participa da sugestao de compra"),
    ("peso_liquido", "Peso liquido"),
    ("peso_bruto", "Peso bruto"),
    ("largura", "Largura"),
    ("altura", "Altura"),
    ("profundidade", "Profundidade"),
    ("volume", "Volume"),
    ("itens_por_caixa", "Itens por caixa"),
    ("frete_gratis", "Frete gratis"),
    ("producao", "Producao"),
    ("ncm", "NCM"),
    ("cest", "CEST"),
    ("gtin_ean", "GTIN/EAN"),
    ("gtin_ean_tributario", "GTIN/EAN tributario"),
    ("origem", "Origem fiscal"),
    ("perfil_tributario", "Perfil tributario"),
    ("forma_aquisicao", "Forma de aquisicao"),
    ("tipo_item", "Tipo do item"),
    ("percentual_tributos", "Percentual de tributos"),
    ("icms_base_retencao", "ICMS base retencao"),
    ("icms_valor_retencao", "ICMS valor retencao"),
    ("icms_valor_proprio", "ICMS valor proprio"),
    ("ipi_codigo_excecao", "IPI codigo excecao"),
    ("pis_valor_fixo", "PIS valor fixo"),
    ("cofins_valor_fixo", "COFINS valor fixo"),
    ("cfop", "CFOP"),
    ("aliquota_icms", "Aliquota ICMS"),
    ("aliquota_pis", "Aliquota PIS"),
    ("aliquota_cofins", "Aliquota COFINS"),
    ("informacoes_adicionais_nf", "Informacoes adicionais NF"),
    ("comissao_padrao", "Comissao padrao"),
    ("limite_desconto", "Limite de desconto"),
    ("data_validade", "Data de validade"),
    ("tem_recorrencia", "Tem recorrencia"),
    ("tipo_recorrencia", "Tipo de recorrencia"),
    ("intervalo_dias", "Intervalo em dias"),
    ("numero_doses", "Numero de doses"),
    ("observacoes_recorrencia", "Observacoes de recorrencia"),
    ("especie_compativel", "Especie compativel"),
    ("classificacao_racao", "Classificacao racao"),
    ("peso_embalagem", "Peso da embalagem"),
    ("tabela_nutricional", "Tabela nutricional"),
    ("categoria_racao", "Categoria da racao"),
    ("especies_indicadas", "Especies indicadas"),
    ("tabela_consumo", "Tabela de consumo"),
    ("porte_animal", "Porte animal"),
    ("fase_publico", "Fase/publico"),
    ("tipo_tratamento", "Tipo de tratamento"),
    ("sabor_proteina", "Sabor/proteina"),
    ("auto_classificar_nome", "Auto classificar nome"),
    ("linha_racao_id", "Linha da racao"),
    ("porte_animal_id", "Porte animal cadastrado"),
    ("fase_publico_id", "Fase/publico cadastrado"),
    ("tipo_tratamento_id", "Tratamento cadastrado"),
    ("sabor_proteina_id", "Sabor/proteina cadastrado"),
    ("apresentacao_peso_id", "Apresentacao/peso"),
    ("imagem_principal", "Imagem principal"),
]
