from __future__ import annotations

from app.services.tenant_onboarding_catalog_templates import CATALOG_TEMPLATE_ITEMS
from app.services.tenant_onboarding_financial_templates import FINANCIAL_TEMPLATE_ITEMS
from app.services.tenant_onboarding_template_contracts import (
    BASE_RATEIO_DB_LABELS,
    DEFAULT_BUNDLE_CODE,
    DEFAULT_BUNDLE_VERSION,
    ESCOPO_RATEIO_DB_LABELS,
    INSERT_TABLE_PATTERN,
    ITEM_INSTALL_TARGET_TABLES,
    REQUIRED_ONBOARDING_SECTIONS,
    REQUIRED_ONBOARDING_TABLES,
    REQUIRED_TEMPLATE_ITEM_TYPES,
    TEMPLATE_INFRA_TABLES,
    TIPO_CUSTO_DB_LABELS,
    template_item,
)


__all__ = (
    "BASE_RATEIO_DB_LABELS",
    "BASE_TEMPLATE_ITEMS",
    "BUILTIN_TEMPLATE_ITEMS",
    "DEFAULT_BUNDLE_CODE",
    "DEFAULT_BUNDLE_VERSION",
    "ESCOPO_RATEIO_DB_LABELS",
    "INSERT_TABLE_PATTERN",
    "ITEM_INSTALL_TARGET_TABLES",
    "REQUIRED_ONBOARDING_SECTIONS",
    "REQUIRED_ONBOARDING_TABLES",
    "REQUIRED_TEMPLATE_ITEM_TYPES",
    "TEMPLATE_INFRA_TABLES",
    "TIPO_CUSTO_DB_LABELS",
)


NAME_RECEITAS_VENDAS = "Receitas de Vendas"
NAME_TAXAS_CARTAO = "Taxas de Cartao"
PRODUCT_REFERENCE_DESCRIPTION = "Produto de referencia para importacao opcional."

_template_item = template_item


BASE_TEMPLATE_ITEMS: list[dict[str, object]] = [
    _template_item(
        "payment_method",
        "payment_cash",
        "Dinheiro",
        {
            "nome": "Dinheiro",
            "tipo": "dinheiro",
            "taxa_percentual": 0,
            "taxa_fixa": 0,
            "prazo_dias": 0,
            "prazo_recebimento": 0,
            "gera_contas_receber": False,
            "split_parcelas": False,
            "requer_nsu": False,
            "ativo": True,
            "permite_parcelamento": False,
            "max_parcelas": 1,
            "parcelas_maximas": 1,
            "icone": "cash",
            "cor": "#22C55E",
        },
        10,
    ),
    _template_item(
        "payment_method",
        "payment_pix",
        "PIX",
        {
            "nome": "PIX",
            "tipo": "pix",
            "taxa_percentual": 0,
            "taxa_fixa": 0,
            "prazo_dias": 0,
            "prazo_recebimento": 0,
            "operadora": "PIX",
            "gera_contas_receber": False,
            "split_parcelas": False,
            "requer_nsu": False,
            "ativo": True,
            "permite_parcelamento": False,
            "max_parcelas": 1,
            "parcelas_maximas": 1,
            "icone": "pix",
            "cor": "#0EA5E9",
        },
        20,
    ),
    _template_item(
        "payment_method",
        "payment_debit",
        "Cartao de debito",
        {
            "nome": "Cartao de debito",
            "tipo": "cartao_debito",
            "taxa_percentual": 2,
            "taxa_fixa": 0,
            "prazo_dias": 1,
            "prazo_recebimento": 1,
            "operadora": None,
            "gera_contas_receber": True,
            "split_parcelas": False,
            "requer_nsu": True,
            "tipo_cartao": "debito",
            "ativo": True,
            "permite_parcelamento": False,
            "max_parcelas": 1,
            "parcelas_maximas": 1,
            "icone": "card",
            "cor": "#3B82F6",
        },
        30,
    ),
    _template_item(
        "payment_method",
        "payment_credit",
        "Cartao de credito",
        {
            "nome": "Cartao de credito",
            "tipo": "cartao_credito",
            "taxa_percentual": 3,
            "taxa_fixa": 0,
            "prazo_dias": 30,
            "prazo_recebimento": 30,
            "operadora": None,
            "gera_contas_receber": True,
            "split_parcelas": True,
            "requer_nsu": True,
            "tipo_cartao": "credito",
            "ativo": True,
            "permite_parcelamento": True,
            "max_parcelas": 12,
            "parcelas_maximas": 12,
            "icone": "card",
            "cor": "#8B5CF6",
        },
        40,
    ),
    _template_item(
        "dre_category",
        "dre_receitas",
        NAME_RECEITAS_VENDAS,
        {
            "nome": NAME_RECEITAS_VENDAS,
            "ordem": 1,
            "natureza": "receita",
            "ativo": True,
        },
        100,
    ),
    _template_item(
        "dre_category",
        "dre_cmv",
        "Custo das Mercadorias Vendidas",
        {
            "nome": "Custo das Mercadorias Vendidas",
            "ordem": 2,
            "natureza": "custo",
            "ativo": True,
        },
        200,
    ),
    _template_item(
        "dre_category",
        "dre_despesas_operacionais",
        "Despesas Operacionais",
        {
            "nome": "Despesas Operacionais",
            "ordem": 3,
            "natureza": "despesa",
            "ativo": True,
        },
        300,
    ),
    _template_item(
        "dre_subcategory",
        "dre_vendas_produtos",
        "Vendas de Produtos",
        {
            "categoria_code": "dre_receitas",
            "nome": "Vendas de Produtos",
            "tipo_custo": "direto",
            "base_rateio": None,
            "escopo_rateio": "ambos",
            "ativo": True,
        },
        110,
    ),
    _template_item(
        "dre_subcategory",
        "dre_vendas_servicos",
        "Vendas de Servicos",
        {
            "categoria_code": "dre_receitas",
            "nome": "Vendas de Servicos",
            "tipo_custo": "direto",
            "base_rateio": None,
            "escopo_rateio": "ambos",
            "ativo": True,
        },
        120,
    ),
    _template_item(
        "dre_subcategory",
        "dre_cmv_produtos",
        "CMV - Produtos",
        {
            "categoria_code": "dre_cmv",
            "nome": "CMV - Produtos",
            "tipo_custo": "direto",
            "base_rateio": None,
            "escopo_rateio": "ambos",
            "ativo": True,
        },
        210,
    ),
    _template_item(
        "dre_subcategory",
        "dre_taxas_cartao",
        NAME_TAXAS_CARTAO,
        {
            "categoria_code": "dre_despesas_operacionais",
            "nome": NAME_TAXAS_CARTAO,
            "tipo_custo": "direto",
            "base_rateio": None,
            "escopo_rateio": "ambos",
            "ativo": True,
        },
        310,
    ),
    _template_item(
        "financial_category",
        "fin_receitas_vendas",
        NAME_RECEITAS_VENDAS,
        {
            "nome": NAME_RECEITAS_VENDAS,
            "tipo": "receita",
            "cor": "#16A34A",
            "icone": "trending-up",
            "descricao": "Receitas operacionais de produtos e servicos.",
            "dre_subcategory_code": "dre_vendas_produtos",
            "tipo_custo": "variavel",
            "ativo": True,
        },
        400,
    ),
    _template_item(
        "financial_category",
        "fin_cmv",
        "CMV",
        {
            "nome": "CMV",
            "tipo": "despesa",
            "cor": "#F97316",
            "icone": "package",
            "descricao": "Custo das mercadorias vendidas.",
            "dre_subcategory_code": "dre_cmv_produtos",
            "tipo_custo": "variavel",
            "ativo": True,
        },
        410,
    ),
    _template_item(
        "expense_type",
        "expense_cmv",
        "CMV",
        {
            "nome": "CMV",
            "e_custo_fixo": False,
            "dre_subcategory_code": "dre_cmv_produtos",
            "ativo": True,
        },
        450,
    ),
    _template_item(
        "expense_type",
        "expense_taxas_cartao",
        NAME_TAXAS_CARTAO,
        {
            "nome": NAME_TAXAS_CARTAO,
            "e_custo_fixo": False,
            "dre_subcategory_code": "dre_taxas_cartao",
            "ativo": True,
        },
        460,
    ),
    _template_item(
        "product_department",
        "dept_produtos",
        "Produtos",
        {
            "nome": "Produtos",
            "descricao": "Produtos comercializados pela loja.",
            "ativo": True,
        },
        500,
    ),
    _template_item(
        "product_category",
        "cat_pet_food",
        "Pet Food",
        {
            "nome": "Pet Food",
            "departamento_code": "dept_produtos",
            "descricao": "Racoes, alimentos e petiscos.",
            "icone": "package",
            "cor": "#2563EB",
            "ordem": 1,
            "ativo": True,
        },
        510,
    ),
    _template_item(
        "product_category",
        "cat_acessorios",
        "Acessorios",
        {
            "nome": "Acessorios",
            "departamento_code": "dept_produtos",
            "descricao": "Acessorios, brinquedos e itens de uso geral.",
            "icone": "shopping-bag",
            "cor": "#9333EA",
            "ordem": 2,
            "ativo": True,
        },
        520,
    ),
    _template_item(
        "product_reference",
        "prod_ref_racao_adulto_1kg",
        "Referencia Racao Adulto 1kg",
        {
            "codigo": "TPL-RACAO-ADULTO-1KG",
            "nome": "Referencia Racao Adulto 1kg",
            "categoria_code": "cat_pet_food",
            "departamento_code": "dept_produtos",
            "tipo": "produto",
            "descricao_curta": PRODUCT_REFERENCE_DESCRIPTION,
            "preco_custo": 0,
            "preco_venda": 0,
            "estoque_atual": 0,
            "estoque_minimo": 0,
            "estoque_maximo": 0,
            "unidade": "UN",
            "condicao": "novo",
            "ativo": False,
            "situacao": False,
        },
        900,
    ),
    _template_item(
        "product_reference",
        "prod_ref_petisco_100g",
        "Referencia Petisco 100g",
        {
            "codigo": "TPL-PETISCO-100G",
            "nome": "Referencia Petisco 100g",
            "categoria_code": "cat_pet_food",
            "departamento_code": "dept_produtos",
            "tipo": "produto",
            "descricao_curta": PRODUCT_REFERENCE_DESCRIPTION,
            "preco_custo": 0,
            "preco_venda": 0,
            "estoque_atual": 0,
            "estoque_minimo": 0,
            "estoque_maximo": 0,
            "unidade": "UN",
            "condicao": "novo",
            "ativo": False,
            "situacao": False,
        },
        910,
    ),
    _template_item(
        "product_reference",
        "prod_ref_brinquedo",
        "Referencia Brinquedo",
        {
            "codigo": "TPL-BRINQUEDO",
            "nome": "Referencia Brinquedo",
            "categoria_code": "cat_acessorios",
            "departamento_code": "dept_produtos",
            "tipo": "produto",
            "descricao_curta": PRODUCT_REFERENCE_DESCRIPTION,
            "preco_custo": 0,
            "preco_venda": 0,
            "estoque_atual": 0,
            "estoque_minimo": 0,
            "estoque_maximo": 0,
            "unidade": "UN",
            "condicao": "novo",
            "ativo": False,
            "situacao": False,
        },
        920,
    ),
]


BUILTIN_TEMPLATE_ITEMS = [
    *BASE_TEMPLATE_ITEMS,
    *FINANCIAL_TEMPLATE_ITEMS,
    *CATALOG_TEMPLATE_ITEMS,
]
