import { useState } from "react";
import useTransferenciaHistoricoController from "./useTransferenciaHistoricoController";
import useTransferenciaLancamentoController from "./useTransferenciaLancamentoController";

export default function useEstoqueTransferenciaParceiroController() {
  const [abaAtiva, setAbaAtiva] = useState("lancamento");
  const lancamento = useTransferenciaLancamentoController({ setAbaAtiva });
  const historico = useTransferenciaHistoricoController({
    parceiroSelecionado: lancamento.parceiroSelecionado,
    transferenciaEditando: lancamento.transferenciaEditando,
    limparLancamentoAtual: lancamento.limparLancamentoAtual,
    setAbaAtiva,
  });

  const modoEdicao = Boolean(lancamento.transferenciaEditando?.conta_receber_id);

  return {
    cupomTransferencia: historico.cupomTransferencia,
    modalDocumentoTransferenciaProps: {
      modal: historico.modalDocumentoTransferencia,
      colunasSelecionadas: historico.colunasDocumentoTransferencia,
      onChangeColunas: historico.setColunasDocumentoTransferencia,
      onClose: historico.fecharModalDocumentoTransferencia,
      onConfirmar: () => void historico.confirmarDocumentoTransferencia(),
      loading: historico.loadingDocumentoTransferencia,
    },
    headerProps: {
      modoEdicao,
      transferenciaEditando: lancamento.transferenciaEditando,
      onCancelarEdicao: lancamento.cancelarEdicaoTransferencia,
      abaAtiva,
      onChangeAba: setAbaAtiva,
      totalRegistrosHistorico: historico.historico.totais.total_registros,
    },
    abaAtiva,
    lancamentoProps: {
      parceiroRef: lancamento.parceiroRef,
      parceiroSelecionado: lancamento.parceiroSelecionado,
      limparParceiro: lancamento.limparParceiro,
      buscaParceiro: lancamento.buscaParceiro,
      setBuscaParceiro: lancamento.setBuscaParceiro,
      setDropdownParceiroAberto: lancamento.setDropdownParceiroAberto,
      dropdownParceiroAberto: lancamento.dropdownParceiroAberto,
      loadingParceiros: lancamento.loadingParceiros,
      sugestoesParceiros: lancamento.sugestoesParceiros,
      selecionarParceiro: lancamento.selecionarParceiro,
      form: lancamento.form,
      atualizarCampo: lancamento.atualizarCampo,
      produtoRef: lancamento.produtoRef,
      produtoInputRef: lancamento.produtoInputRef,
      buscaProduto: lancamento.buscaProduto,
      setBuscaProduto: lancamento.setBuscaProduto,
      setDropdownProdutoAberto: lancamento.setDropdownProdutoAberto,
      dropdownProdutoAberto: lancamento.dropdownProdutoAberto,
      adicionarProdutoPorBuscaAtual: lancamento.adicionarProdutoPorBuscaAtual,
      loadingProdutos: lancamento.loadingProdutos,
      sugestoesProdutos: lancamento.sugestoesProdutos,
      adicionarProduto: lancamento.adicionarProduto,
      itensRef: lancamento.itensRef,
      itens: lancamento.itens,
      totalQuantidade: lancamento.totalQuantidade,
      totalRessarcimento: lancamento.totalRessarcimento,
      registrarTransferencia: () =>
        void lancamento.registrarTransferencia(historico.recarregarPrimeiraPagina),
      salvando: lancamento.salvando,
      modoEdicao,
      itensSemValor: lancamento.itensSemValor,
      atualizarCustoUnitario: lancamento.atualizarCustoUnitario,
      atualizarQuantidade: lancamento.atualizarQuantidade,
      atualizarTotalItem: lancamento.atualizarTotalItem,
      removerItem: lancamento.removerItem,
    },
    historicoFiltersProps: {
      parceiroSelecionado: lancamento.parceiroSelecionado,
      onUsarParceiroAtual: historico.usarParceiroAtualNoHistorico,
      onAtualizarHistorico: () => void historico.recarregarPaginaAtual(),
      totais: historico.historico.totais,
      filtros: historico.filtrosHistoricoForm,
      atualizarFiltro: historico.atualizarFiltroHistorico,
      pessoaSelecionada: historico.pessoaHistoricoSelecionada,
      sugestoesPessoas: historico.sugestoesPessoasHistorico,
      loadingPessoas: historico.loadingPessoasHistorico,
      onAtualizarBuscaPessoa: historico.atualizarBuscaPessoaHistorico,
      onSelecionarPessoa: historico.selecionarPessoaHistorico,
      aplicarPeriodoRapido: historico.aplicarPeriodoRapidoHistorico,
      limparFiltros: historico.limparFiltrosHistorico,
      onSubmit: historico.aplicarFiltrosHistorico,
    },
    historicoResultsProps: {
      loadingHistorico: historico.loadingHistorico,
      historico: historico.historico,
      selecionadosHistorico: historico.selecionadosHistorico,
      todosPaginaSelecionados: historico.todosPaginaSelecionados,
      gerandoPdfConsolidado: historico.gerandoPdfConsolidado,
      historicoExpandidoIds: historico.historicoExpandidoIds,
      baixaAbertaId: historico.baixaAbertaId,
      formBaixa: historico.formBaixa,
      setFormBaixa: historico.setFormBaixa,
      loadingFormasPagamento: historico.loadingFormasPagamento,
      formasPagamento: historico.formasPagamento,
      totalCompensadoBaixa: historico.totalCompensadoBaixa,
      loadingContasPagarCompensacao: historico.loadingContasPagarCompensacao,
      contasPagarCompensacao: historico.contasPagarCompensacao,
      contaRecebendo: historico.contaRecebendo,
      contaGerandoPdf: historico.contaGerandoPdf,
      contaEnviandoEmail: historico.contaEnviandoEmail,
      contaExcluindo: historico.contaExcluindo,
      totalPaginasHistorico: historico.totalPaginasHistorico,
      paginaHistorico: historico.paginaHistorico,
      onAlternarSelecaoPaginaHistorico: historico.alternarSelecaoPaginaHistorico,
      onLimparSelecaoHistorico: historico.limparSelecaoHistorico,
      onAbrirModalDocumentoTransferencia: historico.abrirModalDocumentoTransferencia,
      onAlternarSelecaoHistorico: historico.alternarSelecaoHistorico,
      onAlternarExpansaoHistorico: historico.alternarExpansaoHistorico,
      onAbrirBaixaTransferencia: historico.abrirBaixaTransferencia,
      onIniciarEdicaoTransferencia: lancamento.iniciarEdicaoTransferencia,
      onExcluirTransferencia: historico.excluirTransferencia,
      onPreencherCompensacaoAutomatica: historico.preencherCompensacaoAutomatica,
      onLimparCompensacoesBaixa: historico.limparCompensacoesBaixa,
      onAtualizarValorCompensacao: historico.atualizarValorCompensacao,
      onFecharBaixaTransferencia: historico.fecharBaixaTransferencia,
      onRegistrarBaixaTransferencia: historico.registrarBaixaTransferencia,
      onSetPaginaHistorico: historico.setPaginaHistorico,
    },
  };
}
