"""convert vendas.id to IDENTITY ALWAYS

Revision ID: 20260126_identity
Revises: 
Create Date: 2026-01-26 15:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260126_identity'
down_revision = '35ed26f476f0'  # Última migration conhecida
branch_labels = None
depends_on = None


def upgrade():
    """
    Converte a coluna vendas.id para IDENTITY GENERATED ALWAYS
    """
    # 1. Remove DEFAULT anterior (se existir) antes de adicionar IDENTITY
    op.execute("""
        ALTER TABLE vendas
        ALTER COLUMN id DROP DEFAULT;
    """)
    
    # 2. Adiciona IDENTITY GENERATED ALWAYS
    op.execute("""
        ALTER TABLE vendas
        ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
    """)
    
    # 3. Sincroniza a sequence com o maior ID existente
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('vendas', 'id'),
            COALESCE((SELECT MAX(id) FROM vendas), 1),
            true
        );
    """)


def downgrade():
    """
    Reverte para IDENTITY GENERATED BY DEFAULT
    """
    op.execute("""
        ALTER TABLE vendas
        ALTER COLUMN id DROP IDENTITY IF EXISTS;
    """)
    
    op.execute("""
        ALTER TABLE vendas
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    """)
