import useConsultaFinalizacaoActions from "./useConsultaFinalizacaoActions";
import useConsultaFluxosActions from "./useConsultaFluxosActions";
import useConsultaRascunhoActions from "./useConsultaRascunhoActions";

export default function useConsultaFormActions({
  agendamentoIdQuery,
  carregarTimelineConsulta,
  consultaIdAtual,
  contextoConsultaParams,
  etapa,
  form,
  insumoRapidoForm,
  insumoRapidoSelecionado,
  navigate,
  novoExameArquivo,
  novoExameForm,
  pets,
  selecionarPetCriado,
  setConsultaIdAtual,
  setErro,
  setEtapa,
  setFinalizado,
  setInsumoRapidoForm,
  setInsumoRapidoSelecionado,
  setModalInsumoAberto,
  setModalNovoExameAberto,
  setModalNovoPetAberto,
  setNovoExameArquivo,
  setNovoExameForm,
  setRefreshExamesToken,
  setSalvando,
  setSalvandoInsumoRapido,
  setSalvandoNovoExame,
  setSucesso,
  tipoQuery,
  tutorSelecionado,
}) {
  const rascunhoAcoes = useConsultaRascunhoActions({
    agendamentoIdQuery,
    consultaIdAtual,
    etapa,
    form,
    navigate,
    pets,
    selecionarPetCriado,
    setConsultaIdAtual,
    setErro,
    setEtapa,
    setModalNovoPetAberto,
    setSalvando,
    setSucesso,
    tipoQuery,
    tutorSelecionado,
  });

  const finalizacaoAcoes = useConsultaFinalizacaoActions({
    carregarTimelineConsulta,
    consultaIdAtual,
    form,
    setErro,
    setFinalizado,
    setSalvando,
    setSucesso,
  });

  const fluxosAcoes = useConsultaFluxosActions({
    agendamentoIdQuery,
    carregarTimelineConsulta,
    consultaIdAtual,
    contextoConsultaParams,
    form,
    insumoRapidoForm,
    insumoRapidoSelecionado,
    navigate,
    novoExameArquivo,
    novoExameForm,
    setErro,
    setEtapa,
    setInsumoRapidoForm,
    setInsumoRapidoSelecionado,
    setModalInsumoAberto,
    setModalNovoExameAberto,
    setNovoExameArquivo,
    setNovoExameForm,
    setRefreshExamesToken,
    setSalvandoInsumoRapido,
    setSalvandoNovoExame,
    setSucesso,
  });

  return {
    ...rascunhoAcoes,
    ...finalizacaoAcoes,
    ...fluxosAcoes,
  };
}
