import EstoqueLancamentoModal from "./EstoqueLancamentoModal";
import GranelLancamentoModal from "./GranelLancamentoModal";
import ReservasAtivasModal from "./ReservasAtivasModal";

export default function MovimentacoesProdutoModals({
  abrirPedidoReservado,
  atualizarPrecoGranel,
  baseMargemGranel,
  baseMargemTexto,
  buscaGranel,
  custoKgGranel,
  diferencaPrecoGranel,
  editingMovimentacao,
  estoqueAtual,
  formData,
  formatMoney,
  formatPercentual,
  formatarQuantidade,
  granelDentroMargemEsperada,
  granelProdutos,
  granelSelecionadoId,
  granelVinculos,
  handleAlterarModoPrecoGranel,
  handleDesvincularGranel,
  handleSelecionarGranel,
  handleSubmit,
  handleSubmitGranel,
  kgGranelPrevisto,
  loadingGranel,
  margemBaseGranel,
  margemCalculadaGranel,
  margemGranel,
  modoPrecoGranel,
  nomeGranelSelecionado,
  observacaoGranel,
  onCloseGranel,
  onCloseLancamento,
  onCloseReservas,
  precoMinimoEsperadoGranel,
  precoVendaAtualGranel,
  precoVendaGranel,
  precoVendaKgOrigem,
  precoVendaSugeridoGranel,
  produto,
  produtoEhGranel,
  quantidadeGranel,
  quantidadeGranelNumero,
  reservasAtivas,
  setAtualizarPrecoGranel,
  setBuscaGranel,
  setFormData,
  setMargemBaseGranel,
  setMargemGranel,
  setObservacaoGranel,
  setPrecoVendaGranel,
  setQuantidadeGranel,
  setTipoLancamento,
  showGranelModal,
  showModal,
  showReservasModal,
  tipoLancamento,
  pesoPacoteOrigem,
}) {
  return (
    <>
      {showReservasModal && (
        <ReservasAtivasModal
          abrirPedidoReservado={abrirPedidoReservado}
          formatarQuantidade={formatarQuantidade}
          onClose={onCloseReservas}
          reservasAtivas={reservasAtivas}
        />
      )}

      {showModal && (
        <EstoqueLancamentoModal
          editingMovimentacao={editingMovimentacao}
          estoqueAtual={estoqueAtual}
          formData={formData}
          onClose={onCloseLancamento}
          onSubmit={handleSubmit}
          produto={produto}
          produtoEhGranel={produtoEhGranel}
          setFormData={setFormData}
          setTipoLancamento={setTipoLancamento}
          tipoLancamento={tipoLancamento}
        />
      )}

      {showGranelModal && (
        <GranelLancamentoModal
          atualizarPrecoGranel={atualizarPrecoGranel}
          baseMargemGranel={baseMargemGranel}
          baseMargemTexto={baseMargemTexto}
          buscaGranel={buscaGranel}
          custoKgGranel={custoKgGranel}
          diferencaPrecoGranel={diferencaPrecoGranel}
          formatMoney={formatMoney}
          formatPercentual={formatPercentual}
          formatarQuantidade={formatarQuantidade}
          granelDentroMargemEsperada={granelDentroMargemEsperada}
          granelProdutos={granelProdutos}
          granelSelecionadoId={granelSelecionadoId}
          granelVinculos={granelVinculos}
          handleAlterarModoPrecoGranel={handleAlterarModoPrecoGranel}
          handleDesvincularGranel={handleDesvincularGranel}
          handleSelecionarGranel={handleSelecionarGranel}
          kgGranelPrevisto={kgGranelPrevisto}
          loadingGranel={loadingGranel}
          margemBaseGranel={margemBaseGranel}
          margemCalculadaGranel={margemCalculadaGranel}
          margemGranel={margemGranel}
          modoPrecoGranel={modoPrecoGranel}
          nomeGranelSelecionado={nomeGranelSelecionado}
          observacaoGranel={observacaoGranel}
          onClose={onCloseGranel}
          onSubmit={handleSubmitGranel}
          precoMinimoEsperadoGranel={precoMinimoEsperadoGranel}
          precoVendaAtualGranel={precoVendaAtualGranel}
          precoVendaGranel={precoVendaGranel}
          precoVendaKgOrigem={precoVendaKgOrigem}
          precoVendaSugeridoGranel={precoVendaSugeridoGranel}
          produto={produto}
          quantidadeGranel={quantidadeGranel}
          quantidadeGranelNumero={quantidadeGranelNumero}
          setAtualizarPrecoGranel={setAtualizarPrecoGranel}
          setBuscaGranel={setBuscaGranel}
          setMargemBaseGranel={setMargemBaseGranel}
          setMargemGranel={setMargemGranel}
          setObservacaoGranel={setObservacaoGranel}
          setPrecoVendaGranel={setPrecoVendaGranel}
          setQuantidadeGranel={setQuantidadeGranel}
          pesoPacoteOrigem={pesoPacoteOrigem}
        />
      )}
    </>
  );
}
