import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const ordersStyles = StyleSheet.create({
  loading: { flex: 1, justifyContent: "center", alignItems: "center", gap: 12 },
  loadingText: { fontSize: FONTE.normal, color: CORES.textoSecundario },
  lista: { padding: ESPACO.md, paddingBottom: 40 },

  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    marginBottom: ESPACO.sm,
    paddingBottom: ESPACO.sm,
    borderBottomWidth: 1,
    borderBottomColor: CORES.borda,
  },
  headerTitulo: {
    fontSize: FONTE.grande,
    fontWeight: "700",
    color: CORES.texto,
  },
  headerSub: { fontSize: FONTE.pequena, color: CORES.textoSecundario },

  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginBottom: ESPACO.sm,
    ...SOMBRA,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: ESPACO.sm,
  },
  cardHeaderInfo: { flex: 1 },
  pedidoId: {
    fontSize: FONTE.normal,
    fontWeight: "700",
    color: CORES.texto,
    letterSpacing: 0.5,
  },
  pedidoData: {
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
    marginTop: 2,
  },
  canalBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 4,
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: RAIO.circulo,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
  },
  canalBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9A3412",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: ESPACO.sm,
    paddingVertical: 4,
    borderRadius: RAIO.circulo,
    gap: 4,
    maxWidth: 180,
  },
  statusTexto: { fontSize: 11, fontWeight: "600" },

  entregaBadge: {
    borderRadius: RAIO.sm,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: 5,
    marginBottom: ESPACO.sm,
    alignSelf: "flex-start",
  },
  entregaBadgeText: { fontSize: FONTE.pequena, fontWeight: "700" },
  retiradoPorTexto: {
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
    marginBottom: ESPACO.sm,
  },

  itensList: { marginBottom: ESPACO.sm, gap: 4 },
  itemLinha: { flexDirection: "row", alignItems: "center", gap: 8 },
  itemQtdBadge: {
    backgroundColor: CORES.fundo,
    borderRadius: RAIO.sm,
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 32,
    alignItems: "center",
  },
  itemQtd: { fontSize: 11, fontWeight: "700", color: CORES.primario },
  itemNome: { fontSize: FONTE.normal, color: CORES.textoSecundario, flex: 1 },
  itemMais: {
    fontSize: FONTE.pequena,
    color: CORES.textoClaro,
    marginTop: 2,
    marginLeft: 40,
  },

  palavraChaveBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.primarioClaro,
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
    marginBottom: ESPACO.sm,
    gap: ESPACO.sm,
  },
  palavraChaveLabel: { fontSize: 11, color: CORES.primario },
  palavraChaveValor: {
    fontSize: FONTE.grande,
    fontWeight: "800",
    color: CORES.primario,
    letterSpacing: 2,
  },

  cardRodape: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    paddingTop: ESPACO.sm,
    marginTop: ESPACO.xs,
  },
  totalLabel: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  totalValor: { fontSize: FONTE.grande, fontWeight: "800", color: CORES.texto },
  acoes: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  btnPagar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm - 2,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.circulo,
  },
  btnPagarTexto: {
    fontSize: FONTE.pequena,
    color: "#fff",
    fontWeight: "700",
  },
  btnRastrear: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm - 2,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.circulo,
  },
  btnRastrearTexto: {
    fontSize: FONTE.pequena,
    color: "#fff",
    fontWeight: "700",
  },
  btnRepetir: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm - 2,
    borderWidth: 1.5,
    borderColor: CORES.primario,
    borderRadius: RAIO.circulo,
  },
  btnRepetirTexto: {
    fontSize: FONTE.pequena,
    color: CORES.primario,
    fontWeight: "600",
  },

  vazio: {
    alignItems: "center",
    paddingTop: 80,
    paddingHorizontal: 40,
    gap: 12,
  },
  vazioEmoji: { fontSize: 64 },
  vazioTitulo: {
    fontSize: FONTE.grande,
    fontWeight: "700",
    color: CORES.texto,
  },
  vazioTexto: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    textAlign: "center",
    lineHeight: 22,
  },
  btnComprar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: CORES.primario,
    paddingHorizontal: ESPACO.lg,
    paddingVertical: ESPACO.sm + 2,
    borderRadius: RAIO.circulo,
    marginTop: 8,
  },
  btnComprarTexto: { fontSize: FONTE.normal, color: "#fff", fontWeight: "700" },
});
