import { StyleSheet } from "react-native";
import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  content: { padding: ESPACO.md, paddingBottom: ESPACO.xxl, gap: ESPACO.md },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: ESPACO.sm },
  loadingText: { color: CORES.textoSecundario },
  hero: {
    borderRadius: RAIO.lg,
    backgroundColor: "#0F766E",
    padding: ESPACO.lg,
    ...SOMBRA,
  },
  heroEyebrow: { color: "#99F6E4", fontSize: FONTE.pequena, fontWeight: "800" },
  heroTitle: { color: "#FFFFFF", fontSize: FONTE.titulo, fontWeight: "900", marginTop: 4 },
  heroText: { color: "#CCFBF1", marginTop: 5, lineHeight: 20 },
  tabs: { flexDirection: "row", gap: ESPACO.sm },
  tab: {
    flex: 1,
    minHeight: 46,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.superficie,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: { backgroundColor: "#0F766E", borderColor: "#0F766E" },
  tabText: { color: CORES.textoSecundario, fontWeight: "800" },
  tabTextActive: { color: "#FFFFFF" },
  toolbar: {
    borderRadius: RAIO.md,
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderColor: CORES.borda,
    padding: ESPACO.md,
    gap: ESPACO.sm,
  },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  title: { flex: 1, color: CORES.texto, fontSize: FONTE.grande, fontWeight: "900" },
  primaryButton: {
    minHeight: 42,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    paddingHorizontal: ESPACO.md,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonDisabled: { opacity: 0.55 },
  primaryButtonText: { color: "#FFFFFF", fontWeight: "900" },
  segment: { flexDirection: "row", gap: 6, padding: 4, backgroundColor: "#F1F5F9", borderRadius: RAIO.md },
  segmentButton: { flex: 1, paddingVertical: 8, borderRadius: RAIO.sm, alignItems: "center" },
  segmentButtonActive: { backgroundColor: "#FFFFFF" },
  segmentText: { color: CORES.textoClaro, fontWeight: "700" },
  segmentTextActive: { color: CORES.primario, fontWeight: "900" },
  navRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  navButton: { borderRadius: RAIO.md, backgroundColor: "#EFF6FF", paddingHorizontal: 12, paddingVertical: 9 },
  navText: { color: CORES.primario, fontSize: FONTE.pequena, fontWeight: "800" },
  periodTitle: { flex: 1, textAlign: "center", color: CORES.texto, fontWeight: "800", textTransform: "capitalize" },
  dayTitle: { color: CORES.texto, fontWeight: "900", textTransform: "capitalize", marginBottom: 8 },
  card: {
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.superficie,
    padding: ESPACO.md,
    marginBottom: ESPACO.sm,
    ...SOMBRA,
  },
  cardTop: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  cardPet: { color: CORES.texto, fontSize: FONTE.grande, fontWeight: "900" },
  cardTutor: { color: CORES.textoSecundario, marginTop: 2 },
  badge: { borderRadius: 999, backgroundColor: "#E0F2FE", paddingHorizontal: 9, paddingVertical: 5 },
  badgeText: { color: "#075985", fontSize: FONTE.pequena, fontWeight: "900" },
  badgeAlert: { backgroundColor: "#FEE2E2" },
  badgeAlertText: { color: "#B91C1C" },
  meta: { color: CORES.textoSecundario, marginTop: 7, lineHeight: 19 },
  services: { color: CORES.texto, fontWeight: "700", marginTop: 7 },
  cardActions: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 12 },
  secondaryButton: {
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.primario,
    paddingHorizontal: ESPACO.md,
    paddingVertical: 9,
  },
  secondaryButtonText: { color: CORES.primario, fontWeight: "900" },
  amount: { color: CORES.primario, fontWeight: "900" },
  empty: { borderRadius: RAIO.md, borderWidth: 1, borderStyle: "dashed", borderColor: CORES.borda, padding: ESPACO.xl, alignItems: "center" },
  emptyTitle: { color: CORES.texto, fontWeight: "900", marginTop: ESPACO.sm },
  emptyText: { color: CORES.textoSecundario, textAlign: "center", marginTop: 4 },
  stageScroll: { gap: 8, paddingRight: ESPACO.md },
  stageChip: { borderRadius: 999, borderWidth: 1, borderColor: CORES.borda, backgroundColor: "#FFFFFF", paddingHorizontal: 13, paddingVertical: 9 },
  stageChipActive: { backgroundColor: "#0F766E", borderColor: "#0F766E" },
  stageChipText: { color: CORES.textoSecundario, fontWeight: "800" },
  stageChipTextActive: { color: "#FFFFFF" },
  timerRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 8 },
  timerText: { color: CORES.textoSecundario, fontSize: FONTE.pequena, fontWeight: "700" },
  timerAlert: { color: "#B91C1C" },
  warningBox: { marginTop: 9, borderRadius: RAIO.sm, backgroundColor: "#FFF7ED", padding: 9 },
  warningText: { color: "#9A3412", fontSize: FONTE.pequena, fontWeight: "700" },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(15,23,42,0.55)", justifyContent: "flex-end" },
  modalCard: { maxHeight: "92%", borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: "#FFFFFF", padding: ESPACO.lg },
  modalHeader: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 },
  modalTitle: { flex: 1, color: CORES.texto, fontSize: FONTE.titulo, fontWeight: "900" },
  modalSubtitle: { color: CORES.textoSecundario, marginTop: 4 },
  closeButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#F1F5F9", alignItems: "center", justifyContent: "center" },
  label: { color: CORES.texto, fontWeight: "800", marginTop: ESPACO.md, marginBottom: 6 },
  input: { minHeight: 48, borderRadius: RAIO.md, borderWidth: 1, borderColor: CORES.borda, backgroundColor: CORES.fundo, paddingHorizontal: ESPACO.md, color: CORES.texto },
  multiline: { minHeight: 82, paddingTop: 12, textAlignVertical: "top" },
  optionList: { maxHeight: 180, borderWidth: 1, borderColor: CORES.borda, borderRadius: RAIO.md, overflow: "hidden" },
  option: { minHeight: 48, paddingHorizontal: ESPACO.md, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: "#F1F5F9", justifyContent: "center" },
  optionActive: { backgroundColor: "#ECFDF5" },
  optionTitle: { color: CORES.texto, fontWeight: "800" },
  optionText: { color: CORES.textoSecundario, fontSize: FONTE.pequena, marginTop: 2 },
  inlineFields: { flexDirection: "row", gap: 10 },
  field: { flex: 1 },
  modalFooter: { flexDirection: "row", gap: 10, marginTop: ESPACO.lg },
  cancelButton: { flex: 1, minHeight: 48, borderRadius: RAIO.md, backgroundColor: "#F1F5F9", alignItems: "center", justifyContent: "center" },
  cancelText: { color: CORES.textoSecundario, fontWeight: "900" },
  saveButton: { flex: 1.4, minHeight: 48, borderRadius: RAIO.md, backgroundColor: "#0F766E", alignItems: "center", justifyContent: "center" },
  saveText: { color: "#FFFFFF", fontWeight: "900" },
});
