import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const funcionarioContagemStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  conteudo: { padding: ESPACO.md, gap: ESPACO.md, paddingBottom: ESPACO.xxl },
  centrado: { flex: 1, alignItems: "center", justifyContent: "center", padding: ESPACO.lg, backgroundColor: CORES.fundo },
  tituloPermissao: { fontSize: FONTE.titulo, fontWeight: "700", color: CORES.texto, marginVertical: ESPACO.md },
  headerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    ...SOMBRA,
  },
  headerIcone: {
    width: 48,
    height: 48,
    borderRadius: RAIO.md,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: ESPACO.md,
  },
  headerTexto: { flex: 1 },
  titulo: { fontSize: FONTE.titulo, fontWeight: "800", color: CORES.texto },
  subtitulo: { fontSize: FONTE.normal, color: CORES.textoSecundario, marginTop: 2 },
  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    gap: ESPACO.sm,
    ...SOMBRA,
  },
  secaoCabecalho: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: ESPACO.sm },
  secaoTitulo: { fontSize: FONTE.grande, fontWeight: "800", color: CORES.texto },
  label: { fontSize: FONTE.normal, fontWeight: "700", color: CORES.texto, marginTop: ESPACO.xs },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    fontSize: FONTE.media,
    color: CORES.texto,
    backgroundColor: "#fff",
  },
  inputMultilinha: { minHeight: 78, textAlignVertical: "top" },
  buscaLinha: { flexDirection: "row", gap: ESPACO.sm, marginTop: ESPACO.xs },
  inputBusca: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    color: CORES.texto,
    fontSize: FONTE.normal,
    backgroundColor: "#fff",
  },
  botaoBusca: {
    width: 52,
    height: 48,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    alignItems: "center",
    justifyContent: "center",
  },
  fornecedorIcone: {
    width: 42,
    height: 42,
    borderRadius: RAIO.md,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  sugestao: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginTop: ESPACO.xs,
  },
  sugestaoNome: { fontSize: FONTE.normal, fontWeight: "700", color: CORES.texto },
  sugestaoMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  botaoScan: {
    height: 52,
    borderRadius: RAIO.md,
    backgroundColor: CORES.sucesso,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
  },
  botaoScanTexto: { color: "#fff", fontWeight: "800", fontSize: FONTE.media },
  feedbackOpcoes: { gap: ESPACO.sm },
  produtoImagemWrap: {
    width: 54,
    height: 54,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  produtoImagemWrapCompacta: { width: 44, height: 44 },
  produtoImagem: { width: "100%", height: "100%" },
  produtoCabecalho: { flexDirection: "row", alignItems: "flex-start", gap: ESPACO.sm },
  produtoNome: { fontSize: FONTE.grande, fontWeight: "800", color: CORES.texto },
  produtoMeta: { fontSize: FONTE.normal, color: CORES.textoSecundario, marginTop: 2 },
  botaoLimpar: {
    width: 36,
    height: 36,
    borderRadius: RAIO.circulo,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  metricas: { flexDirection: "row", gap: ESPACO.sm },
  metrica: { flex: 1, backgroundColor: CORES.fundo, borderRadius: RAIO.sm, padding: ESPACO.sm },
  metricaLabel: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  metricaValor: { fontSize: FONTE.media, fontWeight: "800", color: CORES.texto, marginTop: 2 },
  botaoSalvar: {
    height: 52,
    borderRadius: RAIO.md,
    backgroundColor: CORES.sucesso,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
    marginTop: ESPACO.sm,
  },
  botaoSalvarTexto: { color: "#fff", fontWeight: "800", fontSize: FONTE.media },
  botaoDesabilitado: { opacity: 0.5 },
  itemLinha: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  itemNome: { fontSize: FONTE.normal, fontWeight: "800", color: CORES.texto },
  itemMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  itemObs: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 4 },
  botaoRemover: {
    width: 36,
    height: 36,
    borderRadius: RAIO.circulo,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  vazio: { alignItems: "center", justifyContent: "center", paddingVertical: ESPACO.lg, gap: ESPACO.xs },
  vazioTexto: { color: CORES.textoSecundario, fontWeight: "700" },
  badge: {
    overflow: "hidden",
    borderRadius: RAIO.circulo,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: 4,
    backgroundColor: "#E5E7EB",
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    fontWeight: "800",
  },
  resumoBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: CORES.fundo,
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
  },
  resumoTexto: { color: CORES.textoSecundario, fontWeight: "700" },
  resumoValor: { color: CORES.texto, fontWeight: "900", fontSize: FONTE.media },
  checkboxLinha: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  checkboxTitulo: { fontSize: FONTE.normal, color: CORES.texto, fontWeight: "800" },
  checkboxDescricao: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  totalLinha: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9FAFB",
    borderRadius: RAIO.sm,
    padding: ESPACO.sm,
  },
  totalLabel: { color: CORES.textoSecundario, fontWeight: "800" },
  totalValor: { color: CORES.texto, fontWeight: "900", fontSize: FONTE.media },
  exportLinha: { flexDirection: "row", gap: ESPACO.sm },
  botaoExportar: {
    flex: 1,
    height: 50,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
  },
  botaoExportarTexto: { color: "#fff", fontWeight: "800", fontSize: FONTE.media },
  resultado: {
    flexDirection: "row",
    gap: ESPACO.sm,
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderColor: "#BBF7D0",
    borderWidth: 1,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  resultadoTexto: { flex: 1, color: "#065F46", fontWeight: "700" },
  historicoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  historicoAbrir: { flex: 1, flexDirection: "row", alignItems: "center", gap: ESPACO.sm },
  historicoTitulo: { fontSize: FONTE.normal, fontWeight: "800", color: CORES.texto },
  historicoMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  botaoExcluirHistorico: {
    width: 38,
    height: 38,
    borderRadius: RAIO.circulo,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  botaoPrimario: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.lg,
    paddingVertical: ESPACO.md,
  },
  botaoPrimarioTexto: { color: "#fff", fontWeight: "800" },
  scannerContainer: { flex: 1, backgroundColor: "#000" },
  camera: { flex: 1 },
  scannerOverlay: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.25)" },
  fecharScanner: {
    position: "absolute",
    top: 48,
    right: 24,
    width: 44,
    height: 44,
    borderRadius: RAIO.circulo,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  frameScan: {
    width: 260,
    height: 160,
    borderWidth: 3,
    borderColor: "#fff",
    borderRadius: RAIO.md,
  },
  scannerTexto: { color: "#fff", marginTop: ESPACO.lg, fontSize: FONTE.media, fontWeight: "700" },
  scannerFeedback: {
    minHeight: 48,
    maxWidth: "86%",
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  scannerFeedbackSucesso: { backgroundColor: "rgba(22, 163, 74, 0.92)" },
  scannerFeedbackErro: { backgroundColor: "rgba(220, 38, 38, 0.92)" },
  scannerFeedbackTexto: { flex: 1, color: "#fff", fontWeight: "800", fontSize: FONTE.normal },
  botaoScanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  botaoScannerTexto: { color: "#fff", fontWeight: "800" },
});
