from fastapi import APIRouter

from app.routes import (
    ecommerce_auth_beneficios,
    ecommerce_auth_profiles,
    ecommerce_auth_public,
    ecommerce_auth_recovery,
)
from app.routes.ecommerce_auth_beneficios import (
    meu_extrato_cashback,
    meus_beneficios,
    meus_cupons,
    minha_sugestao_cashback,
)
from app.routes.ecommerce_auth_cliente import (
    _copy_missing_cliente_fields,
    _digits_only,
    _extract_ecommerce_delivery_details,
    _find_cliente_match,
    _find_operational_cliente_match,
    _get_or_create_cliente_for_user,
    _identity_match_reasons,
    _identity_matches_cliente,
    _is_operational_cliente,
    _select_linked_cliente_fallback,
    _select_preferred_cliente,
    _transfer_cliente_relations_for_ecommerce_merge,
    _upsert_delivery_details,
    transferir_referencias_pessoa,
)
from app.routes.ecommerce_auth_common import (
    _activate_user_tenant_context,
    _align_reference_datetime,
    _cashback_disponivel_clause,
    _ensure_active_store_access,
    _extract_tenant_id_from_request,
    _get_current_ecommerce_user,
    _get_or_create_customer_role,
    _is_expired,
    _is_expired_or_equal,
    _normalize_tenant_uuid,
    _remaining_days_until,
    _tenant_status_is_active,
    security,
)
from app.routes.ecommerce_auth_profiles import (
    _serialize_profile,
    atualizar_perfil,
    me,
    obter_perfil,
    selecionar_perfil_app,
)
from app.routes.ecommerce_auth_public import login_cliente, registrar_cliente
from app.routes.ecommerce_auth_recovery import (
    _build_email_verification_link,
    _build_reset_password_email_for_app,
    _build_reset_password_email_for_site,
    _build_storefront_reset_link,
    _email_verification_block,
    _hash_token,
    _issue_email_verification_token,
    _issue_numeric_code,
    _issue_password_reset_tokens,
    _mark_user_consent,
    _now_utc,
    _password_reset_token_matches,
    _resolve_password_recovery_channel,
    _send_email_verification,
    esqueci_senha,
    resetar_senha,
)
from app.routes.ecommerce_auth_schemas import (
    EcommerceForgotPasswordRequest,
    EcommerceLoginRequest,
    EcommerceProfileUpdateRequest,
    EcommerceRegisterRequest,
    EcommerceResetPasswordRequest,
    EcommerceSelectProfileRequest,
)
from app.routes.ecommerce_auth_settings import (
    EMAIL_VERIFICATION_REQUIRED,
    EMAIL_VERIFICATION_TOKEN_HOURS,
    PRIVACY_VERSION,
    RESET_TOKEN_MINUTES,
    TERMS_VERSION,
)


router = APIRouter(prefix="/ecommerce/auth", tags=["ecommerce-auth"])
router.include_router(ecommerce_auth_public.router)
router.include_router(ecommerce_auth_recovery.router)
router.include_router(ecommerce_auth_profiles.router)
router.include_router(ecommerce_auth_beneficios.router)


__all__ = [
    "EMAIL_VERIFICATION_REQUIRED",
    "EMAIL_VERIFICATION_TOKEN_HOURS",
    "PRIVACY_VERSION",
    "RESET_TOKEN_MINUTES",
    "TERMS_VERSION",
    "EcommerceForgotPasswordRequest",
    "EcommerceLoginRequest",
    "EcommerceProfileUpdateRequest",
    "EcommerceRegisterRequest",
    "EcommerceResetPasswordRequest",
    "EcommerceSelectProfileRequest",
    "_activate_user_tenant_context",
    "_align_reference_datetime",
    "_build_email_verification_link",
    "_build_reset_password_email_for_app",
    "_build_reset_password_email_for_site",
    "_build_storefront_reset_link",
    "_cashback_disponivel_clause",
    "_copy_missing_cliente_fields",
    "_digits_only",
    "_email_verification_block",
    "_ensure_active_store_access",
    "_extract_ecommerce_delivery_details",
    "_extract_tenant_id_from_request",
    "_find_cliente_match",
    "_find_operational_cliente_match",
    "_get_current_ecommerce_user",
    "_get_or_create_cliente_for_user",
    "_get_or_create_customer_role",
    "_hash_token",
    "_identity_match_reasons",
    "_identity_matches_cliente",
    "_is_expired",
    "_is_expired_or_equal",
    "_is_operational_cliente",
    "_issue_email_verification_token",
    "_issue_numeric_code",
    "_issue_password_reset_tokens",
    "_mark_user_consent",
    "_normalize_tenant_uuid",
    "_now_utc",
    "_password_reset_token_matches",
    "_remaining_days_until",
    "_resolve_password_recovery_channel",
    "_select_linked_cliente_fallback",
    "_select_preferred_cliente",
    "_send_email_verification",
    "_serialize_profile",
    "_tenant_status_is_active",
    "_transfer_cliente_relations_for_ecommerce_merge",
    "_upsert_delivery_details",
    "atualizar_perfil",
    "esqueci_senha",
    "login_cliente",
    "me",
    "meu_extrato_cashback",
    "meus_beneficios",
    "meus_cupons",
    "minha_sugestao_cashback",
    "obter_perfil",
    "registrar_cliente",
    "resetar_senha",
    "router",
    "security",
    "selecionar_perfil_app",
    "transferir_referencias_pessoa",
]
