import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const profileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  content: { padding: ESPACO.lg, paddingBottom: 140 },
  avatarSection: { alignItems: "center", marginBottom: ESPACO.lg },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: CORES.primario,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: ESPACO.sm,
  },
  avatarLetter: { fontSize: 36, color: "#fff", fontWeight: "700" },
  nomeUsuario: { fontSize: FONTE.titulo, fontWeight: "bold", color: CORES.texto },
  emailUsuario: { fontSize: FONTE.normal, color: CORES.textoSecundario, marginTop: 2 },
  pontosCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    backgroundColor: "#FFF8E1",
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
    marginBottom: ESPACO.lg,
    borderWidth: 1,
    borderColor: "#FFE082",
    gap: ESPACO.md,
    justifyContent: "space-between",
    ...SOMBRA,
  },
  pontosLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  pontosResumo: { flexShrink: 1, minWidth: 0 },
  pontosValor: { fontSize: FONTE.grande, fontWeight: "bold", color: "#92400E" },
  pontosLabel: { fontSize: FONTE.pequena, color: "#78350F", flexShrink: 1 },
  pontosInfoSpacer: { flexGrow: 1, minWidth: 0 },
  pontosInfo: { alignItems: "flex-end", flexShrink: 1, minWidth: 130 },
  pontosInfoTextoLinha: { fontSize: FONTE.pequena, color: "#78350F", textAlign: "right" },
  secao: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
    marginBottom: ESPACO.lg,
    ...SOMBRA,
  },
  secaoHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: ESPACO.md,
  },
  secaoTitulo: { fontSize: FONTE.grande, fontWeight: "bold", color: CORES.texto },
  perfisGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  perfilBotao: {
    borderWidth: 1,
    borderColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    backgroundColor: CORES.superficie,
  },
  perfilBotaoAtivo: {
    backgroundColor: CORES.primario,
  },
  perfilBotaoTexto: {
    color: CORES.primario,
    fontSize: FONTE.normal,
    fontWeight: "700",
  },
  perfilBotaoTextoAtivo: {
    color: "#fff",
  },
  botaoPerfilAtualizar: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.primario,
    borderRadius: RAIO.md,
    marginTop: ESPACO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    backgroundColor: "#EFF6FF",
  },
  botaoPerfilAtualizarTexto: {
    color: CORES.primario,
    fontSize: FONTE.normal,
    fontWeight: "700",
  },
  editarTexto: { color: CORES.primario, fontWeight: "500" },
  infoRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: ESPACO.sm },
  infoLabel: { fontSize: FONTE.normal, color: CORES.textoSecundario },
  infoValor: {
    fontSize: FONTE.normal,
    color: CORES.texto,
    fontWeight: "500",
    flex: 1,
    textAlign: "right",
  },
  campo: { marginBottom: ESPACO.sm },
  campoLabel: {
    fontSize: FONTE.pequena,
    fontWeight: "600",
    color: CORES.textoSecundario,
    marginBottom: 4,
  },
  input: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    fontSize: FONTE.normal,
    color: CORES.texto,
    backgroundColor: CORES.fundo,
  },
  botaoSalvar: {
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.sm + 4,
    alignItems: "center",
    marginTop: ESPACO.sm,
  },
  botaoSalvarTexto: { color: "#fff", fontWeight: "bold", fontSize: FONTE.normal },
  botaoNotificacoes: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ESPACO.sm,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingVertical: ESPACO.sm + 4,
    marginTop: ESPACO.md,
  },
  botaoNotificacoesTexto: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: FONTE.normal,
  },
  linha: { flexDirection: "row", gap: ESPACO.sm },
  toggleLinha: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    marginBottom: ESPACO.sm,
  },
  toggleTexto: { fontSize: FONTE.normal, color: CORES.texto, fontWeight: "600" },
  enderecoCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: ESPACO.sm,
    backgroundColor: "#EFF6FF",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: "#BFDBFE",
  },
  enderecoTexto: { fontSize: FONTE.normal, color: CORES.texto, flex: 1 },
  enderecoSub: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  textoSuporte: {
    fontSize: FONTE.normal,
    color: CORES.textoSecundario,
    lineHeight: 20,
  },
  botaoSair: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ESPACO.sm,
    paddingVertical: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.erro,
    borderRadius: RAIO.md,
    marginBottom: ESPACO.sm,
    backgroundColor: "#FEF2F2",
  },
  botaoSairTexto: { color: CORES.erro, fontWeight: "bold", fontSize: FONTE.normal },
  exclusaoSecao: {
    paddingVertical: ESPACO.md,
    marginTop: ESPACO.md,
  },
  exclusaoTitulo: {
    fontSize: FONTE.media,
    fontWeight: "700",
    color: CORES.texto,
    marginBottom: ESPACO.xs,
  },
  exclusaoTexto: {
    fontSize: FONTE.pequena,
    lineHeight: 18,
    color: CORES.textoSecundario,
    marginBottom: ESPACO.md,
  },
  botaoExcluirConta: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.erro,
    borderRadius: RAIO.md,
    backgroundColor: "#FEF2F2",
  },
  botaoExcluirContaTexto: {
    color: CORES.erro,
    fontWeight: "700",
    fontSize: FONTE.normal,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    padding: ESPACO.lg,
    backgroundColor: "rgba(17, 24, 39, 0.62)",
  },
  modalExclusao: {
    width: "100%",
    maxWidth: 460,
    alignSelf: "center",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.lg,
  },
  modalExclusaoIcone: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEF2F2",
    marginBottom: ESPACO.md,
  },
  modalExclusaoTitulo: {
    fontSize: FONTE.grande,
    fontWeight: "700",
    color: CORES.texto,
    marginBottom: ESPACO.sm,
  },
  modalExclusaoTexto: {
    fontSize: FONTE.normal,
    lineHeight: 20,
    color: CORES.textoSecundario,
    marginBottom: ESPACO.lg,
  },
  modalCampoLabel: {
    fontSize: FONTE.pequena,
    fontWeight: "700",
    color: CORES.textoSecundario,
    marginTop: ESPACO.sm,
    marginBottom: ESPACO.xs,
  },
  botaoExcluirDefinitivo: {
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: RAIO.md,
    backgroundColor: CORES.erro,
    marginTop: ESPACO.lg,
  },
  botaoExcluirDefinitivoDesativado: { opacity: 0.45 },
  botaoExcluirDefinitivoTexto: {
    color: "#fff",
    fontSize: FONTE.normal,
    fontWeight: "700",
  },
  botaoCancelarExclusao: {
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    marginTop: ESPACO.sm,
  },
  botaoCancelarExclusaoTexto: {
    color: CORES.textoSecundario,
    fontSize: FONTE.normal,
    fontWeight: "600",
  },
  versao: { textAlign: "center", fontSize: FONTE.pequena, color: CORES.textoClaro },
});
