import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const petDetailStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  content: { padding: ESPACO.lg, gap: ESPACO.md },
  headerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.md,
    ...SOMBRA,
  },
  foto: { width: 72, height: 72, borderRadius: 36 },
  fotoPlaceholder: {
    backgroundColor: CORES.primarioClaro,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fotoEmoji: { fontSize: 32 },
  nome: { fontSize: FONTE.grande, fontWeight: '700', color: CORES.texto },
  subtitulo: { fontSize: FONTE.normal, color: CORES.textoSecundario, marginTop: 2 },
  botaoEditar: {
    padding: 8,
    borderRadius: RAIO.circulo,
    backgroundColor: CORES.primarioClaro,
  },
  quickNavRow: {
    flexDirection: 'row',
    gap: ESPACO.sm,
  },
  quickNavButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    backgroundColor: '#EFF6FF',
  },
  quickNavLabel: {
    fontSize: FONTE.pequena,
    fontWeight: '700',
    color: CORES.primario,
  },
  loadingBox: { paddingVertical: ESPACO.xl, alignItems: 'center' },
  loadingText: { marginTop: ESPACO.sm, color: CORES.textoSecundario },
  resumoGrid: { flexDirection: 'row', gap: ESPACO.sm },
  resumoCard: {
    flex: 1,
    backgroundColor: CORES.superficie,
    borderWidth: 1,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    alignItems: 'center',
  },
  resumoValor: { fontSize: 26, fontWeight: '700' },
  resumoTitulo: {
    marginTop: 4,
    fontSize: FONTE.pequena,
    color: CORES.textoSecundario,
  },
  section: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    ...SOMBRA,
  },
  sectionTitulo: {
    fontSize: FONTE.grande,
    fontWeight: '700',
    color: CORES.texto,
    marginBottom: ESPACO.sm,
  },
  alertaItem: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  alertaTexto: { flex: 1, color: CORES.texto },
  itemCard: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
    marginBottom: ESPACO.sm,
  },
  itemTitulo: { fontSize: FONTE.normal, fontWeight: '700', color: CORES.texto },
  itemMeta: { marginTop: 2, fontSize: FONTE.pequena, color: CORES.textoSecundario },
  itemResumo: { marginTop: 8, fontSize: FONTE.pequena, color: CORES.texto },
  linkTexto: { marginTop: 8, color: CORES.primario, fontWeight: '600' },
  vazioTexto: { color: CORES.textoSecundario },
  folhetoCarteira: {
    borderRadius: RAIO.lg,
    backgroundColor: '#74D391',
    padding: ESPACO.md,
    gap: ESPACO.sm,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  folhetoPaws: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    opacity: 0.9,
  },
  folhetoIdentidade: {
    flexDirection: 'row',
    gap: ESPACO.md,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: RAIO.lg,
    padding: ESPACO.sm,
  },
  folhetoLabel: {
    fontSize: 10,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#064E3B',
    fontWeight: '900',
  },
  folhetoPetNome: {
    marginTop: 4,
    fontSize: 22,
    color: '#064E3B',
    fontWeight: '900',
  },
  folhetoPetInfo: {
    marginTop: 2,
    fontSize: FONTE.pequena,
    color: '#065F46',
    fontWeight: '700',
  },
  folhetoFoto: {
    width: 88,
    height: 88,
    borderRadius: RAIO.md,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    transform: [{ rotate: '5deg' }],
  },
  folhetoFotoPlaceholder: {
    backgroundColor: '#DCFCE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  folhetoSlots: { gap: ESPACO.sm },
  folhetoVacinaSlot: {
    borderRadius: RAIO.lg,
    backgroundColor: '#FFFFFF',
    padding: ESPACO.sm,
    borderWidth: 1,
    borderColor: 'rgba(6, 78, 59, 0.12)',
  },
  folhetoVacinaSlotVazio: {
    minHeight: 92,
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderStyle: 'dashed',
  },
  folhetoSlotHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: ESPACO.sm,
  },
  folhetoSlotLabel: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#15803D',
    fontWeight: '900',
  },
  folhetoSlotTitulo: {
    marginTop: 2,
    fontSize: FONTE.normal,
    color: CORES.texto,
    fontWeight: '900',
  },
  folhetoSlotTexto: {
    marginTop: 4,
    color: '#166534',
    fontSize: FONTE.pequena,
  },
  folhetoStatusPill: {
    borderRadius: RAIO.circulo,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#F8FAFC',
  },
  folhetoStatusTexto: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  folhetoSlotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: ESPACO.sm,
  },
  folhetoInfoBox: {
    width: '48%',
    borderRadius: RAIO.md,
    backgroundColor: '#F8FAFC',
    padding: 8,
  },
  folhetoInfoLabel: {
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: CORES.textoClaro,
    fontWeight: '900',
  },
  folhetoInfoValor: {
    marginTop: 3,
    fontSize: FONTE.pequena,
    color: CORES.texto,
    fontWeight: '800',
  },
  folhetoAssinatura: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACO.sm,
    marginTop: ESPACO.sm,
    borderRadius: RAIO.md,
    backgroundColor: '#ECFDF5',
    padding: 8,
  },
  folhetoQr: {
    width: 42,
    height: 42,
    borderRadius: RAIO.md,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  folhetoAssinaturaTitulo: {
    fontSize: 10,
    color: '#166534',
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  folhetoAssinaturaTexto: {
    marginTop: 2,
    color: '#064E3B',
    fontWeight: '800',
  },
  folhetoAssinaturaHash: {
    marginTop: 2,
    fontSize: 10,
    color: '#15803D',
    fontWeight: '700',
  },
  folhetoPaginacao: {
    marginTop: ESPACO.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: ESPACO.sm,
  },
  folhetoPaginaBotao: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: RAIO.circulo,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: 8,
    backgroundColor: '#EFF6FF',
  },
  folhetoPaginaBotaoDisabled: {
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
  },
  folhetoPaginaTexto: {
    color: CORES.primario,
    fontWeight: '800',
    fontSize: FONTE.pequena,
  },
  folhetoPaginaTextoDisabled: { color: CORES.textoClaro },
  folhetoPaginaInfo: {
    color: CORES.textoSecundario,
    fontSize: FONTE.pequena,
    fontWeight: '800',
  },
  vacinaCard: {
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: RAIO.lg,
    padding: ESPACO.md,
    marginBottom: ESPACO.sm,
    backgroundColor: '#F8FBFF',
  },
  vacinaCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACO.sm,
  },
  vacinaIconBox: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: CORES.primarioClaro,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vacinaNome: { fontSize: FONTE.normal, fontWeight: '800', color: CORES.texto },
  vacinaStatusPill: {
    borderRadius: RAIO.circulo,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  vacinaStatusTexto: { fontSize: FONTE.pequena, fontWeight: '800' },
  vacinaGrid: {
    flexDirection: 'row',
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  vacinaCampo: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
  },
  vacinaCampoLabel: {
    fontSize: 10,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: CORES.textoClaro,
    fontWeight: '800',
  },
  vacinaCampoValor: {
    marginTop: 3,
    fontSize: FONTE.pequena,
    color: CORES.texto,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.58)',
    justifyContent: 'center',
    padding: ESPACO.lg,
  },
  modalCard: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.lg,
    padding: ESPACO.md,
    ...SOMBRA,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: ESPACO.md,
  },
  modalTitulo: { fontSize: FONTE.grande, fontWeight: '800', color: CORES.texto },
  modalSubtitulo: { marginTop: 2, fontSize: FONTE.pequena, color: CORES.textoSecundario },
  modalCloseButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CORES.fundo,
  },
  carteiraVirtual: {
    borderRadius: RAIO.lg,
    borderWidth: 1,
    borderColor: '#F6AD55',
    backgroundColor: '#FFFBEB',
    padding: ESPACO.md,
  },
  carteiraTopLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: ESPACO.sm,
  },
  carteiraPetNome: { fontSize: FONTE.grande, fontWeight: '900', color: CORES.texto },
  carteiraStamp: {
    minWidth: 82,
    minHeight: 82,
    borderRadius: 41,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-8deg' }],
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  carteiraStampTexto: {
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  carteiraVacinaNome: {
    marginTop: ESPACO.md,
    fontSize: 22,
    fontWeight: '900',
    color: CORES.texto,
  },
  carteiraInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
  },
  carteiraInfoBox: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
  },
  carteiraInfoLabel: {
    fontSize: 10,
    letterSpacing: 0.8,
    color: CORES.textoClaro,
    textTransform: 'uppercase',
    fontWeight: '800',
  },
  carteiraInfoValor: {
    marginTop: 4,
    fontSize: FONTE.pequena,
    color: CORES.texto,
    fontWeight: '800',
  },
  assinaturaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
    padding: ESPACO.sm,
    borderRadius: RAIO.md,
    backgroundColor: '#EEF2FF',
  },
  assinaturaTitulo: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  assinaturaNome: { marginTop: 2, fontSize: FONTE.normal, fontWeight: '800', color: CORES.texto },
  assinaturaCodigo: { marginTop: 2, fontSize: FONTE.pequena, color: CORES.primario },
  hashTexto: {
    marginTop: ESPACO.sm,
    fontSize: 10,
    color: CORES.textoClaro,
    textAlign: 'center',
  },
  fecharModal: {
    marginTop: ESPACO.md,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    paddingVertical: ESPACO.sm + 2,
    alignItems: 'center',
  },
  fecharModalTexto: { color: '#FFFFFF', fontWeight: '800' },
  pendenteChip: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#F6AD55',
    backgroundColor: '#FFF7ED',
    borderRadius: RAIO.circulo,
    paddingHorizontal: ESPACO.md,
    paddingVertical: 8,
    marginBottom: ESPACO.xs,
  },
  pendenteTexto: { color: '#9C4221', fontWeight: '600' },
});
