"""Constantes das pendencias de compras."""

from decimal import Decimal

UNIT_PRECISION = Decimal("0.0001")
PENDENCIA_STATUS_ABERTA = "aberta"
PENDENCIA_STATUS_AGUARDANDO = "aguardando_fornecedor"
PENDENCIA_STATUS_TRATATIVA = "em_tratativa"
PENDENCIA_STATUS_RESOLVIDA = "resolvida"
PENDENCIA_STATUS_CANCELADA = "cancelada"
PENDENCIA_STATUS_VALIDOS = {
    PENDENCIA_STATUS_ABERTA,
    PENDENCIA_STATUS_AGUARDANDO,
    PENDENCIA_STATUS_TRATATIVA,
    PENDENCIA_STATUS_RESOLVIDA,
    PENDENCIA_STATUS_CANCELADA,
}
PENDENCIA_STATUS_FINAIS = {PENDENCIA_STATUS_RESOLVIDA, PENDENCIA_STATUS_CANCELADA}
