import { StyleSheet } from "react-native";

import { CORES, ESPACO, FONTE, RAIO, SOMBRA } from "../../../theme";

export const funcionarioPdvStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: CORES.fundo },
  conteudo: { padding: ESPACO.md, gap: ESPACO.md, paddingBottom: ESPACO.xxl },
  centrado: { flex: 1, alignItems: "center", justifyContent: "center", padding: ESPACO.lg, backgroundColor: CORES.fundo },
  tituloPermissao: { fontSize: FONTE.titulo, fontWeight: "800", color: CORES.texto, marginVertical: ESPACO.md },
  botaoPrimario: {
    height: 48,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    paddingHorizontal: ESPACO.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  botaoPrimarioTexto: { color: "#fff", fontWeight: "800", fontSize: FONTE.media },
  headerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    ...SOMBRA,
  },
  headerIcone: {
    width: 48,
    height: 48,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primarioClaro,
    alignItems: "center",
    justifyContent: "center",
    marginRight: ESPACO.md,
  },
  titulo: { fontSize: FONTE.titulo, fontWeight: "800", color: CORES.texto },
  subtitulo: { fontSize: FONTE.normal, color: CORES.textoSecundario, marginTop: 2 },
  botaoAtualizarCaixa: {
    width: 40,
    height: 40,
    borderRadius: RAIO.circulo,
    backgroundColor: CORES.primarioClaro,
    alignItems: "center",
    justifyContent: "center",
  },
  caixaBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
  },
  caixaAberto: { backgroundColor: "#ECFDF5", borderColor: "#BBF7D0" },
  caixaFechado: { backgroundColor: "#FFFBEB", borderColor: "#FDE68A" },
  caixaTexto: { flex: 1, color: CORES.texto, fontSize: FONTE.normal, fontWeight: "700" },
  card: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    gap: ESPACO.sm,
    ...SOMBRA,
  },
  botaoScan: {
    height: 52,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
  },
  botaoScanTexto: { color: "#fff", fontWeight: "800", fontSize: FONTE.media },
  buscaLinha: { flexDirection: "row", gap: ESPACO.sm },
  inputBusca: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    color: CORES.texto,
    fontSize: FONTE.normal,
    backgroundColor: "#fff",
  },
  botaoBusca: {
    width: 52,
    height: 48,
    borderRadius: RAIO.md,
    backgroundColor: CORES.primario,
    alignItems: "center",
    justifyContent: "center",
  },
  sugestao: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    marginTop: ESPACO.xs,
  },
  sugestaoNome: { fontSize: FONTE.normal, fontWeight: "800", color: CORES.texto },
  sugestaoMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  linhaTitulo: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  secaoTitulo: { fontSize: FONTE.grande, fontWeight: "800", color: CORES.texto },
  badge: {
    backgroundColor: CORES.primarioClaro,
    color: CORES.primario,
    borderRadius: RAIO.circulo,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.xs,
    fontWeight: "800",
    overflow: "hidden",
  },
  vazio: { alignItems: "center", paddingVertical: ESPACO.lg },
  vazioTexto: { marginTop: ESPACO.sm, color: CORES.textoSecundario, fontSize: FONTE.normal },
  itemCarrinho: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: ESPACO.sm,
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    paddingTop: ESPACO.sm,
  },
  produtoImagemWrap: {
    width: 54,
    height: 54,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    backgroundColor: CORES.fundo,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  produtoImagemWrapCompacta: {
    width: 44,
    height: 44,
  },
  produtoImagem: { width: "100%", height: "100%" },
  itemNome: { fontSize: FONTE.normal, fontWeight: "800", color: CORES.texto },
  itemMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario, marginTop: 2 },
  itemCarrinhoConteudo: { flex: 1, gap: ESPACO.xs },
  itemCarrinhoTopo: { flexDirection: "row", alignItems: "flex-start", gap: ESPACO.sm },
  itemControles: { flexDirection: "row", flexWrap: "wrap", gap: ESPACO.sm },
  campoCarrinho: { gap: 3 },
  campoCarrinhoLabel: { color: CORES.textoSecundario, fontSize: FONTE.pequena, fontWeight: "800" },
  quantidadeBox: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: CORES.borda, borderRadius: RAIO.md },
  botaoQuantidade: { width: 34, height: 38, alignItems: "center", justifyContent: "center" },
  inputQuantidade: {
    width: 66,
    height: 38,
    textAlign: "center",
    color: CORES.texto,
    fontWeight: "800",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: CORES.borda,
  },
  inputValorItem: {
    width: 92,
    height: 40,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.sm,
    textAlign: "right",
    color: CORES.texto,
    fontWeight: "800",
    backgroundColor: "#fff",
  },
  itemSubtotal: { minWidth: 82, textAlign: "right", fontWeight: "800", color: CORES.texto },
  clienteSelecionado: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BBF7D0",
    backgroundColor: "#ECFDF5",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
  },
  clienteNome: { fontSize: FONTE.media, fontWeight: "800", color: CORES.texto },
  clienteMeta: { fontSize: FONTE.pequena, color: CORES.textoSecundario },
  botaoDetalhesCliente: {
    height: 36,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    paddingHorizontal: ESPACO.sm,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 4,
    marginRight: ESPACO.xs,
    backgroundColor: "#EFF6FF",
  },
  botaoDetalhesClienteTexto: { color: CORES.primario, fontWeight: "800", fontSize: FONTE.pequena },
  detalhesCliente: {
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: 3,
  },
  detalhesClienteTitulo: { color: CORES.texto, fontWeight: "900", fontSize: FONTE.media },
  detalhesClienteSubtitulo: { color: CORES.primario, fontWeight: "900", fontSize: FONTE.pequena, marginTop: ESPACO.xs },
  detalhesClienteLinha: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  botaoLimpar: {
    width: 36,
    height: 36,
    borderRadius: RAIO.circulo,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  formasGrid: { flexDirection: "row", flexWrap: "wrap", gap: ESPACO.sm },
  formaBotao: {
    flexGrow: 1,
    minWidth: "46%",
    height: 52,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
    backgroundColor: "#fff",
  },
  formaBotaoAtivo: { borderColor: CORES.primario, backgroundColor: CORES.primarioClaro },
  formaTexto: { color: CORES.textoSecundario, fontWeight: "800" },
  formaTextoAtivo: { color: CORES.primario },
  cartaoBox: { gap: ESPACO.xs },
  cartaoInstrucao: { color: CORES.textoSecundario, fontSize: FONTE.pequena, marginTop: -ESPACO.xs },
  cartaoOpcoesGrid: { gap: ESPACO.xs },
  cartaoOpcao: {
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    backgroundColor: "#fff",
    padding: ESPACO.sm,
    gap: 2,
  },
  cartaoOpcaoAtiva: { borderColor: CORES.primario, backgroundColor: CORES.primarioClaro },
  cartaoOpcaoTitulo: { color: CORES.texto, fontWeight: "900", fontSize: FONTE.normal },
  cartaoOpcaoTituloAtivo: { color: CORES.primario },
  cartaoOpcaoSubtitulo: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  cartaoOpcaoAviso: { color: CORES.primario, fontSize: FONTE.pequena, fontWeight: "800" },
  cartaoAviso: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.xs,
    borderWidth: 1,
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
  },
  cartaoAvisoTexto: { flex: 1, color: CORES.erro, fontWeight: "700", fontSize: FONTE.pequena },
  parcelasBox: { gap: ESPACO.xs },
  parcelasGrid: { flexDirection: "row", flexWrap: "wrap", gap: ESPACO.xs },
  parcelaBotao: {
    minWidth: 48,
    height: 38,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  parcelaBotaoAtivo: { borderColor: CORES.primario, backgroundColor: CORES.primarioClaro },
  parcelaTexto: { color: CORES.textoSecundario, fontWeight: "800" },
  parcelaTextoAtivo: { color: CORES.primario },
  label: { fontSize: FONTE.normal, fontWeight: "700", color: CORES.texto, marginTop: ESPACO.xs },
  beneficioErro: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.xs,
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
  },
  beneficioErroTexto: { flex: 1, color: CORES.erro, fontSize: FONTE.pequena, fontWeight: "700" },
  beneficioInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.xs,
    backgroundColor: CORES.fundo,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    padding: ESPACO.sm,
  },
  beneficioInfoTexto: { flex: 1, color: CORES.textoSecundario, fontSize: FONTE.pequena },
  cuponsLista: { gap: ESPACO.xs },
  cupomChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.xs,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.sm,
    paddingVertical: ESPACO.xs,
  },
  cupomChipTexto: { flex: 1, color: CORES.primario, fontWeight: "800", fontSize: FONTE.pequena },
  beneficiosGeradosBox: {
    borderWidth: 1,
    borderColor: "#BBF7D0",
    backgroundColor: "#ECFDF5",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.xs,
  },
  beneficiosGeradosTitulo: { color: "#065F46", fontWeight: "900", fontSize: FONTE.normal },
  beneficioGeradoLinha: { flexDirection: "row", alignItems: "center", gap: ESPACO.sm },
  beneficioGeradoTitulo: { color: CORES.texto, fontWeight: "800", fontSize: FONTE.pequena },
  beneficioGeradoDescricao: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  cashbackBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#BBF7D0",
    backgroundColor: "#ECFDF5",
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    gap: ESPACO.md,
  },
  cashbackTitulo: { color: CORES.textoSecundario, fontWeight: "700", fontSize: FONTE.pequena },
  cashbackValor: { color: CORES.sucesso, fontWeight: "900", fontSize: FONTE.grande },
  cashbackToggle: {
    height: 40,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: CORES.primario,
    paddingHorizontal: ESPACO.md,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.xs,
    backgroundColor: "#fff",
  },
  cashbackToggleAtivo: { backgroundColor: CORES.primario },
  cashbackToggleTexto: { color: CORES.primario, fontWeight: "900" },
  cashbackToggleTextoAtivo: { color: "#fff" },
  beneficioResumo: {
    borderTopWidth: 1,
    borderTopColor: CORES.borda,
    paddingTop: ESPACO.sm,
    gap: ESPACO.xs,
  },
  beneficioLinha: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  beneficioResumoLabel: { color: CORES.textoSecundario, fontSize: FONTE.pequena },
  beneficioResumoValor: { color: CORES.texto, fontWeight: "800" },
  beneficioResumoDesconto: { color: CORES.sucesso, fontWeight: "900" },
  beneficioResumoTotal: { color: CORES.texto, fontSize: FONTE.media, fontWeight: "900" },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: CORES.borda,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
    fontSize: FONTE.media,
    color: CORES.texto,
    backgroundColor: "#fff",
  },
  inputMultilinha: { minHeight: 80, textAlignVertical: "top" },
  troco: { color: CORES.sucesso, fontWeight: "800", fontSize: FONTE.media },
  resumo: {
    backgroundColor: CORES.superficie,
    borderRadius: RAIO.md,
    padding: ESPACO.md,
    borderWidth: 1,
    borderColor: CORES.borda,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ESPACO.md,
    ...SOMBRA,
  },
  resumoLabel: { color: CORES.textoSecundario, fontSize: FONTE.pequena, fontWeight: "700" },
  resumoValor: { color: CORES.texto, fontSize: FONTE.titulo, fontWeight: "900", marginTop: 2 },
  resumoSubvalor: { color: CORES.textoSecundario, fontSize: FONTE.pequena, marginTop: 2 },
  resumoAcoes: { flex: 1, gap: ESPACO.sm },
  botaoSalvarAberta: {
    minHeight: 48,
    borderRadius: RAIO.md,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.xs,
    paddingHorizontal: ESPACO.sm,
  },
  botaoSalvarAbertaTexto: { color: CORES.primario, fontSize: FONTE.pequena, fontWeight: "900" },
  botaoFinalizar: {
    minHeight: 52,
    borderRadius: RAIO.md,
    backgroundColor: CORES.sucesso,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: ESPACO.sm,
  },
  botaoDesabilitado: { opacity: 0.5 },
  botaoFinalizarTexto: { color: "#fff", fontSize: FONTE.media, fontWeight: "900" },
  scannerContainer: { flex: 1, backgroundColor: "#000" },
  camera: { flex: 1 },
  scannerOverlay: { flex: 1, alignItems: "center", justifyContent: "center", padding: ESPACO.lg },
  fecharScanner: {
    position: "absolute",
    top: 54,
    right: 24,
    width: 44,
    height: 44,
    borderRadius: RAIO.circulo,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  frameScan: {
    width: "82%",
    height: 180,
    borderWidth: 3,
    borderColor: "#fff",
    borderRadius: RAIO.lg,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  scannerTexto: { color: "#fff", marginTop: ESPACO.md, fontSize: FONTE.media, fontWeight: "800", textAlign: "center" },
  botaoScanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: ESPACO.sm,
    marginTop: ESPACO.md,
    backgroundColor: CORES.primario,
    borderRadius: RAIO.md,
    paddingHorizontal: ESPACO.md,
    paddingVertical: ESPACO.sm,
  },
  botaoScannerTexto: { color: "#fff", fontWeight: "800" },
});
